### ISSUE TITLE
query->result() returns empty

### ISSUE THREAD

**Issue by li9ht** [bcit-ci/CodeIgniter#1125]
$query->result() is returning array{0}
while $query->result_array() is returning correct result .
driver odbc database informix

**Comment by tthanhlong** [comment]
I met the same error with whyb.
$query->num_rows() return 19605 but $query->result_array() does not return anything. There are no errors found. 19605 is not very large data, is it right? 
Please help.

**Comment by whyb** [comment]
@tthanhlong , my database driver is odbc, ms sql server, But I met the problem two year ago.
I not sure the new version was resolved it?

**Comment by tthanhlong** [comment]
Memory limit caused this problem.
Default is 128M, but we can set memory_limit = 1024M or higher and you should be good.
ini_set('memory_limit', "1024M");

We also set unlimited by:
ini_set('memory_limit', "-1");

but it isn't be encouraged due to memory leak somewhere and out of control.

I changed to appropriate number and it seems to be fix.

Regards!
