### ISSUE TITLE
SQL EXPLAIN badly needed (profiler or output)

### ISSUE THREAD

**Issue by iazi** [bcit-ci/CodeIgniter#1534]
There seems to be no option with codeigniter's active record to enable EXPLAIN before SQL statements. It would be nice having it in the profiler for example.
Joan

**Comment by Brian-Webb** [comment]
+1

**Comment by DavidOtis** [comment]
It seems to me that this should be handled in the individual db drivers because each different database has different explain syntax. Instead of printing them in the in the profiler, I think an explain function should just return the results which would allow users to print/log/email or do whatever else they want to with them. Thoughts?

**Comment by jim-parry** [comment]
Should there be an explain() method in the DB_Driver, with optional parameters?
No expectation about what it returns, nor about the parameter interpretation ... just an expectation that each database driver will implement it in an appropriate fashion.

**Comment by DavidOtis** [comment]
Yes, I think there should be an explain() method in the DB_Driver, but I'm not sure what optional parameters it would need. Shouldn't it just take in the query to be explained?

**Comment by narfbg** [comment]
"No, I don't think we should have [put functionality name here]" - said no user ever. :)

**Comment by narfbg** [comment]
If someone wants to have a go at this - submit a pull request. No use having this issue just sitting open though.
