### ISSUE TITLE
SQLSRV: N prefix should be added before any value to be inserted in NVARCHAR field

### ISSUE THREAD

**Issue by Loupax** [bcit-ci/CodeIgniter#1602]
Not sure if I should post this here, but here it goes...

Here is the deal: When I try to insert unicode values to a NVARCHAR column, the query should be something like this:

INSERT INTO test_table (title) VALUES (N'Iñtërnâtiônàlizætiøn')

Activerecord generates this query

INSERT INTO test_table (title) VALUES ('Iñtërnâtiônàlizætiøn')
and this makes all special character information to be stripped from the string, making the inserted data being this: Internationaliz?tion

If this functionality is implemented, it guarantees painless UTF-8 data inserting and fetching from SQL servers

**Comment by ChristosGeorgiou** [comment]
Why this is a 4.0 feature? Maybe we need a temporary workaround for this to support unicode now on MSSQL. I think an 'ugly' or performance-intense' fix is probably better that nothing.

**Comment by narfbg** [comment]
Many years later, but with more clarity and knowledge on the subject ...

This had nothing to do with prepared statements ... I don't know what the hell I was thinking when I said that. In fact, to the extent that it ever would be related, even PDO's prepared statements couldn't handle this until PHP 7.2 (which obviously didn't exist at the time when this issue was opened) - see https://wiki.php.net/rfc/extended-string-types-for-pdo.

It's impossible to do not without prepared statements, but without prior knowledge of the column type. Only ORMs have such knowledge and CI doesn't include an ORM, so ... we can't do anything about this.
