### ISSUE TITLE
Array Validation with Callback-function. Form Validation Class

### ISSUE THREAD

**Issue by bitbucket-import** [bcit-ci/CodeIgniter#193]
It might be useful to somehow extend usual array validation (in Form Validation Class) using callback-function.

Handling `<input type="checkbox" name="field[]" value="val" />` with this code:
    $this->form_validation->set_rules('field[]', 'field_name', 'callback_check_field');

passes to the callback function every element of "field" individually, and the quantity of function calls equals to the quantity of elements in array.

Validation of the same html input with this code:

    $this->form_validation->set_rules('field', 'field_name', 'callback_check_field');

passes to the callback function the whole array "field", and the quantity of function calls still equals to the quantity of elements in array.

It's not good when, for example, in callback function there is a db request `$this->db->where_in($field)->...` or something.
It would be great to have possibility to validate the whole array at once, with only one callback-function call.

**Comment by quasiperfect** [comment]
The ability to be able to pass the whole array to a validation function would be great

**Comment by narfbg** [comment]
@jim-parry 

There's some interest, but it's also a bit of a challenge due to how the FV class works - `_execute()` will recursively call itself for any array field, so it can validate the separate elements of the array.

Changing this behavior for a specificly chosen rule (if such existed) may be a feasible change, but for an arbitrary callback you can never know what the intention is.

I've left this open over the years because I agree that it can be really useful, but it can't happen without significant changes.

**Comment by jim-parry** [comment]
I think it's best left on ice, in the "possible future features" pile.

**Comment by Asssimilate** [comment]
Array validation on callback methods actually worked in at least version 2.2.1. Since migrating to 3.0.0 this no longer works as it did in 2.2.1 (maybe other versions too).
