### ISSUE TITLE
Feature request: split long session cookie into few less-than-4096b cookies

### ISSUE THREAD

**Issue by dtmax** [bcit-ci/CodeIgniter#2085]
I'm using cookie-based sessions.
Sometimes, when session contains a lot of info, especially for encrypted sessions, cookie size is bigger than 4096 bytes. This is not supported by some(all?) browsers. 

Idea is to split the session cookie into smaller chunks when sending "Set-cookie" header. For example, ci_session_1, ci_session_2 etc. And then recompose it back in CI core.

**Comment by yehudahkay** [comment]
@narfbg we are using codeigniter 2 and when the userdata becomes too large the session will end, apparently because of the cookie size. However we have a ci_sessions table in the database and are using these options:

$config['sess_encrypt_cookie']	= TRUE;
$config['sess_use_database']	= TRUE;

Why is codeigniter still using the cookie even though we've set to use database?

**Comment by narfbg** [comment]
There's a reason why CI2 is no longer supported, and why the session library was completely rewritten in CI3. Stop using it.
