### ISSUE TITLE
Make CodeIgniter PSR-0 Compatible

### ISSUE THREAD

**Issue by davidbarratt** [bcit-ci/CodeIgniter#2251]
I think it would be really beneficial for CodeIgniter to catch up with the rest of the PHP world (namely Zend & Symfony) by supporting the PSR-0 Standard:
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md

More information on PHP Fig:
http://www.php-fig.org

Doing this would allow CodeIgniter to be included with Composer:
http://getcomposer.org

This would allow PHP developers to easily get CodeIgnitor and include it in their next/current project.

thansk!

**Comment by inadarei** [comment]
Sorry, guys, but this is ridiculous. PHP 5.2.3 was end of life 4 years ago (http://php.net/eol.php). What can possibly be justification of sticking with it and sacrificing any sanity in class loading?

**Comment by dmyers2004** [comment]
**"This would allow PHP developers to easily get CodeIgnitor and include it in their next/current project."**
Uh, doesn't adding "codeigniter/framework": "dev-develop" to the composer.json file not satisfy his need?
What are these people not understanding about Composer?
The package is right here: https://packagist.org/packages/codeigniter/framework

**Comment by davidbarratt** [comment]
_sigh_ I wrote that two years ago. :) 

Although, we aren't using Composer (or any other PSR-0/PSR-4 autoloader to load the classes), so I suppose my point is more to use a PSR-0/PSR-4 autoloader than to use Composer

**Comment by dbernar1** [comment]
It does not seem that you guys understand free software, so I will explain the basic mechanism to you briefly:

A piece of software which is distributed without restrictions on its users, such as CodeIgniter, is provided  AS IS, and freedom is granted to the users to modify the software in whatever way you need it modified.

The way that applies to our current scenario and the issue brought up here is that you are free to hit the Fork button on the top, and adjust the software to your needs and then put in a pull request. If users of CodeIgniter care about the change you made, they can even start using your version instead of the version provided here, etc.

One does not simply whine about missing functionality in free software.

**Comment by davidbarratt** [comment]
@dbernar1,

Your comment is extremely rude and disrespectful. 

I'm pretty sure everyone here understands free software... do you understand that we have the freedom to whine? we have the freedom to make a feature request?

What's the point in doing all of that work if I have to maintain it myself after the fork? Shouldn't we favor collaboration over competition?

**Comment by dmyers2004** [comment]
We can take this off line to not fill this issue with off topic posts. You can contact me via my github profile.  I personally don't understand everyone's comments on "CodeIgniter isn't compatible with Composer / Packgist" I have been using Codeigniter this way for over a year and not only include CodeIgniter as a Composer package but I also use a number of Composer packages with CodeIgniter. For example monolog and guzzlehttp/guzzle to name just two. I honestly would like to continue this discussion as I am personally confused why this question is asked over and over. I am beginning to feel I am missing something? Please contact me.

**Comment by inadarei** [comment]
@davidbarratt there is really no need for disrespectful rhetoric. I am sure there are people on this thread and in the community that have way more experience with open-source than you are assuming.

Either way, the whole point of successful open-source is healthy community and ability to listen to each other and discuss things. 

There are many things in PHP that is only available since version 5.3. Plus 5.2 was abandoned 4 years ago and even the most conservative Linux Distros (RH and CentOS) ship with 5.3 by default at this point. 

It is not crazy to ask in 2015 why is the upcoming version of a framework trying to support PHP 5.2. I am still reading through https://github.com/bcit-ci/CodeIgniter/pull/3450 to try get an answer to that. I think I may be through that loooong discussion in couple weeks or so :)

**Comment by inadarei** [comment]
@dmyers2004 CodeIgniter is indeed on Packagist (https://packagist.org/packages/codeigniter/framework) and can be installed through composer, but that's not what we are talking about, really.

If you install CodeIgniter via composer, right now, you really are not doing anything but downloading a "zip file" via alternative means. Code Igniter cannot currently leverage any of the Composer's auto-loading capabilities and CI doesn't have namespaces because namespaces are only available since PHP 5.3.

PSR-compliant auto-loading and namespace usage are pinnacles of proper, modern PHP development. CI code, in contrast, is stuck in decade-old style of PHP development that is hugely outdated. 

To be specific, currently CI's composer.json has no PSR-4 or PSR-0 auto-loading: https://github.com/bcit-ci/CodeIgniter/blob/develop/composer.json instead using good-ol' explicit "require" calls and class names use prefixes instead of namespaces.

**Comment by dmyers2004** [comment]
Composer brings CodeIgniter down into my composer vendor folder.
Then I just change the line in the index.php file that is there exactly for this purpose (for as long as I can remember).

$system_path = '../vendor/codeigniter/framework/system';

When I want to update my CodeIginiter just like any other Composer Package from the command line I simply type "composer update" new latest and greatest version based on my composer.json entry.

Finally support for Composer is already built into CI3

The manually specifically states

"Additionally, if you want CodeIgniter to use a Composer auto-loader, just set $config['composer_autoload'] to TRUE or a custom path in application/config/config.php."

http://www.codeigniter.com/userguide3/general/autoloader.html?highlight=composer

Of course in order for the 3rd party composer code to work you need PHP 5.3 or higher (I am currently running CI on PHP 5.5.19)

Then I bring in guzzle for example just like the guzzle read me states

$client = new GuzzleHttp\Client();

Sure CodeIgniter still uses $this->load->library('Page'); with the $this->page->build('books/index',$data); syntax but, I'm not worried about "being decades behind the curve" because I can't simply use page::build('books/index',$data);

**Comment by inadarei** [comment]
@dmyers2004, there're are people who still write code in assembler and enjoy it immensely. They are free to do so, given that it doesn't affect their productivity and they can make living do so.

PHP has *clearly* moved on from pre-5.3 style of code. Furthermore, it is simply insecure to deploy code on EOL-ed (4 years ago!) PHP version.

So, you can do whatever pleases you, but it is still very unclear – what's the urge of sticking with the past in the ucoming (!) release of Code Igniter?

**Comment by narfbg** [comment]
OK, this is just ranting, and on an issue that was closed 2 years ago. I'm locking this thread.

@inadarei You were linked to another thread already, if you don't get your answers there - sorry, but that's about all that can be said.
