### ISSUE TITLE
Do we need the reference sign in $CI =& get_instance() ?

### ISSUE THREAD

**Issue by vlakoff** [bcit-ci/CodeIgniter#2307]
Or more exactly, `$CI = &get_instance()`

Looks like as `get_instance()` and `CI_Controller::get_instance()` return references, there is no need to use reference sign elsewhere.

**Comment by krskrs** [comment]
Hi guys, I ended up here while trying to find out why nowadays CI3 is still using references in its core.

While I understand that it was surely required with PHP4.x, with modern PHP, it should no longer be. 

The example from @narfbg with the $dummy variable is inappropriate in this context, because objects are handled differently than Strings, and I totally agree with @vlakoff and @TheDigitalOrchard .. 

By looking at how the reference operator is still being utilized, one might think that CI is trying to maintain compatibility with PHP 4, but obviously this is not the case.

So I think too that it should be removed, to have a clearer code, without a redundant operator that might only create confusion for people which try to understand how objects work in PHP. They might think that objects would be returned by value (as a copy), while it's not true.

Quoting from PHP manual:

> Returning by reference is useful when you want to use a function to find to which variable a reference should be bound. Do not use return-by-reference to increase performance. The engine will automatically optimize this on its own. Only return references when you have a valid technical reason to do so. To return references

http://php.net/manual/en/language.references.return.php
