### ISSUE TITLE
PHP 5.5+ and mysql_pconnect()

### ISSUE THREAD

**Issue by ghost** [bcit-ci/CodeIgniter#2595]
please check this http://pastebin.com/jYepiCec

i'm running php 5.5+

**Comment by thezoggy** [comment]
I ran into this myself on php 5.5 with latest CI 2.x and the simple fix switching from `mysql` to `mysqli` did NOT work..  I saw a slew of issues and with the whole app failing for multiple reasons.

Turns out that setting the port with the hostname is fine for mysql but breaks mysqli.
`$db['default']['hostname'] = 'localhost:3306';`

So not sure if its worth touching 2.x code to catch this.. but made me question what if you wanted to run sql on a non standard port using mysqli.. how would you handle this in CI?

**Comment by narfbg** [comment]
> I ran into this myself on php 5.5 with latest CI 2.x and the simple fix switching from mysql to mysqli did NOT work.. I saw a slew of issues and with the whole app failing for multiple reasons.

The "latest CI 2.x" was abandoned more than a year ago.
It's dead. You shouldn't be trying anything with it.

> Turns out that setting the port with the hostname is fine for mysql but breaks mysqli.
>`$db['default']['hostname'] = 'localhost:3306';`
>
> Once I changed it to drop the port, mysqli was happy
>`$db['default']['hostname'] = 'localhost';`

Naturally, it says 'hostname' and not 'hostname+port' ...

> So not sure if its worth touching 2.x code to catch this.. but made me question what if you wanted to run sql on a non standard port using mysqli.. how would you handle this in CI?

Step 1: Upgrade.
Step 2: Use the 'port' option - it's not present in the config by default, but it does exist.

---

I only replied because 'port' is hard to find unless you look at the actual CI code, so it's only fair that somebody points it out. But please note that this is a bug tracker and not a place to seek tips.

**Comment by thezoggy** [comment]
If its not broke... but seriously I do understand and agree as a dev myself.
I went to go move to 3.x at one point but too much time was going to be required to just get everything working back to how it was on 2.x thus I just stayed. I do plan to do 3.x but probably by then 4.x will come out. 

Anyways, I was simply adding my findings to this issue as its relevant and I'm not seeking tips (as you are trying to provide guidance). Because myself like many others stumble upon this github issue when searching for the issue and after following the 'fix' it lead me to find out that I had something wrong that only popped up when I switched to mysqli...  and to be fair there are many apps that define 'host' or 'hostname' to be ip/name with port. which is what I assumed since there was no mention of a port config entry or anything about running on non standard ports.
