### ISSUE TITLE
Query builder: oci8 driver generates invalid query when asterisk and group by are used

### ISSUE THREAD

**Issue by ostrolucky** [bcit-ci/CodeIgniter#3230]
``` php
$this->db->group_by('column')->get('table')
```

Generates

``` mysql
SELECT * FROM table GROUP BY column
```

Which is not valid oracle query. Therefore query builder does not generate valid cross-database queries. Oracle can't select all columns using asterisk in select portion in combination with group by.

**Comment by internalsystemerror** [comment]
Assuming that an entire application uses only the query builder, is the idea of the CI DBAL, that the same code can work regardless of the database? I was under the impression this was the point, however if there is a requirement to modify code when changing database type, then the DBAL isn't very good imo.

If as @narfbg suggests the issue is MySQL allows something it shouldn't, would it be better to generate a warning to the user suggesting their logic is broken?

**Comment by narfbg** [comment]
Depending on the user's intent, it may be broken logic ... or not. CI typically doesn't generate warnings and this specific case is a fairly rare limitation.
