### ISSUE TITLE
$HTTP_RAW_POST_DATA depricated message using PHP 5.6 Heroku

### ISSUE THREAD

**Issue by hamiltonmascioli** [bcit-ci/CodeIgniter#3254]
Started getting this warning using PHP 5.6 Heroku using PaperTrail reporting..

AH01071: Got error 'PHP message: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0\n', referer: 

Looks like CodeIgniter should begin using php:://input stream instead.

**Comment by vikingjs** [comment]
For those happening by here, it turns out this is caused by sending ajax post messages with no data in them to php 5.6 servers. See https://bugs.php.net/bug.php?id=66763.

It is not likely to be fixed on the PHP side; so ultimately you will either have to update your php.ini (which will eventually break anyway), or send dummy data from the client.
