### ISSUE TITLE
Double session issue in Safari 8 on Mac OSX Yosemite

### ISSUE THREAD

**Issue by twistedpixel** [bcit-ci/CodeIgniter#3330]
I had a look through issues and couldn't find any reference to this so thought I'd check. While I came across this issue in Codeigniter 2.2, I'm happy to test further in CI3 if this issue hasn't already been discussed.

On testing a new production site, I found that only with Safari 8 running on Yosemite (possibly just Safari 8) a duplicate session is being generated. Identical IP, one session has correct user data set but one has empty session data. The session that appears to be correct has user agent

<code>Safari/10600.1.25 CFNetwork/720.0.9 Darwin/14.0.0 (x86_64)</code>

while the session I would call correct has user agent

<code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10) AppleWebKit/600.1.25 (KHTML, like Gecko) Version/8.0 Safari/600.1.25</code>

This issue does not appear on any other browser I tested, including Safari 7.

Like I say, this may be fixed/addressed/known in CI3 but I wanted to mention it just in case. Happy to test further if you think worth investigating.

**Comment by iammapping** [comment]
I also met this "issue" today. The `CFNetwork ` useragent because of safari retrieve fav or touch icons. I think the best solution is adding a "/apple-touch-icon-precomposed.png" to make sure the request never passing to CI `index.php`. If you are unwilling to add such file, rewrite fav or touch icons to file system(return 404 while not found), before rewrite them to CI `index.php`
