### ISSUE TITLE
Session path determination in upcoming session library

### ISSUE THREAD

**Issue by vlakoff** [bcit-ci/CodeIgniter#3431]
Opening a new issue to not clutter #3073.

Trying the feature/session branch some time ago, I encountered the same issue as in https://github.com/symfony/symfony/issues/4908. I remember having had spent a bit of time to figure out the problem.

I think we should either:
- Detect if invalid path, and if so provide the user with helpful message. The solutions are to change PHP session path, or better, specify a session path in CI config.
- Implement a mechanism like in https://github.com/symfony/symfony/pull/5016/files.

**Comment by npulidom** [comment]
I came up with this issue in OSX 10.10.1 with Apache 2.4, PHP 5.6 & CI 3.0 dev. 
Folder `/var/tmp/` must have write perms (chmod -R 777)
In environment config, for OSX platform, make sure is set `session_save_path()` is set.

```php
//CI environment conf
if (defined('ENVIRONMENT'))
{
	switch (ENVIRONMENT)
	{
		case 'development':
			ini_set('display_errors', 1);
			error_reporting(E_ALL);
			//for OSX platform
            if(php_uname('s') == "Darwin")
            	session_save_path("/var/tmp/"); 
        break;
		case 'testing':
            //....
        break;
    }
}
```

**Comment by vlakoff** [comment]
@npulidom Not really the best place to put the code…
@narfbg #3503 should be quite beneficial.

**Comment by narfbg** [comment]
@ both of you ...

The only reason you encountered the error is because you didn't have a `$config['sess_save_path']`.

**Comment by thiagopalooza** [comment]
I did have configured $config['sess_save_path'], but I still get the error...

**Comment by narfbg** [comment]
Having it set to NULL does not mean it's configured ...

**Comment by jouwstrm** [comment]
Please tell me you're not the author of codeigniter.

1. You're way too condescending... Grow Up.
2. sess_save_path should be setup already, or at least come with an example.

**Comment by jouwstrm** [comment]
If you can't talk to users of codeigniter with a little respect, and realize there are bugs in the software still, please don't respond... AND PLEASE DON'T CONTRIBUTE.

sess_save_path should already be setup upon installation or atleast come with an example path.

Grow up.

**Comment by narfbg** [comment]
If you think my comments were disrespectful, you should read what you just wrote yourself.

**Comment by jouwstrm** [comment]
like I said... Grow up.

**Comment by narfbg** [comment]
Oh right, like I'm the one with the sensitivity of an upset teenager ... You're obviously not going to grow up yourself, but please stop spamming us.

**Comment by jouwstrm** [comment]
Hey, I'm just telling you to be a little nicer to the users of codeigniter.

If you were to grow up, you'd be able to realize this, and do something to fix it.

**Comment by narfbg** [comment]
Just because I say "what" instead of "please explain yourself" or similar, that doesn't mean I'm disrespectful.

I get all kinds of shit from all kinds of people, for my work on a free product that I do in my spare time. And for that, I'm not going to start acting like a customer support agent who is paid to be polite and always agree with you. Certainly not because a random guy on the internet told me to "grow up".
The world doesn't revolve around your personal preferences for how other people should speak their minds, and if *you* were to grow up, you would realize that you're not entitled to tell anybody what to do or how to do it. Especially in OSS, you should be publicly shamed for saying "DON'T CONTRIBUTE" to anybody and in any context.

Furthermore, judging by the countless interactions I've had with the OP, he'd also speak his mind freely for anything that he disagrees with, and yet you're the one complaining. In fact, I have a ton of respect for him and he should be perfectly aware of that because I've personally recommended him for a co-maintainer role in CI. So please do yourself a favor and shut the fuck up with this "grow up" already, it just makes you look more and more ridiculous each time you say it.

**Comment by jouwstrm** [comment]
No need for the language. Only children, who haven't grown up yet use that kind of language.

**Comment by narfbg** [comment]
Right ... :D

**Comment by faelpinho** [comment]
Try this:

$config['sess_save_path'] = sys_get_temp_dir();

I'm using UwAmp and WAMP Server.

**Comment by aishwaryacedcoss** [comment]
Thanks faelpinho !!!

**Comment by faelpinho** [comment]
It's works?

**Comment by aishwaryacedcoss** [comment]
yes it works..

**Comment by imamideb** [comment]
sys_get_temp_dir(); is not working.
