### ISSUE TITLE
Bug in Upload library

### ISSUE THREAD

**Issue by josewilsoncc** [bcit-ci/CodeIgniter#3487]
Bug in Upload library

Upload library throw:
Severity: Notice --> Undefined property: Upload::$upload

Even after being included.

**Comment by narfbg** [comment]
Not a bug, that's a typo in your code.

**Comment by josewilsoncc** [comment]
I tried with CodeIgniter-develop 3.0 and fail, it throws the message: Undefined property: Upload::$upload.

This works in the previous versions (CodeIgniter 2.x)

**Comment by Razican** [comment]
If you have an issue, please, put it in the forums, and only post here if it's a confirmed bug, please.

In any case, which is the code producing that error?

**Comment by josewilsoncc** [comment]
The error occurs when call the function "$ this-> upload-> do_upload ()", this happens even when the library 'upload' is loaded "$this->load->library('upload', $config)", this did not happen before, is something recent. (I sorry for my english, I just want to contribute)

**Comment by narfbg** [comment]
You don't want to contribute, you only want your problem to get resolved and you're not listening to anybody who's not doing something in that direction.

I'd let you struggle with it for awhile days until you at least try to debug it yourself, but I was also wrong in my assumption that it's a typo in your code, and it's a fairly complex issue that's not really your fault, so here it is ... 

Your controller, named 'Upload', collides with the library's name (also 'Upload'). Hence why CI is refusing to load the library.

This did work in CI2, but that doesn't make it a bug in CI3 - it's quite intentional. An obvious work-around is to rename your controller, but if you prefer a more hacky way - creating a MY_Upload class extension should also make it work, even if it's an empty class:

    // application/libraries/MY_Upload.php
    class MY_Upload extends CI_Upload {}

However, there's no guarantee that a future change won't break this hack too, so please just rename your controller. You can use the routing configuration if you really care about having '/upload/' in your URL.

**Comment by josewilsoncc** [comment]
Thank you very much, it works, could change the name in the tutorial for beginners not have this error.

**Comment by josewilsoncc** [comment]
This is a possible update to official documentation?

![changes1](https://cloud.githubusercontent.com/assets/6321568/5825952/31b4f102-a0bd-11e4-87f7-0aa9ec5735b5.JPG)
![changes2](https://cloud.githubusercontent.com/assets/6321568/5825957/38a9a28c-a0bd-11e4-8c67-bbb75522991a.JPG)
