### ISSUE TITLE
Unable to generate key

### ISSUE THREAD

**Issue by arisdario** [bcit-ci/CodeIgniter#3608]
So, as we switched to the new 3.0 CI now i need to rebuild the authentication method, so on create a new key it give me symbols, and i cannot understand why, on made:

$password = "Password";
```
private function _encrypt_password($password){
		$hmac_key = $this->encryption->hkdf($password, 'sha512', NULL, NULL, 'authentication');
        return $hmac_key;
    }

the result is: 
?{?
????\?L??0???u?=??di??>E???9?k?'X?T5#Tk;?!??.?b?2

Is this ok?

**Comment by narfbg** [comment]
First of all, passwords should be *hashed* and not *encrypted*, there's a difference between the two. And you should use PHP's own [password hashing](http://php.net/password) extension, which was designed exactly for that purpose. If you're running on a PHP version lower than 5.5, CI does include [transparent backports](http://www.codeigniter.com/userguide3/general/compatibility_functions.html#password-hashing) of PHP's ext/password functions, which are usable as long as you have at least PHP 5.3.7.

This is also explained in our [security recommendations](http://www.codeigniter.com/userguide3/general/security.html?highlight=security#password-handling).

If you're one of the unfortunate people that can't run even PHP 5.3.7, then you can use `hash_pbkdf()`, which is also available in CI's [compatibility layer](http://www.codeigniter.com/userguide3/general/compatibility_functions.html#hash_pbkdf2). It is not designed for password storage, but it's characteristics make it appropriate nevertheless.

Second, `hkdf()` is a key derivation function, but unlike `hash_pbkdf()`, it's not password-based and it accepts random binary data, not ASCII strings and again - not passwords. You obviously don't know what it does, so you shouldn't use it ...

Please, really, don't use something that you don't understand when you implement security features and even more importantly - don't build your own algorithms. You *will* do it wrong and I'm not saying this to make you feel bad, I'm saying it for your own good. Don't make the mistake of inventing your own.

Security is important and requires very in-depth knowledge of various technologies, and especially in cryptography - there are details that you don't even know exist. If you want your application to be secure, you *must* leave it to the experts in that area, and I'm not even speaking of myself - I got plenty of help from a number of such people when implementing CI's new Encryption class. 

This is also the only reason I'm being that descriptive in this reply instead of just redirecting you to the [forums](http://forum.codeigniter.com) - a request that you're deliberately ignoring and this is not helping you (I will be closing and locking any question issues that you open here if you continue to do so).

**Comment by arisdario** [comment]
No problem, i asked because before that im was isung $this->encrypt->sha1('Password'); so, if sha1 is not anymore a secure algoritm, and you encourage to use another methods, thatts good, is because i have asked if the result is ok or not. !
