### ISSUE TITLE
自动加载的时候提示：Unable to locate the specified class: Session.php

### ISSUE THREAD

**Issue by ecscrm** [bcit-ci/CodeIgniter#3634]
问题：
$autoload['libraries'] = array('session');
自动加载的时候提示：Unable to locate the specified class: Session.php

可能的原因：
3.0 R2的Session类在子目录下
session class path：system/libraries/Session/Session.php
system/core/Common.php文件的 load_class方法无法自动加载到session子目录下的文件。

**Comment by vkeranov** [comment]
You can use English... Don't you think?!

Да та таковам у джинса китайски аз... Фу!

**Comment by bjjay** [comment]
$autoload['drivers'] = array('session');

**Comment by piece601** [comment]
@ecscrm Say:
$autoload['libraries'] = array('session');
When autoloaded will response 'Unable to locate the specified class: Session.php'

Possiable reason:
In 3.0 RC2 at Session sub directory
session class path：system/libraries/Session/Session.php
load_class method can't autoload in session directory's file in system/core/Common.php .

**Comment by narfbg** [comment]
Just for the record, it works completely fine ... my best guess would be that the OP has a MY_Loader extension that isn't updated to work with CI3.

**Comment by logzhouchen** [comment]
Hi, I just meet the same error. And I just found the condition:
$autoload['libraries'] = array('session','database');     // I load the session library automatically
And CI_Session will be constructed in the method initialize() of Loader.php，just because the Session.php is in /system/libraries/Session/Session.php （not just /system/libraries/Session.php ),so it indeeded constructed in  _ci_init_library() of Loader.php and 
$this->_ci_classes[$object_name] = $class;    //_ci_classes is the reference of &is_loaded method in Common.php

function &is_loaded($class = ''){
		static $_is_loaded = array();
		if ($class !== ''){
			$_is_loaded[strtolower($class)] = $class;
		}
		return $_is_loaded;
}
and 'session' is added to the variable--   $_is_loaded

And then when the constructor of CI_CONTROLLER is invoked next time,
public function __construct()
	{
		self::$instance =& $this;
		foreach (is_loaded() as $var => $class){
			$this->$var =& load_class($class);
		}

		$this->load =& load_class('Loader', 'core');
		$this->load->initialize();
		log_message('info', 'Controller Class Initialized');
	} 
It tries to instantiated CI_Sesson with the method load_class, which just check the folder /system/libraries/, while the Session.php is just in /system/libraries/Session/. Then the error "Unable to locate the specified class: Session.php" is reported.

**Comment by logzhouchen** [comment]
My pre_controller hook extends CI_CONTROLLER to fetch the objects like $this->input, and when when the actual controller is met（the constructor of CI_controller is invoked）, the problem is met
