### ISSUE TITLE
Form with no ACTION

### ISSUE THREAD

**Issue by schinaider** [bcit-ci/CodeIgniter#3681]
Hi guys,
I'm using AngularJs with Codeigniter 3. In Angular JS, we don't use 'action' attribute, cause all post/get request use AJAX. So, CI3 don't give us the possibility of create a form without Action attribute, i propose to you, guys, that you change that. I change the code 'system/helpers/form_helper.php' to do that like this: When i give the value 'noaction' to the parameter '$action' of the 'form_open()' function, no 'action' attribute will be print in html code.

if($action=='noaction')
$form = '<form '.$attributes....
else
$form = '<form action="'.$action.'"'.$attributes.......

**Comment by mwhitneysdsu** [comment]
In HTML 5, when the action attribute is not provided on the form element, the browser is supposed to set it to the current URL (though it likely does this internally when determining how to handle submission, rather than outputting it in the DOM).

In HTML 4, the action attribute is required, though the behavior is undefined if it is set to something other than an HTTP URI (in other words, it may vary from one browser to the next).

Personally, I think AngularJS should supply a method to prevent the default action even when the action attribute is defined, but they probably thought they were being helpful when they made the code behave the way it does.

That said, If you're going to set a value to indicate to the form_open() function that it should generate a form element without the action attribute defined, it should probably be an easily-tested value which is not a string, since there's always the chance that someone will want to (or already does) use 'noaction'. For example, you could use the boolean value false:

$form = '<form';
if ($action === false)
{
    $form .= "{$attributes}>\n";
} 
else
{
    // set $action with existing code, then create the form tag
    // ...
    $form .= " action='{$action}'{$attributes}>\n";
}

**Comment by ivantcholakov** [comment]
What do you think about the following attribute:
action="javascript: return false;"

**Comment by schinaider** [comment]
https://docs.angularjs.org/api/ng/directive/form

"For this reason, Angular prevents the default action (form submission to the server) **unless the <form> element has an action attribute specified**."

I can't has an action attribute,

**Comment by narfbg** [comment]
You're not required to use `form_open()` or any of the form helpers ... In fact, I'd discourage you to do so if your logic is in JS, it is not built for that.
