### ISSUE TITLE
$this->form_validation->set_rules with empty rule will fail

### ISSUE THREAD

**Issue by m4ikel** [bcit-ci/CodeIgniter#3736]
Using $this->form_validation->set_rules('username', 'Username', array()); will validate.
$this->form_validation->set_rules('username', 'Username', ''); will fail.

With codeigniter 2.x this worked without issue:

I added hotfix to overcome this issue.

if(!empty($rules))
{
	$rules = explode('|', $rules);
}
else
{
	$rules = array();
}

**Comment by narfbg** [comment]
Why would you want to have empty rules?

**Comment by joshuahamilton** [comment]
I can see some possible benefit if rules are generated dynamically for some reason, but my feeling on the matter is either an empty array and string should both work OR should both fail. The behaviour as described is inconsistent.

Without knowing the context of the OP's code, I'm inclined to make empty rules fail with the assumption that if you don't need to validate it, then just comment out or delete the line. If you do, then you need to be specific.

**Comment by m4ikel** [comment]
Because set_value only applies when the input has been defined through set_rules. The current behaviour is as joshua is saying inconsistent. Also with 2.x '' would validate obviously.

Why would the following validate:
$this->form_validation->set_rules('username','Username');

And a empty rule fail
$this->form_validation->set_rules('username','Username','');

And a empty validate?
$this->form_validation->set_rules('username','Username',array());

**Comment by narfbg** [comment]
Consistency ... the argument for everything in the PHP world. This is a case that you should regard as having "undefined behavior", not one that you should be expecting any sane result from.

The `set_value()` helper uses `CI_Form_validation::set_value()` *only if* you've loaded the form validation library and if you've defined rules for that field. It otherwise looks at `$_POST` for the value. If anything is an issue here, it's that you're not actually defining rules, yet `CI_Form_validation::has_rule()` returns TRUE.

**Comment by evertramos** [comment]
Hi there,

Here is what I got...

I do want the form to be repopulated, although, it works with <code>set_value()</code> even if there is no validation rules set. 

But when the field is an array, it gets an error:

<code>\<input name="fullname[]" value="<?php echo set_value('fullname[]'); ?>"></code>

If the 'fullname[]' does not have a validation rule set or set to 'array[]' (empty array) it will bring an error:

<code>Array to string conversion</code>

Is this an Issue or should use empty array ('array()') for the form validation rule and that´s it?

Thanks very much!

**Comment by narfbg** [comment]
@evertramos This is a bug tracker, you can't just write an unrelated comment in the first issue you find ... please post your questions on the [forums](http://forum.codeigniter.com/) instead.

**Comment by andersonunsonst** [comment]
I myself already I was wrong about set_value
You could put this in the userguide ?

"The set_value() helper uses CI_Form_validation::set_value() only if you've loaded the form validation library and if you've defined rules for that field. It otherwise looks at $_POST for the value."

**Comment by evertramos** [comment]
@narfbg Sorry man... I was not sure how to proceed, but this is not unrelated. Actually I saw that you close de issue, but I had the same problem, Just would like to confirm and make it clear for future reference. Sorry for that.

**Comment by narfbg** [comment]
@andersonunsonst 

I'd argue that there's nothing in the form helper's manual suggesting that it does use the form validation *library* in the first place (and also that this is unrelated), but good call: 3da611e5b4c9cda8d70975d638f6f05066e46bc4

@evertramos 

It is *completely* unrelated. :)

This issue was about whether `CI_Form_validation::set_rules()` should accept an empty set of rules. Granted, the OP did somehow mix that with a use-case of his for `set_value()`, but even that has nothing to do with our own usage of `set_value()` ... I don't know how you've connected the two.
