### ISSUE TITLE
PSR-1

### ISSUE THREAD

**Issue by Tjoosten** [bcit-ci/CodeIgniter#3763]
I i was thinking can we convert the function names to `StudlyCaps`. 

if yes i can code this and send it with a PR if you want.

**Comment by rougin** [comment]
Hmmmm. I don't think that it will be accepted here. Please check the following issues related to that below:
https://github.com/bcit-ci/CodeIgniter/issues/3438 https://github.com/bcit-ci/CodeIgniter/issues/3274 https://github.com/bcit-ci/CodeIgniter/issues/2251 https://github.com/bcit-ci/CodeIgniter/issues/2754

**Comment by jim-parry** [comment]
Not appropriate for CI3, thanks

**Comment by Quix0r** [comment]
PSR-x are common coding standards and conventions that every modern framework/application should follow and at least support. Generally rejecting it means you don't want to follow common standards, period.

Reconsider having namespaces and `CamelCased` classes and `lowerCamelCase` method names with next CI version, say 4/5?

**Comment by narfbg** [comment]
Reconsider trying to educate seasoned PHP framework maintainers on what PSRs are.

**Comment by Quix0r** [comment]
_P_HP _S_tandards _R_ecommendations: http://www.php-fig.org/psr/

**Comment by narfbg** [comment]
FYI, that wasn't a request to link resources. It was a subtle way of telling you that nobody needed that comment, not least because its original (stricken-through) content is incorrect.

And I'm not trying to start an argument here. Just note that if somebody maintains a piece of PHP software popular enough for you to use, there is zero chance of them not knowing what PSRs are.
