### ISSUE TITLE
FTP delete_dir issue as well as solution

### ISSUE THREAD

**Issue by mainuljs** [bcit-ci/CodeIgniter#3787]
Ftp delete_dir() does not work. 
Problem:
	if ( ! preg_match('#/\.\.?$#', $list[$i]) && ! @ftp_delete($this->conn_id, $list[$i]))
	{
		$this->delete_dir($list[$i]);
	}

1. Regular expression checking failed. Because unwanted '/' after starting #. Maybe typo.

2. list_files() returns array of only files and folders name. Not the path. So Recursive function argument will be $filepath.$lish[$i] and ftp_delete() path will $filepath.$lish[$i].

3. Final Solution is 
	if ( ! preg_match('#\.\.?$#', $list[$i]) && ! @ftp_delete($this->conn_id, $filepath.$list[$i]))
	{
	$this->delete_dir($filepath.$list[$i]);
	}

**Comment by narfbg** [comment]
It's not a typo, and your suggested final solution makes that whole loop redundant ...

What do you mean by "does not work" exactly? Give us some details.

**Comment by mainuljs** [comment]
<pre>
<code>
$this->delete_dir($filepath.$list[$i]);
</code>
</pre>

**Comment by mainuljs** [comment]
<code>
$this->delete_dir($filepath.$list[$i]);
</code>

**Comment by mainuljs** [comment]
If this function is called like this
```
$filepath='/public_html/';
$this->ftp->delete_dir($filepath);
```
Then in function..
```
$list = $this->ftp->list_files('/public_html/');
print_r($list);
```
return something like this
```
Array ( [0] => . [1] => .. [2] => New Folder [3] => index.php )
```
Then we check for folder(if available) for recursion. If file it will be deleted. And
. or .. check by preg_match()  like
```
preg_match('#\.\.?$#', $list[$i]) // will check . or ..
```
in your function checking like
```
preg_match('#/\.\.?$#', $list[$i])  // extra '/'  after # which not match . or ..
```
 If folder found then recursion happen
```
// Your way.
$this->delete_dir($list[$i]); // delete_dir('New Folder/'); which leads to not found. Incorrect Path  

//my way
$this->delete_dir($filepath.$list[$i]); // delete_dir('/public_html/New Folder/'); found. just concatenate $filepath and $list[$i].
```
Whole function like this
```
	public function delete_dir($filepath)
	{
		if ( ! $this->_is_conn())
		{
			return FALSE;
		}


		// Add a trailing slash to the file path if needed
		$filepath = preg_replace('/(.+?)\/*$/', '\\1/', $filepath);
		
		echo $filepath;
		$list = $this->list_files($filepath);
		if ( ! empty($list))
		{
			for ($i = 0, $c = count($list); $i < $c; $i++)
			{
				// If we can't delete the item it's probaly a directory,
				// so we'll recursively call delete_dir()
				if ( ! preg_match('#\.\.?$#', $list[$i]) && ! @ftp_delete($this->conn_id, $filepath.$list[$i]))
				{
					$this->delete_dir($filepath.$list[$i]);
				}
			}
		}
		if (@ftp_rmdir($this->conn_id, $filepath) === FALSE)
		{
			if ($this->debug === TRUE)
			{
				$this->_error('ftp_unable_to_delete');
			}
			return FALSE;
		}

		return TRUE;
	}

```
Now you may got it. 
Your code shows  'Unable to delete' error.
My code work for me.

**Comment by narfbg** [comment]
It's hardly my code, but yes - I see what you mean now.

**Comment by Yomi337** [comment]
Hey guys, i found a very annoying thing in this method, i fixed it for my project and wanna share my solution with you. 

$list = $this->list_files($filepath); returns full paths for each file and folder in $filepath (you can check it by yourself or just read it here http://php.net/manual/en/function.ftp-nlist.php).  So this part ---> $this->delete_dir($filepath.$list[$i]); fails recursion if you trying to delete dir with sub-dir.

e. g. You are trying to delete "application/cache/123/" and you have some "456" folder inside this, so the 2nd iteration will look like $this->delete_dir('application/cache/123/application/cache/123/456'); which causes an error.

I removed $filename from this line $this->delete_dir($filepath.$list[$i]); because $list[$i] already contains fullpath and now i got a pretty good working code.
