### ISSUE TITLE
Database layer is not compiling sql properly

### ISSUE THREAD

**Issue by cperrot** [bcit-ci/CodeIgniter#3794]
see thread http://forum.codeigniter.com/thread-646-post-3402.html#pid3402

problem description for one problem and a solution for another.

**Comment by narfbg** [comment]
The query builder is made for simple things, not to be fed with lines of raw SQL ... that's what `query()` is for.

**Comment by cperrot** [comment]
Let me make it easier for you.

SELECT ProductName, ROUND(Price,2) AS RoundedPrice FROM Products; 

This select is easy and will fail too.

**Comment by narfbg** [comment]
Yes it will, because we handle field names, not functions. And you can optionally disable quoting because of that.

**Comment by mwhitneysdsu** [comment]
The original bug in that particular post only exists in CI 2, not in CI 3. In CI 2, using a mixture of select() and select_sum/min/max/avg functions in which one or more select() calls comes after one of the other methods causes it to ignore the $escape value passed to one or more of the later select() calls. This is because DB_active_rec's _max_min_avg_sum() method doesn't set $this->ar_cache_no_escape[], causing the later select() calls' $escape values to be assigned to the wrong portion of the select statement in the final output.

DB_query_builder's _max_min_avg_sum() method sets $this->qb_no_escape[] = NULL; so any similar issue in CI 3 is actually a different problem with a similar result.

Given the complexity of the select statement in that post, though, we could probably all find different bugs in the output while trying variations of the original input.

It might be useful to have a function like _max_min_avg_sum() to handle numeric/math functions, as a large number of the common functions are very well supported cross-platform.
