### ISSUE TITLE
Duplicate Entry when save Session into database

### ISSUE THREAD

**Issue by mylastof** [bcit-ci/CodeIgniter#3839]
I have activate <code>sess_match_ip</code>, but when save to database, its says <strong>Duplicate Entry ..... for key 'PRIMARY'</strong>.
Is should be unique

**Comment by narfbg** [comment]
'but' is the wrong word to use ... you're getting this error *because* you've enabled that setting, without reading the manual about it.

http://www.codeigniter.com/userguide3/libraries/sessions.html

Also, please use our [forums](http://forum.codeigniter.com/) to ask your questions. We don't provide support here.
