### ISSUE TITLE
Form Validation multiple language

### ISSUE THREAD

**Issue by stefanuswiely** [bcit-ci/CodeIgniter#3889]
Broken multiple language for form validation standard messages if language was set on sesssion.
Load the language, but when run the validation, run will reload form_validation_lang file with default application language file that set at config.php file

Code line #455 at libraries/Form_validation.php 
    $this->CI->lang->load('form_validation');

Maybe the default load can be set at construct. And if user load the lang file for different language will override the original one. Or maybe can add new function to set what language to be use?

**Comment by mwhitneysdsu** [comment]
This should probably be posted to the [forums](http://forum.codeigniter.com/) instead of GitHub. If you use `$this->config->set_item('language', $userLanguage);` once you know the user's language (assuming you get that information early enough in your base controller), the Form_validation library should load the correct language.
