### ISSUE TITLE
Callbacks not run on empty fields in some situations

### ISSUE THREAD

**Issue by jamieburchell** [bcit-ci/CodeIgniter#3904]
Using latest stable CI3 version this code does not run the validation callback if the `image` field is empty:

```
$this->form_validation->set_rules('image', 'Image', [
	'trim',
	[
		'upload_image',
		[$this, 'upload_image']
	]
]);
```

This format does:

```
$this->form_validation->set_rules('image', 'Image', [
	'trim',
	function($value) {
		$this->upload_image();
	}
]);
```

**Comment by jamieburchell** [comment]
I can't think of a situation where having an anonymous function without an error label (example 2) is useful? There is no way to set an error message without using example 1, but I guess this is just by design given you are looking for things that are callable.

Just a thought, but would this syntax be cleaner for assigning a error string to a function?

```
$this->form_validation->set_rules('image', 'Image', [
    'trim',
    'label' => function($value) {
        $this->upload_image();
    }
]);
```

**Comment by narfbg** [comment]
It's not necessarily a validation function ... it could modify the input as well (e.g. like `trim()`). As for the alternative syntax - sure, it's nice, but we already use the other one and this library is becoming a maintenance hell as it is. Introducing another one doesn't really bring any benefit other than being "nice".

**Comment by GloryFish** [comment]
We ran into this issue in our project. We are updating a CI 2.x project to 3.0.1 and have existing custom validation rules defined like so:

```php
$this->form_validation->set_rules($identifier, $description, 'trim|is_natural|alpha_dash_space_apos|less_than[2]');
```
and we implement that rule in a function like so:

```php
  function alpha_dash_space_apos($str) {
    if (! preg_match("/^([-a-z_ '])+$/i", $str)) {
      $this->set_message('alpha_dash_space_apos', 'The %s field may only contain letters, spaces, apostrophies, underscores, and dashes.');
      return FALSE;
    } else {
      return TRUE;
    }
  }
```

The [current documentation](https://www.codeigniter.com/userguide3/libraries/form_validation.html#prepping-data) says "Any native PHP function that accepts one parameter can be used as a rule, like ``htmlspecialchars()``, ``trim()``, etc.". However,  the current implementation of Form_validation::_execute() skips callbacks defined as strings (liek we do above) if the field is empty and required, unless the string begins with 'callback_'. 

I believe changing the [check in _execute()](https://github.com/bcit-ci/CodeIgniter/blob/938c7e4e4d874189fec2bec8532ed70bb8c52f05/system/libraries/Form_validation.php#L606-L614) to this:

```php
if (is_string($rule) && strncmp($rule, 'callback_', 9) === 0) {
    $callback = TRUE;
    $rules = array(1 => $rule);
    break;
}
```
resolves the issue. With this change, rules defined as a string with a prefix of 'callable_' will be set as a rule AND any string which is callable will also be included, even when the field is empty and not required. This ensures that all defined rules will be correctly invoked.

However, this leads to the case that @jamieburchell mentions where it's possible to define a validation rule without an error string. This happens if you specify the name of a custom function and return a BOOL from that function or if you supply a native PHP function that returns a BOOL (e.g. `is_array`) and that funciton does not explicitly call `set_message()` before returning `FALSE`.

I think the underlying problem is that the `Form_validation` class conflates field validation with field "prepping". Validation functions are expected to return a BOOL and some error message needs to be provided. Prepping functions need to return a modified value and don't prevent form submissions; they don't need a defined error message. It's very easy to define a validation function the same way a prepping function is defined and then you run into an implicit assumption in the system that data prepping functions _never_ need to be run if the data is empty. 

I think `set_rules()` should explicitly only support validation rules so that the error message requirement can be enforced. Then a new `set_prep()` method should be added for specifying data transformation functions which don't need error messages.

That way you can't accidentally define a validation rule with no error message that gets skipped when the posted data is empty. 

At the very least, the documentation should _not_ say "Any native PHP function that accepts one parameter can be used as a rule" as that seems to be clearly incorrect.

**Comment by narfbg** [comment]
Lack of the 'required' rule means that an empty value is acceptable - that's the whole point of having 'required' in the first place.

And the documentation is not incorrect, because `set_message()` isn't the only way to map error messages to rule names.

**Comment by GloryFish** [comment]
Check out this example. If I define a validation scenario like this:

```php
$this->form_validation->set_message('my_custom_validation', '{field} failed validation');

$this->form_validation->set_rules('my_field', 'My field',
  array(
    array(
      'my_custom_validation',
      function($str) {
        return FALSE;
      }
    ),
  )
);
```

Even though the field is not required, the Form Validation library will run the callback, validation for 'my_field' will fail, and the message will be displayed.

However, if I define the rule like so:

```php
function my_custom_validation($str) {
    return FALSE;
}

$this->form_validation->set_message('my_custom_validation', '{field} failed validation');

$this->form_validation->set_rules('my_field', 'My field', 'my_custom_validation');
```

my validation function will never be called by the library. You get different behavior based on how the rule is defined. 

The reason why is because the code [here](https://github.com/bcit-ci/CodeIgniter/blob/938c7e4e4d874189fec2bec8532ed70bb8c52f05/system/libraries/Form_validation.php#L606-L614) has no code path for the case where a supplied rule name _doesn't_ begin with 'callback_' but is still callable. 

My change proposed above handles this case explicitly.

Since the code here goes out of it's way to check for additional defined rules even when the field _isn't_ required, I don't think it's correct to say that "Lack of the 'required' rule means that an empty value is acceptable".

**Comment by narfbg** [comment]
I was very careful in picking the word 'acceptable' there ... it is not incorrect exactly because it leaves room for exceptions. And still, honestly, what use do you see in the 'required' rule if not that? Determining whether empty values are accepted is literally its only purpose.

Now, I do have to admit one thing - I have no fucking idea why 'callback_' rules specifically would still run for empty values when there's no 'required' rule. That's something that goes way back before I became involved with CI.
However, if I have to guess, there is some logic in *callbacks* (not just callables, but callbacks - a tiny difference) always running because, originally, those were only controller methods prefixed by 'callback_', and controllers are objects, which means they maintain some kind of state and therefore can be used to execute side-effect logic that's not just validation or sanitization (logging perhaps? who knows ... the possibilities are endless).
Whether people actually use them that way is another story, but that statefulness is what's different between a class method and what you're trying to do with a regular function.

The so called "callables" were just designed as a more flexible version of "callbacks", but it really refers to closures, or anonymous functions, and not really all callables.
Every rule (except 'required') is a callable and so this "callables" exception wouldn't make any sense otherwise. Your proposed change makes everything *but* the predefined rules from `CI_Form_validation` to run at all times, which makes even less sense. :)

Yes, it's all confusing and buried under a pile of confusing and at times probably improper terms, so I certainly don't blame you for not getting the logic behind it, but it's just the way it is and it *does* work as intended.

**Comment by GloryFish** [comment]
Thank you for taking the time to review and respond.

Your point about class or closure state is well taken. With that in mind, allow me to phrase my understanding of the code's intent and you can tell me if I'm on the right track:

"Generally speaking, if a field is empty and isn't required, additional validation functions will not be run against the empty field. However, if there is a custom validation rule defined which is a Class based callback ("_callback") or a closure, the system will always call it so that additional state information can be utilized." 

I think that is what the code expresses and what you intend with the code in `_execute()`. If that's true then that seems reasonable.

I think the documentation could be updated in two small ways to make this more clear:

1. Make it explicit that ordinarily, validation rules aren't run if a field is empty, however the module _will_ call custom controller-based callbacks or anonymous functions every time.
2. Change the wording in the "Prepping Data" section from "Any native PHP function that accepts one parameter can be used as a **rule**, like ``htmlspecialchars()``, ``trim()``, etc." to "Any native PHP function that accepts one parameter can be used as a **prepping function**, like ``htmlspecialchars()``, ``trim()``, etc."

It's reasonable to me that prepping functions wouldn't run if the field is empty, but it's surprising if certain custom rules defined in a specific way don't run every time. Making it explicit that defining custom validation rules with just a string is not the expected use case clears this up.

Also, I think the Upgrade documentation should mention this because it is a change of behavior from 2.0 to 3.0. (I _think_ the change occurred [here](https://github.com/bcit-ci/CodeIgniter/commit/4b90a3746e929f6bbf2b83c71948665c0c31d1fe) although I may be misreading it.)

Our 2.0 code implemented some custom form validation functions which we invoked by including them in a piped string passed to `set_rules()`. These functions were generic validation functions which weren't specific to any particular controller. The 2.0 code called these every time. When we moved to 3.0 we noticed that they were only called when the field was not empty.

I'm not sure how unusual this situation might be, but if you look at the _Cascading Rules_ and _Prepping Data_ sections in the [old documentation](https://ellislab.com/codeigniter/user-guide/libraries/form_validation.html#cascadingrules) it looks like a very reasonable approach for implementing generic custom rules that don't belong in a specific Controller class. This is what we did in our project back in the day.

I first noticed this issue when I went to add a new "conditional required" rule which needed to do some state checking and I needed it to run every time. I have since re-implemented our rules in a small library using the callback functionality rather than with a string identifier and it's working properly.

If the documentation changes above had been in place I would have saved a whole lot of time and just converted all the rules during our initial upgrade.

**Comment by narfbg** [comment]
> Your point about class or closure state is well taken. With that in mind, allow me to phrase my understanding of the code's intent and you can tell me if I'm on the right track:
>
> "Generally speaking, if a field is empty and isn't required, additional validation functions will not be run against the empty field. However, if there is a custom validation rule defined which is a Class based callback ("_callback") or a closure, the system will always call it so that additional state information can be utilized."
>
> I think that is what the code expresses and what you intend with the code in `_execute()`. If that's true then that seems reasonable.

Correct.

> Make it explicit that ordinarily, validation rules aren't run if a field is empty and not required, however the module will call custom controller-based callbacks or anonymous functions every time.

Agreed.

> Change the wording in the "Prepping Data" section from "Any native PHP function that accepts one parameter can be used as a rule, like htmlspecialchars(), trim(), etc." to "Any native PHP function that accepts one parameter can be used as a prepping function, like htmlspecialchars(), trim(), etc."

If this specific sentence is under the "Prepping Data" section, I agree in principle that "prepping function" is better than "rule" here, but otherwise than that ... it seems to me that you're implying the statement itself is wrong and it's not - it would be perfectly correct to say it for validation rules.
For example, using `ctype_digit()` as a validation rule is perfectly fine.

I also get the feeling that you don't quite understand what is meant by "native PHP function" and that's what got you into this whole thing ... The word "native" in there means that we're talking about functions defined by PHP itself and it is there for one reason only - to discourage you from declaring rules as regular global functions.
It is obviously possible, because there's no technical difference in how that function would be called, but you were never supposed to do that in the first place.

> It's reasonable to me that prepping functions wouldn't run if the field is empty, but it's surprising if certain custom rules defined in a specific way don't run every time. Making it explicit that defining custom validation rules with just a string is not the expected use case clears this up.

... I think I answered that in my last sentence above. :)

> Also, I think the Upgrade documentation should mention this because it is a change of behavior from 2.0 to 3.0.

The behavior that you expected was never the intended one. If it is a change in behavior, it's just a regular bugfix and as such it doesn't belong in the upgrade instructions.

> I'm not sure how unusual this situation might be, but if you look at the Cascading Rules and Prepping Data sections in the old documentation it looks like a very reasonable approach for implementing generic custom rules that don't belong in a specific Controller class. This is what we did in our project back in the day.

No it doesn't ... nothing in there suggests usage of regular functions as validation rules. And there are at least two more ways to have rules not tied to a specific controller, that are widely used with CodeIgniter and not just for form validation - putting them in MY_Controller, or in MY_Form_validation. The latter being more reasonable IMO.
