### ISSUE TITLE
Default Routing

### ISSUE THREAD

**Issue by steve-goodwin** [bcit-ci/CodeIgniter#3907]
Porting from CI2 (lastest) to CI3 (latest) there is an issue with the default_controller routing methods.

Prior to CI3 the default_controller would accept:

$route['default_controller'] = 'controller/method/variable';

Now due to a re-write of the Route.php class it looks like its not taking into account the 3rd parameter of the normal routing behaviour documented in the CI User Guide.

The set_default_controller method in the Route.php system class currently see's from the route example above with $this->default_controller;

'variable/method'

and not

'method/variable'

Can this be resolved or a reason given, my applications use this architecture extensively for cached routing and direct redirects to their respective functionality.

**Comment by narfbg** [comment]
'default_controller' was only ever meant to accept controller/method pairs. Nothing else has been documented or considered as a use case.

**Comment by steve-goodwin** [comment]
Thanks for your response narfbg, in CI2 this worked perfectly, every other route in CI is defined using the following notation:

'controller/method/variable'

I find it odd that this functionality has been removed in CI3, my use case I have a content management system which after every page save or deletion rebuilds a cache of routes like so:
```php
$route["default_controller"] = "home/index/1";
$route["explore-education"] = "categories/index/7";
$route["explore-education/(:any)"] = "categories/detail/$1";
$route["explore-education/(:any)/(:any)"] = "courses/detail/$1";
$route["online-cpd"] = "generic/index/8";
$route["meet-the-masters"] = "speakers/index/9";
$route["our-partners"] = "partners/index/10";
$route["venue-hire"] = "venues/index/11";
$route["venue-hire/(:any)"] = "venues/details/$1";
```
As you can appreciate every dynamic website has a homepage and due to the way CI works this is set through the default_controller routing. I can see that the variable name default_controller would suggest this takes a controller/method, but there should be no reason why it cannot take a variable based on how every other route works in CI.

I have got around this issue temporarily by modifying the _set_request() method in the system/core/router.php file, but this is in no way something i'm happy about.

```php
$this->set_class($segments[0]);
		if (isset($segments[1]))
		{
			$this->set_method($segments[1]);
		}
		else
		{
			$segments[1] = 'index';
		}

		array_unshift($segments, NULL);
		unset($segments[0]);
		$this->uri->rsegments = $segments;
```

Will you review this usecase or just dismiss it for the next release? I feel that the default route should accept parameters inline with how all other routes work. If this isn't the case it means for dynamic content users like me are going to have to lookup from the database again for the default route which breaks the time saved by re-generating a cached routing file so not to hit the database on every page load, I don't really want to hard code the index pages database ID.

**Comment by narfbg** [comment]
Every other route uses a "something/something/something/something/etc" notation and is used to translate user input (which 'default_controller' does not, because there's no such input). Which of the segments is a directory, controller, method or an additional parameter is determined afterwards (while for 'default_controller' that's pre-defined).
These two differences are what makes 'default_controller' more of a configuration directive than a route. If it was reasonable to base your expectations about it on other routes' behavior, then you'd also want it to support regular expressions, at which point it becomes very obvious that this is a pointless expectation.

Naming is also not meaningless. It should speak volumes that the setting is called 'default_controller' instead of 'default_route', just as the fact that it's not logical for what even you're calling a *variable* to be used in a static, already known route.

That you think there should be no reason for 'default_controller' to be unlike every other route is because it has previously worked (by accident; read below), you've based your programming logic on it and are now naturally unhappy that this is no longer the case. But that's just what often happens when you take advantage of undocumented behavior, which brings me to the next point ...

This is not a feature that (as you say) was removed, but a side-effect to badly written code - a bug, even if a harmless one. The routing logic was a huge mess, went through major refactoring because of that, and no longer produces that side-effect. In fact, a lot more people have been complaining that 'default_controller' doesn't accept a directory, which it previously did due to the exact same bug.

That being said, I understand that no matter how much better I explain it, that doesn't ease your situation, so here's what I would do - make a 'MY_Router' extension (all system/core/ classes can be overriden that way) and make your `_set_request()` (or better - `_set_default_controller()`) modifications there. We can't cover all use cases by default, but extensions to core classes are always your back-door to making CI behave the way you'd want it to.

**Comment by steve-goodwin** [comment]
@narfbg no worries, thanks for your detailed explanation, I'm not un-happy...before reading your reply I couldn't see any clean way around this without hacking the core system in order to apply this logic. Thanks for your help and clearing this up.
