### ISSUE TITLE
memcached driver for session and cache does not work

### ISSUE THREAD

**Issue by ghost** [bcit-ci/CodeIgniter#3919]
Hi,

I am trying to use memcached as session and cache storage and running into troubles doing so.

For session setting userdata works for the 2 first requests, after that there are huge delays, up 20 sec, and I'm not sure where this comes from. I tested the same server setup without using codeigniter and it works fine:

<pre>
ini_set('session.save_handler', 'memcached');
ini_set('session.save_path', 'tcp://10.126.1.17:11211');

session_start();

$_SESSION['foo'] = 'bar';
$_SESSION['time'] = time();

var_dump($_SESSION);
</pre>

For cache there are no delays but the data is never stored. In the code below both var_dumps output bool(false):

<pre>
public function test() {
$this->load->driver('cache', array(
	'adapter' => 'memcached', 
	'backup' => 'file'
));

var_dump($this->cache->get('foo'));
$this->cache->save('foo', 'test test', 300);
var_dump($this->cache->get('foo'));
}
</pre>

**Comment by shankarbala33** [comment]
Should know the memory space for storing session datas. Core PHP provides
more memory than the Codeigniter. So you couldn't store more datas and
retrieve itself quickly.
That's why you get the different time delays !

**Comment by narfbg** [comment]
The session delays are caused by emulated locks that serve for avoiding concurrency issues ... don't worry about that - the delays will disappear once the writes start working again.  
That being said however, I'm afraid you'd have to debug this one on your own.

**Comment by sneakyimp** [comment]
I'm not sure this comment belongs here, but the CI 3 documentation sample code for memcached doesn't work. The docs need to be updated to reflect the more complex driver loading that actually works.

http://www.codeigniter.com/userguide3/libraries/caching.html#memcached-caching

**Comment by cmeenatchisundaram** [comment]
@sneakyimp & @narfbg 
         One very important and easy to miss thing... If you are using memcache then save_path must have the "tcp://" prefix, if you are using memcached then the save_path should not have the "tcp://" prefix.

**Comment by yahyaerturan** [comment]
I am using memcached for session handling and cache purposes. With the upgrade to CI 3.0.4, it starts to throw the following error (while it was working as expected on CI 3.0.3:

```
Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php5)
```

If I replace CI 3.0.4's `Session_memcached_driver.php` file with 3.0.3's `Session_memcached_driver.php` it is working again.

**Comment by narfbg** [comment]
@yahyaerturan I highly doubt that it is in fact working if you revert to 3.0.3.

The only change in 3.0.4 is that it actually tells you that there's an error, while previously you'd never know that.

**Comment by yahyaerturan** [comment]
@narfbg It's a [short video](https://youtu.be/Skh1IpF4-vg) for making it certain that it works with 3.0.3. 

I reviewed the diff, beside error structure, there is some changes on `_get_lock($session_id)` method, though I am not sure whether it is the reason.

I am working on PHP 5.5.9. There is no line info I can found.

**Comment by narfbg** [comment]
You're confusing "not showing an error" with "working", and in fact the video shows that ...

See that `<sessionId>:lock` key at the [58 second mark](https://www.youtube.com/watch?v=Skh1IpF4-vg&feature=youtu.be&t=58)? If it actually worked, you'd have one more without the ':lock' suffix.

As I said, the only difference is that 3.0.4 actually tells you that something's wrong.

**Comment by narfbg** [comment]
So the question is, which line returns `$this->_failure` for you? You'll have to do some debugging ...

**Comment by yahyaerturan** [comment]
So I proved that you are right :smile: I'll try to dig more..

**Comment by cmeenatchisundaram** [comment]
@narfbg, @yahyaerturan

I have taken the codeigniter version 3.0.3 and 3.0.4 for testing this error.. I used xdebug with netbeans editor.

I noticed that, $this->_success and $this->_failure variables introduced in the 3.0.04 version.

In the write function of session_memcached_driver.php, the line no 198 is a return statement which returns $this->_failure; This is where the problem starts.

If you change this variable from $this->_failure to FALSE, then it is perfectly working in v3.0.04 also without any error(Unknown: Failed to write session data (user). Please verify that the current setting of session...)

If my fix is correct, then guide me how to commit it.

**Comment by narfbg** [comment]
@cmeenatchisundaram Not correct ... you're doing the same thing @yahyaerturan did - thinking that the error message itself is the problem and trying to hide it. That doesn't solve anything.

Line 198 returning failure means that you were unable to obtain a lock. If you're running PHP7, this should fix the issue: c4de3c2f93cb6d2af65b325ae2812fccad7e98b8 (given that the lock was actually acquired, but falsely reported in your case)

**Comment by cmeenatchisundaram** [comment]
@narfbg  

It is returning the value 16( Memcached::RES_NOTFOUND ) when the key doesn't exist in memcached

**Comment by cmeenatchisundaram** [comment]
The above is obtained from getResultCode after executing the touch

The touch returns FALSE(bool)

**Comment by narfbg** [comment]
Why would I ask you what `touch()` returns if that was the final fix?

**Comment by cmeenatchisundaram** [comment]
@narfbg 
  I found the difference between v3.0.3 and 3.0.4..

V3.0.4
-----------
   In the read function, 
            The lock is aquired but the sessionid is not yet set.
Because of this,  In write function, the $this->_session_id is NULL. 
There is a condition check available at the line no. 205 for the lock acquisition. 

But before itself in line 196 the below condition is there to check again the lock
if ( ! $this->_release_lock() OR ! $this->_get_lock($session_id))
{
    return false;
}
    

V3.0.3
-----------
   In the read function, 
            The lock is aquired but the sessionid is also set.
Because of this,  In write function, the $this->_session_id is not NULL. So it is not failing to write the stuff.


Solution
=======
In line no 196, we can add the condition if the lock key is not set then return failure. or else set the session id and fingerprint..then continue the execution...

if (**!isset($this->_lock_key)** && (! $this->_release_lock() OR ! $this->_get_lock($session_id)))
			{
				return $this->_failure;
			}

**Comment by narfbg** [comment]
Nonsense, `$this->_session_id()` is set by read immediately after acquiring the lock, here: https://github.com/bcit-ci/CodeIgniter/blob/3.0.4/system/libraries/Session/drivers/Session_memcached_driver.php#L166

Stop looking for the difference between 3.0.3 and 3.0.4. For the Nth time - if it doesn't work in 3.0.4, it didn't work (properly) in 3.0.3 either; *you just didn't get notified with an error* about it.

Instead, please just try with a54a2b90bf057d7883ea7506d78a1073478ea4cf (on top of the previous patch) and tell me if it works.

**Comment by cmeenatchisundaram** [comment]
@narfbg 
I tried with your patch. But the same error is throwing...

**Comment by narfbg** [comment]
You've tried with both c4de3c2f93cb6d2af65b325ae2812fccad7e98b8 and a54a2b90bf057d7883ea7506d78a1073478ea4cf *at the same time* and it still doesn't work?

Is the error still triggered on line 198?

**Comment by cmeenatchisundaram** [comment]
Yes.. Both are throwing error...

Now it is failing on this condition inside the write fn in line no 190

$this->_memcached->getResultCode() === Memcached::RES_NOTSTORED

**Comment by narfbg** [comment]
Line 190 is an opening brace ... whatever you mean by that, I want to know which line returns `$this->_failure`.

**Comment by cmeenatchisundaram** [comment]
Line no 221 in a54a2b9...  and line no 222 in c4de3c2...

**Comment by narfbg** [comment]
That you're still referring to them separately makes me think you're still doing it wrong - you're supposed to apply both of them and never revert. Or directly pull the 3.0-stable branch if that's easier for you.

If you've done that and it still shows an error, can you do a `var_dump($this->_memcached->getResultCode()` immediately before the `return` and give me the result?

**Comment by omodica** [comment]
For what it's worth we've run into this issue ("Failed to write session data (user). Please verify...") in v3.0.4 vs v3.0.3 and we've tracked it down to the change in Session_driver.php where _success and _failure are set to 0 and -1 respectively.

If we set the _success to TRUE and _failure to FALSE, with no other changes applied to the v3.0.4 code base then it works properly as it did before.

I don't know the full context that relates to this comment and change:

"Necessary due to a bug in all PHP 5 versions where return values
from userspace handlers are not handled properly. PHP 7 fixes the
bug, so we need to return different values depending on the version."

But at least on the version of PHP 5 we run (PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46)) using 0 and -1 does not have the intended effect which could be because it's been patched by Ubuntu.

Hope this helps.

**Comment by narfbg** [comment]
@omodica Excuse me if this comment would appear hostile, but you're now the third person in a row making the same mistake and basically ignoring what I've been saying over and over again ...

It's not helping, you didn't track down the issue and it hasn't worked properly before.

The PHP 5 bug in question is that the otherwise expected boolean return values are basically ignored and don't work for error reporting. Here's the RFC about its fix going into PHP 7: https://wiki.php.net/rfc/session.user.return-value  
And because of this, when you eventually upgrade to PHP 7, TRUE/FALSE wouldn't "solve" the problem for you, because again - the error message being triggered is not the problem in the first place.

It doesn't matter that when you return FALSE instead of -1 you don't get an error message, the `write()` call has still failed and you still have a problem. Difference in 3.0.4 is that you actually *know* that there is a problem. What you're doing is trying to hide it and that's not a solution.

What we have to do in order to fix the issue is find out *why* FALSE/-1 is returned instead of TRUE/0.

**Comment by omodica** [comment]
Hi @narfbg, ok that's fair enough. I think part of my frustration is that Memcached-backed sessions definitely worked well enough in 3.0.3 although I do not know what the complete implications of that PHP bug were.

Moving forward, after I applied the commits you mentioned above it turns out that the getResultCode() value is 16, which is Memcached::RES_NOTFOUND. I believe that's an expected result when the key does not exist and I've added the following check:

OR ($this->_memcached->getResultCode() === Memcached::RES_NOTFOUND && $this->_memcached->set($key, $session_data, $this->_config['expiration']))

in addition to checking for the Memcached::RES_NOTSTORED result. I've tested this change and it's now working properly; at least for our use cases.

**Comment by narfbg** [comment]
@omodica Great, that's what I've been waiting for someone to verify. Thanks!

607b159dcdf6c0df118266b9111f1b67d46d3f9b

We don't need the `RES_NOTSTORED` check, it was only there because the [manual for Memcached::replace()](https://secure.php.net/memcached_replace) said this:

> the operation fails if the key does not exist on the server

and this:

> The Memcached::getResultCode() will return Memcached::RES_NOTSTORED if the key does not exist.

Apparently, we can't trust the ext/memcached manual.

@yahyaerturan @cmeenatchisundaram Can you confirm that this fixes it for you?

**Comment by yahyaerturan** [comment]
@narfbg I was on a active development process so I switched to DB driven session. However, I'll try to fork and try to confirm if this fixes it (I think I will, it makes perfectly sense). Will tell more on Tuesday. Thanks.

**Comment by cmeenatchisundaram** [comment]
@narfbg  8215e2f  commit is working fine.. no errors... happy engineering...

**Comment by narfbg** [comment]
OK, 2 out of 3 is good enough for me to consider it case closed. Thanks for the assistance to you all. :)

**Comment by niglu** [comment]
It does not work for me. And frankly, I dont understand how it can work for anyone else.

Lets take a look at lines 213-214:
```php
if (
					$this->_memcached->replace($key, $session_data, $this->_config['expiration'])
					OR ($this->_memcached->getResultCode() === Memcached::RES_NOTFOUND && $this->_memcached->set($key, $session_data, $this->_config['expiration']))
				)
```

Let's take a closer look what happens there. **We assume that session is being written for the first time and memcache has been just flushed.**

First, call to replace fails, as there is no data in memcache.

Second, `$this->_memcached->getResultCode() === Memcached::RES_NOTFOUND` evaluates to false,  because as @omodica said, getResultCode returns `Memcached::RES_NOTFOUND` as expected.

Therefore, because of characteristics of the && operator, the `$this->_memcached->set($key, $session_data, $this->_config['expiration'])` fragment never gets executed.

So, session data will never be written in the first place.

Obvious fix would be to change the whole fragment simply to `if($this->_memcached->set($key, $session_data, $this->_config['expiration']))`. However, It's been so in the past, but that check has been added.

Perhaps the intent was to use the error code for better error messages, but it's not achieving that and such a complex if-statement is now breaking things...

**Comment by niglu** [comment]
Getting confused with my own thoughts here, sorry. For me, getResultCode() returns code 14, not 16 as with @omodica. Therefore `$this->_memcached->getResultCode() === Memcached::RES_NOTFOUND` evaluates to false, and as the && must be false anyway, PHP does not bother to execute the memcached->set call.

I have no idea why we get different error codes. But is checking the error code here meaningful anyway? Anyway, fix would be the same, and it would propably work for all. (As we really dont need to know the exact reason of failure for replace.)

**Comment by narfbg** [comment]
> For me, getResultCode() returns code 14

... what is 14?

> I have no idea why we get different error codes.

Well, we'll never properly fix it until we find that out.

> But is checking the error code here meaningful anyway?

Yes.

> Anyway, fix would be the same, and it would propably work for all.

"The same" as ... ?

> (As we really dont need to know the exact reason of failure for replace.)

Yes, we really *do* need to know the failure cause. Please, don't go the same route everybody else in this thread did with trying to mask the problem - that is not an acceptable solution.

**Comment by niglu** [comment]
Quoting [PHP documentation](http://php.net/manual/en/memcached.constants.php):

>RES_NOTSTORED = 14
>Item was not stored: but not because of an error. This normally means that either the condition for an "add" or a "replace" command wasn't met, or that the item is in a delete queue.

>RES_NOTFOUND = 16
>Item with this key was not found (with "get" operation or "cas" operations).

16 should be an impossible result, as neither get or cas is called. @omodica, what's your platform?

14 makes sense: the condition for "replace" command is not being met, because no data what to replace exists.

We don't need replace(). Set() does all replace() does, and more. If for some reason we need to know if session is being generated for the first time, then it might be useful. But for now that information is not being needed in any way.

>>But is checking the error code here meaningful anyway?
>Yes.

By "here", I meant the if statement. It would make sense if we do it afterwards, just before calling fail().

> "The same" as ... ?

Same as in my first comment on this thread. Like this - and now with spaceholder for error handling:

```php
if($this->_memcached->set($key, $session_data, $this->_config['expiration']))
				{
					$this->_fingerprint = $fingerprint;
					return $this->_success;
					
				}

				$failure_reason = $this->_memcached->getResultCode();
				
				// TODO Use $failure_reason to produce better error message
				// Alternatively, $this->_memcached->getResultMessage() may be used

				return $this->_fail();
```

**Comment by narfbg** [comment]
> Set() does all replace() does, and more.

Does it? It is true that I have written all of this code "blindly" and I'm not that familiar with Memcached, but why the hell would `replace()` exist if `set()` supersedes it?

I'd comment on the rest of your feedback, but everything else depends on this point. ^

**Comment by niglu** [comment]
From [Memcached documentation](https://github.com/memcached/memcached/wiki/Commands):
>set
>
>Most common command. Store this data, possibly overwriting any existing data. New items are at the top of the LRU.
>
> replace
>
>Store this data, but only if the data already exists. Almost never used, and exists for protocol completeness (set, add, replace, etc)

So it exist mainly to make their API neat and tidy. Clearly "set" is considered a best practice by Memcached authors.

**Comment by narfbg** [comment]
Great, thanks for clearing that up - it does make the whole thing much simpler too.

**Comment by omodica** [comment]
Frankly it's been long enough that I have forgotten some of the details but I think it makes sense what you're saying with using set vs replace. @niglu per your question we've been running PHP 5.5.x on Ubuntu and since this issue was closed the Memcached sessions have definitely worked properly for us... so I'd suggest any change be properly tested (and maybe a new issue / PR created).

**Comment by erwinsetiawan** [comment]
What is the solution for this warning?
Message: Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct 

After reading all of this i didn't catch any solution to fix this warning, please help, it happens on 3.1.6. Thank You

**Comment by erwinsetiawan** [comment]
if ($this->_memcached->get($lock_key))
			{
				sleep(1);
				continue;
			}

			$method = ($this->_memcached->getResultCode() === Memcached::RES_NOTFOUND) ? 'add' : 'set';
			if ( ! $this->_memcached->$method($lock_key, time(), 300))
			{
				log_message('error', 'Session: Error while trying to obtain lock for '.$this->_key_prefix.$session_id);
				return FALSE;

I got problem, Always return FALSE on this part.

**Comment by erwinsetiawan** [comment]
Ah i got it,
 

> Message: Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct

It happens because function open is never calling on Session_memcached_driver is never execute. When it actually triggered? I tried to put "$this->open($this->_config['save_path'], '');
" on construct and its never get any error again.

@narfbg please let me know if it correct. If not when function open actually calling?
