### ISSUE TITLE
Make error_db.php view flexible

### ISSUE THREAD

**Issue by SoundlessCoder** [bcit-ci/CodeIgniter#3944]
The `application/views/errors/error_db.php` file should be as flexible as the `error_php.php` is right now.

There should be available variables to use, like `$sql`, `$line` so we can access the important data instead of displaying an error.

This will offer better flexibility as when writing large queries and an syntax error comes up on LINE X, it is difficult to see it in the message as it is not pre-wrapped. Offering the line number against `$sql` could allow me to grep the line number and perhaps highlight the specific line.

**Comment by narfbg** [comment]
There are a lot of database errors that are not triggered by an SQL query, so the existence of `$sql` can't be guaranteed. In fact, even the currently displayed line number is a guess ...

I also don't understand what you mean by "access the important data instead of displaying an error" - it's a view file, displaying is its sole purpose.

> This will offer better flexibility as when writing large queries and an syntax error comes up on LINE X, it is difficult to see it in the message as it is not pre-wrapped.

I don't understand what you mean here either.

> Offering the line number against $sql could allow me to grep the line number and perhaps highlight the specific line.

You mean against the raw SQL query, as embedded in your PHP code? Sure, it would be very cool, but it borders on the impossible ... I can't even begin to explain how much effort that would require.
