### ISSUE TITLE
Error/exception handler overriding?

### ISSUE THREAD

**Issue by jamieburchell** [bcit-ci/CodeIgniter#3982]
I'd like to be able to handle uncaught exceptions and PHP errors at a global level with the ability to email details of the error and to show the user a generic page/template.

From what I can work out, if `display_errors` is off - the user will get a blank page with no useful information and worse there is no ability to handle the error further to send an email.

Am I missing something or do I need to override the default/php exception handlers from the CI core? Is that even possible?

**Comment by narfbg** [comment]
Please post such questions on the [forums](http://forum.codeigniter.com/), we only accept bug reports here.

**Comment by jamieburchell** [comment]
I'd suggest exit(1) with no ability to show or do anything useful if display errors is off is a bug, but then I don't know what the intended functionality is here

**Comment by narfbg** [comment]
Well, I don't know about what case in particular you're talking about, but while a blank page may seem like a usability issue, leaking detailed information about an error can be way more harmful ...

**Comment by jamieburchell** [comment]
I'm not condoning leaking sensitive information to users. I'm simply saying that not being able to handle uncaught exceptions seems like an issue.

**Comment by narfbg** [comment]
I simply answered to what you said you'd suggest to be a bug ... How *you* would handle uncaught exceptions has little to do with display_errors or a blank page that may be displayed to the user. In fact, display_errors being On doesn't help you with anything in that regard.

Can you handle an uncaught exception? Yes, and there are also other ways to send an email in case of an error, but don't ask me how to do that ... I'm sure you mean no offense, but answering that one question alone makes me feel like I'm handling support tickets instead of a bug tracker.
