### ISSUE TITLE
Query Builder Not Escaping Values For Update/Insert When Disabling _protect_identifiers

### ISSUE THREAD

**Issue by zepernick** [bcit-ci/CodeIgniter#3989]
```php
public function set($key, $value = '', $escape = NULL)
	{
		$key = $this->_object_to_array($key);

		if ( ! is_array($key))
		{
			$key = array($key => $value);
		}

		is_bool($escape) OR $escape = $this->_protect_identifiers;

		foreach ($key as $k => $v)
		{
			$this->qb_set[$this->protect_identifiers($k, FALSE, $escape)] = ($escape)
				? $this->escape($v) : $v;
		}

		return $this;
	}

```

@narfbg This is the same type of problem you fixed for me yesterday.  It looks like the escape of the value is going off the protect_identifiers

I believe the line in the foreach should be 

```php
			$this->qb_set[$this->protect_identifiers($k, FALSE, $escape)] = $this->escape($v);
```

**Comment by narfbg** [comment]
Fixed in 2 more instances, shouldn't be any more of these left ... thanks for digging into it.

Still, I should repeat what I said on the forums - you should NOT ever rely on the possibility to disable `_protect_identifiers`. Also, it's no longer called "Active Record", but "Query Builder" instead.

--------------

Referencing 43afc71b777b00cfc2638add6fa3c47d333c5e04

**Comment by zepernick** [comment]
Thank you!  Warning is understood.  My bad on using the old "Active Record".  I fixed the title of the issue.

**Comment by narfbg** [comment]
Damn auto-closing ... I specifically reopened this, so I can comment on it as an *open* issue.

Anyway, the changes related to this have been reverted. I don't want to be spreading bad advice via our issue tracker, but I'll tell you this - there's another hacky way to avoid field name escaping. It's up to you to find out what it is if you really need it that bad.

**Comment by zepernick** [comment]
subselects are the real issue as to why they need to be shut off in my case.  It is surrounding them with `` and I use them quite heavily.  Disappointed that there is no supported way to shut this functionality off.  It does not make a lot of sense to me.  I would disabled it just from a performance standpoint as it seems pretty unnecessary in most cases.

**Comment by narfbg** [comment]
Well, if you ask me - the moment you start passing raw SQL to the query builder, you're just wasting your time with using QB in the first place and you gain absolutely nothing from it. Use raw queries, there's nothing wrong with them.

**Comment by aanbar** [comment]
So if I understand correctly, this does fix the issue I reported in #3592 ??

**Comment by zepernick** [comment]
It is not a waste of time at all!  It stops from having to concatenate your query and the code is less verbose. I also do not have to check if I have already included my "AND" or start off my where clause with a 1=1 to get around that.  It just feels much cleaner.  I don't have to worry about escaping my values because it is already being done.  The whole point of it is to assist with dynamic queries, but right now you are saying that if your dynamic query contains a subselect you are out of luck and go use raw sql.  Raw queries are fine if you have a fixed amount of criteria and selected columns.

What is the point of trying to escape everything?  People should be trying to stay away from reserved words in their tables and column names anyway.  Why not just have the option to turn it on when needed, it would be one less thing the query builder would have to run through?

**Comment by narfbg** [comment]
@aanbar Yes, although I still think your use case is invalid, given that you can do the same via `where()` or a raw query (you are in fact building it yourself anyway).

@zepernick 

Start with a WHERE condition of '1' and you can always append ' AND something' to it, while parametirized queries solve the escaping problem. The only real benefit in using a query builder is portability (that is, you can transfer from e.g. mssql to mysql without rewriting your queries).

I also want to clarify on the following, because I fucking hate people twisting my words ...

> but right now you are saying that if your dynamic query contains a subselect you are out of luck and go use raw sql

I'm not saying you're out of luck, I'm saying it makes no sense to shove raw SQL into a query builder, because the whole point is that the query builder generates SQL *for you*.

Your argument about what's the actual point of trying to escape everything is more logical, but it's people reporting bugs that *it didn't escape something* who are demanding it. I for one don't see a substantial benefit in either choice - it already did escaping when I joined the project.

You're free to make a feature request for a configuration option on identifier escaping of course, but do it properly in a separate issue.

**Comment by zepernick** [comment]
@narfbg really, calm down man, lol.  Yes, you did not say that.  That is what I was deriving from our conversation. Sorry for getting your knickers in a twist.

**Comment by narfbg** [comment]
I use dirty words regularly, that has nothing to do with my mood. :)

**Comment by mwhitneysdsu** [comment]
@narfbg 
> I'm not saying you're out of luck, I'm saying it makes no sense to shove raw SQL into a query builder, because the whole point is that the query builder generates SQL for you.

If you build your initial SQL with query builder, then use something like `get_compiled_select()` to get the raw SQL to use in a sub-query, it is almost impossible to pass it back into query builder without breaking something, especially if you pass the sub-query into `from()`, which has no option for disabling escaping the query. Obviously, double-escaping is part of the problem if I do things this way, but my point is simply that sub-queries don't have to start as raw SQL.

I'd really be happy if I could just call a method to disable escaping until `_reset_select()`/`_reset_write()` is called. I generally only have a problem with it for 1-2% of the queries I might run, and most of those are on pages which require a larger number of queries than usual, so the choice of disabling it through the back door through unsupported configuration or optionally on some methods (but not having the option to disable it on other methods) just doesn't work.

I ended up hacking together a version of query builder's `where()` functionality in my model to return the text for my where clause, to make it easier to build a SQL string to pass to `query()`, when I only had to build the string and use `query()` because I couldn't stop the `from()` method from breaking my sub-query.

**Comment by ivantcholakov** [comment]
@mwhitneysdsu
public function from($from) -> public function from($from, $escape = TRUE)
Is this a good deal for you?

**Comment by mwhitneysdsu** [comment]
@ivantcholakov I think that would address the issue of that particular method not having the option, which may or may not fix my specific case, but I think it's indicative of a design problem that nearly every method in Query Builder needs an extra parameter to disable escaping queries.

**Comment by narfbg** [comment]
@mwhitneysdsu It doesn't matter how it started, you're passing raw SQL to QB.

**Comment by mwhitneysdsu** [comment]
I was just pointing out that it's possible to pass raw SQL to QB without actually hand-coding the raw SQL...

> because the whole point is that the query builder generates SQL for you.

but I'll stop, because I've dragged it far enough off the original point of this issue. Thanks for working on this.
