### ISSUE TITLE
affected_rows() has ambiguous name

### ISSUE THREAD

**Issue by kevinfoley** [bcit-ci/CodeIgniter#4025]
The query helper method `$this->db->affected_rows()` has an ambiguous and potentially misleading name, in that one might expect the method to return the actual rows instead of a count. Possible alternative names would be `affected_row_count()` or `num_affected_rows()`

**Comment by Calico90** [comment]
Well, I agree on your comment. But it is consistent with the way PHP names it's functions.

http://php.net/manual/en/function.mysql-affected-rows.php

**Comment by narfbg** [comment]
There is some logic in what you're saying, but satisfying readability advocates like yourself would be the only positive effect of it, and that isn't worth the negatives.

**Comment by kevinfoley** [comment]
It's not only a matter of "satisfying readability advocates", but also making CI easier to learn and understand for future users.

**Comment by narfbg** [comment]
I have no doubt that you believe in that, but here's why I wrote my previous comment:

- Changing the name would be a huge backwards-compatibility break.
- As @Calico90 noted, the name `affected_rows()` comes from PHP itself, and in that regard has even historical value.
- Everybody knows what `affected_rows()` does, because we're not the only ones using it - if you believe the name is misleading, you'd have to change the whole internet.
- There's documentation explaining what it does. Comprehensive names are great, but by far not what we rely on.
- It is used within a context, while you're evaluating it in isolation. No reasonable person would ignore the DB_result class (and the `result*()` methods that return it), the fact that `affected_rows()` isn't a part of the DB_result class, nor the logical flaw in that `affected_rows()` isn't in any way coupled with any sort of a result set identifier. Especially since it's an OOP API, not a procedural one.
- Even if somebody does make the assumption that you're warning against, so what? An integer will be returned, they'll "waste" a minute to read the docs and that's it - end of story, no harm done. In fact, I'd kind of like the idea that somebody reads the documentation for a change.

If the API was designed now, would this method be given a better name? Perhaps.  
But it's not being designed now; it's a part of an old, mature API and in a project that puts so much effort in keeping backwards-compatiblity that it sometimes hurts itself for it.

So, given the above points, satisfying readability advocates *is* the only positive that your suggestion would do. As I said, that just isn't worth the negatives.

**Comment by kevinfoley** [comment]
I wasn't suggesting to immediately drop the current method and break all backwards compatibility. Presumably the same approach would be used as with any deprecated function in any API - create a new function with the desired name, but retain the old function for backwards compatibility for some time. CI already took this approach with orderby() -> order_by() and a few other functions. 

Although it might seem that "Everybody knows what  affected_rows() does", not everyone has prior experience with PHP or databases. Personally, I haven't made heavy use of the method, and have had to occasionally look it up again to refresh my memory on what type of data it returns.
Personally, I haven't made heavy use of the method, and have had to occasionally look it up again to refresh my memory on what type of data it returns. 

Anyway, if you're not interested in the change, there's nothing more to be done about it.
