### ISSUE TITLE
Firebird blod

### ISSUE THREAD

**Issue by turtuga** [bcit-ci/CodeIgniter#4035]
Hello 

firebird driver in codeigniter have some problem in inserting blob id's in firebird because an blob id not survive an escape() and prepared statement in codeigniter destroy blob id because it send simple query to firebird..

i think is necessary modify firebird driver to send blob's in "?" instead simple query anyone help me with this??

thanks

**Comment by narfbg** [comment]
CI doesn't have its own prepared statement abstraction yet, but it is planned for version 3.1.
This issue is a Firebird equivalent of #1602, which you may consider a feature request for prepared statements in general, so I'll close this as a duplicate.

Otherwise, please note that this is not the place to ask for assistance. If you need help with something, you should stick to the [forums](http://forum.codeigniter.com/).
