### ISSUE TITLE
SoapClient issue on CLI cron

### ISSUE THREAD

**Issue by arisdario** [bcit-ci/CodeIgniter#4053]
I have created a function that call a Magento SoapClient

In traditional PHP if i run it via command php soapcron.php
 it works

Also i put the same code in a function on CI, on web it Works, but on command via CLI cron it doesn't work and give me an error:

the traditional php is:
```
$client = new SoapClient('http://www.magento.com/api/soap/?wsdl');
$session = $client->login('ApiUser', 'ApiKey');
	try {
		$getAttributes = $client->call($session, 'catalog_product_attribute.options', 11);
	} catch (SoapFault $e) {
		echo '11';
		print($client->__getLastResponse());
	}
var_dump($getAttributes);
$client->endSession($session);
```

```
CI Method

      public function SyncAttributes(){
		
		$mag = $this->Settings_m->getMagentoSettings();
		$client = new SoapClient($mag[2]->action);
		$session = $client->login($mag[0]->action, $mag[1]->action);
		
		$attributes = $this->Magento_m->getAttributes();
		
		foreach($attributes as $attribute){
			try {
				$getAttributes = $client->call($session, 'catalog_product_attribute.options', $attribute->attribute_code);
			} catch (SoapFault $e) {
				echo $attribute->attribute_code;
				print($client->__getLastResponse());
			}
			
			foreach($getAttributes as $value){
				$dataInsert = null;
				if($value['value'] != ""){
					$dataInsert = array(
						'attribute_code' => $attribute->attribute_code,
						'attribute_value' => $value['value'],
						'attribute_label' => $value['label']
					);
				}
				if($dataInsert != null){
					$syncronize = $this->Magento_m->syncAttributes($dataInsert);
				}
			}
		}
		
		if(isset($syncronize) && $syncronize == true){
			echo json_encode(array('status' => 'success'));
		}else{
			echo json_encode(array('status' => 'nothing_new'));
		}
		
		$client->endSession($session);

	}
```

This method is called in command php /paht/to/ci/index.php Controller SyncAttributes

the error is: 

```
PHP Notice:  Constant ENVIRONMENT already defined in /path/to/ci/index.php on line 57

A PHP Error was encountered

Severity: Notice
Message:  Undefined offset: 2
Filename: /path/to/ci/application/controllers/Controller.php
Line Number: 25
Backtrace: File: /path/to/ci/application/controllers/Controller.php
Line: 25
Function: _error_handler
File: /path/to/ci/index.php
Line: 293
Function: require_once


A PHP Error was encountered

Severity: Error
Message:  SoapClient::SoapClient(): 'uri' option is required in nonWSDL mode
Filename: /path/to/ci/application/controllers/Controller.php
Line Number: 25


Line 25 is: $client = new SoapClient($mag[2]->action);
```

Is there a way to fix it?

**Comment by narfbg** [comment]
We only accept bug reports via GitHub and this doesn't seem to be one. Please post your questions on our [forums](http://forum.codeigniter.com/) instead.

**Comment by arisdario** [comment]
narfbg, all the time you say the same thing, is not a bug.... if SoapClient work outsite CI and inside CI it doesn't work, Let me know Why ? Thanks

**Comment by narfbg** [comment]
Well ... when the train rides just fine outside of a car road, is it the road's fault that the train can't go on it? It's a stupid analogy, but just because something works outside of CI, doesn't mean that it's CI's fault when it doesn't work inside it.

When I say that something isn't a bug, it's not just because I flipped a coin; there's logic behind my comments. In fact, it's not even the same code that you're using in both places and none of the error messages that you've pasted here point to CodeIgniter code - they point to *your* code.

**Comment by arisdario** [comment]
You're right, i understand your point of view, but the idea is that i need to run the method via CRON, CI has CLI CRON, on run it via CRON it fails, i mean i put the train on the road, but i know that it will not work, but putting a CLI CRON i know that it need to work without issue, so it is not working and my question is why, what is wrong...

**Comment by andersonunsonst** [comment]
$mag = $this->Settings_m->getMagentoSettings(); //is empty ?! debug you code..
 $client = new SoapClient($mag[2]->action); //not seem right, verify userguide about class
put your question in forum :)

**Comment by arisdario** [comment]
No problem, i edited the post on forum also i put manually the data to avoid the empty values. Thx

**Comment by narfbg** [comment]
CI doesn't have "CLI CRON" ... I don't know if you're referring to a third-party library or just the fact that you could start a CI process via crontab, but neither would be any concern for the framework itself. And that's just reinforcing the statement that this is not a bug in CodeIgniter and therefore has no place in a our bug tracker.

That you're looking for an answer to "why it's not working" is obvious, but here is just the wrong place to ask that question. It's a distraction in the development process and we don't have the resources to handle generic help questions anyway.
That's why we have a dedicated forum, where other people from the CI community would volunteer to help you with almost any problem that you may have. And there are also more popular sites like StackOverflow where you could also find help. Again, GitHub is just not the right place.
