### ISSUE TITLE
Table prefix added on select field when table is escaped.

### ISSUE THREAD

**Issue by txigreman** [bcit-ci/CodeIgniter#4061]
When I do something like this:

```php
ci()->db->select('`exp_table`.`field`', false)->get('`exp_table`');
```

I get this error:
```
You have an error in your SQL syntax; check the manual that
corresponds to your MySQL server version for the right syntax
to use near '.`field` FROM (exp_`exp_table`)' at line 1

SELECT exp_`exp_table`.`field` FROM (`exp_`exp_table`)
```

I've fixed it by modifying the "protect_identifiers" function from DB_driver class, reemplacing this code:
```php
elseif (strpos($parts[$i], $this->dbprefix) !== 0)
{
    $parts[$i] = $this->dbprefix.$parts[$i];
}
```

With this other:
```php
else {
    $pos = substr_compare($parts[$i], $this->_escape_char, 0, strlen($this->_escape_char)) === 0 ? strlen($this->_escape_char) : 0;
    if (substr_compare($parts[$i], $this->dbprefix, $pos, strlen($this->dbprefix)) !== 0)
    {
        $parts[$i] = substr_replace($parts[$i], $this->dbprefix, $pos, 0);
    }
}
```

Have into account that this should be done also when prefixing single items (a few lines of code below).

I hope it helps. Thanks!

**Comment by jmarquezt** [comment]
awesome

**Comment by narfbg** [comment]
Yea, I'm not sure what, if anything should be done about that ...

For you, it's an error, but for somebody else it may be the expected behavior - not this example in particular, but disable escaping does mean disable anything related to escaping, including detection.

**Comment by txigreman** [comment]
Can you provide an example where this odd behaviour is the expected one?

I'm not talking about of disabling table prefixing when escape flag is set to false, what I mean is that the table prefixing is not working properly when the table is escaped. If I put the table without the prefix it neither works!

In my opinion this behaviour is never the expected one.

**Comment by narfbg** [comment]
When you don't feed it an already escaped and prefixed table/field name?

**Comment by txigreman** [comment]
But with my code that is still working! It only fixes the table prefixing process when the provided table is escaped...

**Comment by narfbg** [comment]
I'm not saying your patch breaks it ... I'm saying it deals with escaping-related logic when that should be disabled.

Surely you could follow-up with more "but"s, but that's not the point - there's potential for a lot more edge cases related to this functionality and if we take one-at-a-time patches for all of them we'd end up with an ugly pile of work-arounds.

The disable escaping feature was introduced to allow DB-level functions and similar (but simple) stuff that is otherwise broken by auto-escaping; we knew it would never be perfect.  
The table prefix on the other hand is a horrible feature IMO. If it wasn't for BC concerns, I'd remove it right now.
So the way I see it, it's probably not worth touching at all.

I could be wrong of course, so I'm leaving the issue open for discussion for now, but it would take a lot to convince me.

**Comment by txigreman** [comment]
A workaround is what I have to do in order of make it work, that is just a bug fix.

I understand that you don't like the table prefix feature, but it is a CI built-in feature that, in some cases, it's not working properly. I think you should fix it or mark it as deprecated.

**Comment by blasto333** [comment]
The table prefix feature should NOT be deprecated. This is important for people that want to share the same database along with other tables. I understand that it can cause issues but depreciated it because it breaks in certain cases is really not a valid reason

**Comment by narfbg** [comment]
Not in "certain cases", but in *many* cases. The feature is simply fragile by design ... you've experienced that yourself.

It may be deprecated, or not, we'll see ... but it's a legacy feature that should be avoided regardless.

**Comment by blasto333** [comment]
Please do not deprecate that would really cause issues with my application

--
Chris Muench
Sent from my iPhone

On Sep 3, 2015, at 4:58 AM, Andrey Andreev <notifications@github.com> wrote:

Not in "certain cases", but in *many* cases. The feature is simply fragile
by design ... you've experienced that yourself.

It may be deprecated, or not, we'll see ... but it's a legacy feature that
should be avoided regardless.

—
Reply to this email directly or view it on GitHub
<https://github.com/bcit-ci/CodeIgniter/issues/4061#issuecomment-137383338>.

**Comment by narfbg** [comment]
"Please don't" comments really make me "do" instead ... you're not helping yourself that way.

**Comment by blasto333** [comment]
I was just expressing my opinion on the issue. I am sorry if I offended you.

**Comment by adam-bell** [comment]
I agree that this is working as expected.

For that use case, if it is infrequent (as suggested in your original post)

Remove the prefix before the query:
`$tmp_prefix  = $this->db->dbprefix;`
`$this->db->set_prefix('');`
`// unusual query runs here`
`$this->db->set_prefix($tmp_prefix);`

if you do this fairly often in your application, then maybe a prefix shouldn't be set in the db config and should be part of the application logic.

otherwise create your own helper function/library to wrap select, maybe called `select_noprefix` ?

**Comment by txigreman** [comment]
Well, thankfully expression engine is not using this mediocre framework anymore, so from now on I don't have to struggle with stuff like this... I'm not going to miss you, CI.

**Comment by narfbg** [comment]
Good for you.

**Comment by bhavhirani** [comment]
In my case it give me error `Call to undefined method CI_DB_mysqli_driver::set_prefix()`.
Then after I did the following, and it's working.

`$tmp_prefix = $this->db->dbprefix;`
`$this->db->dbprefix = '';`
`// unusual query runs here`
`$this->db->dbprefix = $tmp_prefix;`
