### ISSUE TITLE
index.php should be in it's own public folder 

### ISSUE THREAD

**Issue by 9livesdevelopment** [bcit-ci/CodeIgniter#4094]
I recommend moving the index.php file to a public or www folder so the rest of the folder structure can't be accessed from the Internet. Relying on .htaccess files is not the safest solution.

Obviously users can do this themselves, but it would be much better if this was the default.

**Comment by sho88** [comment]
I concur.

**Comment by narfbg** [comment]
Duplicate of #1399.

**Comment by 9livesdevelopment** [comment]
How about providing it at least and mentioning in the instructions that if you can't use the public folder you can use the alternative index.php in the root folder?

**Comment by narfbg** [comment]
That's the same thing said with different words ... instructions aren't the problem, CI working out of the box is.

**Comment by 9livesdevelopment** [comment]
I've read the arguments for and against and it's clear. Apparently it won't be changed, but I strongly disagree with the argumentation as security should not suffer because of webserver limitations. Find a decent hosting provider or have a pro host it for you. 

We should always strive to implement best practices and educate people who are unaware.

**Comment by narfbg** [comment]
Strive, not follow them for the sake of it. :) Being reasonable is the best "best practice" there is and we have to know our crowd.

Hosting environment limitations are the main problem, but not the only one. Most of our users are newbies and they pick CodeIgniter because it is the easiest one to use and requires almost zero configuration. And I can say this from experience - telling them to pick a better provider or hire a professional will be met mostly with ignorance.

Naturally, if this was a critical security issue that would take precedence, but it's not - having only index.php in the document root liberates you from many further security *considerations*, but the opposite is not a vulnerability, leaking the info that you're using CI is the only penalty.

**Comment by jim-parry** [comment]
This is an issue best dealt with in the user guide, i.e. describing several "best" ways to configure an app.

**Comment by Vwe** [comment]
why not just change the path to the application and system folders in index.php moving them out of the root www folder leaving only the index.php and other various assets like css, js, images, ect ... in the www folder. simple, easy, and no htaccess entries.

**Comment by jim-parry** [comment]
There is no single best way, @Vwe 
This will be dealt with in the user guide or on the forum.
