### ISSUE TITLE
Documentation for base_url and site_url should mention that protocol relative URLs are handled through base_url config option

### ISSUE THREAD

**Issue by ZhangYiJiang** [bcit-ci/CodeIgniter#4098]
I believe it would be useful to mention this fact (as brought up by issue #1972 and #165) so that those looking to set the protocol with the second parameter of these two functions would not end up confused when that doesn't work

**Comment by narfbg** [comment]
I'm qurious ... how exactly would you try to set a protocol to relative using the second parameter of either function?

Protocol-relative means you don't specify a protocol, which means passing an empty value I guess? If you pass NULL, that's no different to passing nothing; if you pass `''` (empty string) then it would actually work. So what's the issue here?

**Comment by ZhangYiJiang** [comment]
That's the issue - the documentation made it sound like what you described there would work, but looking at the actual code for the function involved 

	public function base_url($uri = '', $protocol = NULL)
	{
		$base_url = $this->slash_item('base_url');

		if (isset($protocol))
		{
			$base_url = $protocol.substr($base_url, strpos($base_url, '://'));
		}

		return $base_url.ltrim($this->_uri_string($uri), '/');
	}

passing in a blank protocol would result in incorrectly formed URL 

    php > $base_url = 'http://example.com'; 
    php > var_dump(substr($base_url, strpos($base_url, '://')));
    string(14) "://example.com"

**Comment by narfbg** [comment]
I see ... now it works.
