### ISSUE TITLE
query builder select with alias

### ISSUE THREAD

**Issue by huehnerhose** [bcit-ci/CodeIgniter#4134]
Hi,

I am upgrading from CI2 to CI3 and encountered a problem with my old database-queries. There are several occasions where I build queries using active record / query builder with select-statements containing aliases (SQL: AS). They can be devided in two types:
Type 1: `"table"."column" AS "alias"`
And Type 2: `"table"."column" AS "prefix.alias"`

Type 1 works, type 2 gets escaped the wrong way. query builder generates `"table"."column" AS "prefix"."alias"`, it adds two " around the .

I didn't find anything about aliases in the query builder documentation, except for select_avg, etc. 
I really think this is a bug. I am not certain if my usage was "wrong" in the first place, but I need these prefixed aliases anyway ;)

Example Code

``` php
$a = $data = $this->db->select('table."column" as "prefix.alias"')->get("table");
var_dump($a);
```

outputs

``` sql
SELECT "table"."column" as "prefix"."alias" FROM "table"
```

**Comment by andersonunsonst** [comment]
try 3.0.2
look here: https://github.com/bcit-ci/CodeIgniter/issues/4096

**Comment by huehnerhose** [comment]
I uses the current 3.0-stable branch. Error still exists.

**Comment by narfbg** [comment]
I can't classify this as a bug, because using the dot character inside `select()` has always meant identifier separation - there are just *some* limitations that we have to live with. It may've worked for you in the past, but that's rather accidental.

Still, after looking at the relevant code, there is something that could be done about this, but it would require at a new parameter for `escape_identifiers()` for this particular case and a small change in behavior (but a BC break nonetheless) in order to avoid similar complaints about other usages. Therefore, it can't happen in 3.0.x and will have to wait for 3.1.0.

**Comment by pakistanimoon** [comment]
Version 3.1.0 is there, I will suggest you to check it for this issue.
