### ISSUE TITLE
Validating multidimensional arrays

### ISSUE THREAD

**Issue by adnnor** [bcit-ci/CodeIgniter#4181]
I have two fields, named `title[1]` and `title[2]`.

>*Indexes are used to mention the language id*.

    $this->form_validation->set_rules("title[]", "Menu title", "required");

Only validates the first index but not second or others using CodeIgniter 2.2.1. I want to know is there any fix so CI its self check for all the indexes and apply the same rule. Just like `set_value["title[]"]` reloads the value for each field automatically.

**Comment by narfbg** [comment]
Please ask your questions on the [forums](https://forum.codeigniter.com/) instead, we only accept bug reports here.

**Comment by adnnor** [comment]
Dear @nerfbg

Is this not a bug that `title[]` indexes are not validating just like `set_value["title[]"]` reloads all the value automatically without mentioning indexes?

**Comment by narfbg** [comment]
Even if it is a bug, there are a few problems with you opening this issue here ...

- Before reporting any bug, you must make sure that it hasn't already been fixed and step 1 is updating to the latest version. CI 2.2.1 is *very* old.
- CI2 is in security maintenance mode and we no longer accept bug reports for it.
- You didn't present it as a bug report; you just asked how to fix it for yourself.
