### ISSUE TITLE
Database backed sessions with session rotation with many requests causes session to lose data

### ISSUE THREAD

**Issue by blasto333** [bcit-ci/CodeIgniter#4195]
Steps to reproduce:

1. Add data to session such as person_id = 1 with the settings below for config.php
2. Refresh page repeatedly by holding down cmd + R (or ctrl + R) on windows 
3. Notice that you are logged out  due to some sort of race condition as person_id = 1 is NOT available in session anymore.

It is my understanding that this should not happen due to session locking; but it does appear to come up against a race condition because during session rotation their could be 2 different locks and it allows for non blocking actions.. my reason for making the `sess_time_to_update` so small is so I can easily reproduce issue. This doesn't seem to happen when sess_regenerate_destroy is FALSE: but in theory it could still happen in php garbage collection takes over; although probably very rare.

config.php settings

	$config['sess_driver'] = 'database';
	$config['sess_cookie_name'] = 'phppos';
	$config['sess_expiration'] = 0;
	$config['sess_save_path'] = 'sessions';
	$config['sess_match_ip'] = FALSE;
	$config['sess_time_to_update'] = 1;
	$config['sess_regenerate_destroy'] = TRUE;

mysql_general_log:

https://www.dropbox.com/s/ybsa5eo1bmmv44l/sessions_general_log.txt?dl=0

**Comment by narfbg** [comment]
There's no bug here ...

This is where you lose the data (`GET_LOCK()`, `RELEASE_LOCK()` queries obviously stripped):

<pre>
		   40 Query	SELECT `data` FROM `phppos_sessions`WHERE `id` = '61859a28c2d08b95db0be41e97f37f974e2b2fc4'
		   40 Query	DELETE FROM `phppos_sessions` WHERE `id` = '61859a28c2d08b95db0be41e97f37f974e2b2fc4'
		   41 Query	SELECT `data` FROM `phppos_sessions` WHERE `id` = '61859a28c2d08b95db0be41e97f37f974e2b2fc4'

		   --- irrelevant queries ---

		   41 Query	INSERT INTO `phppos_sessions` (`id`, `ip_address`, `timestamp`, `data`) VALUES ('61859a28c2d08b95db0be41e97f37f974e2b2fc4', '72.225.8.28', 1445995775, '__ci_last_regenerate|i:1445995775;')

		   --- irrelevant queries ---

		   40 Query	INSERT INTO `phppos_sessions` (`id`, `ip_address`, `timestamp`, `data`) VALUES ('3b6824196f25dbd4e1ad7173858598fa882a2297', '72.225.8.28', 1445995775, '__ci_last_regenerate|i:1445995775;person_id|s:1:\"1\";')

		   --- queries from connections 40, 42-51 ---

</pre>

You're simply running *simultaneous* requests using the same session, either because of AJAX usage or because you're reloading the page while it is still executing.

The request that got control/lock for that session first (connection 40) regenerates the session - deletes the old one at the start of the request, creates a new one at the end of the request. Then another request (connection 40) plugs in as soon as the lock is released (after the DELETE) and tries to read the data *for the same session that just got deleted*, resulting in it having no data in the session.
If those were non-simultaneous requests, the second one (with connection id 41) would've had the new session ID and so would've read the newly-created session, but because they are simultaneous, there was never a chance for that to happen.

This race condition is unavoidable, that's exactly why 'sess_regenerate_destroy' is configurable instead of forced to TRUE.
