### ISSUE TITLE
Redis + PHP7 session_regenerate_id()

### ISSUE THREAD

**Issue by exbit** [bcit-ci/CodeIgniter#4230]
CodeIgniter develop last

A PHP Error was encountered
Severity: 4096
Message: session_regenerate_id(): Failed to create session ID: user (path: tcp://127.0.0.1:6379)
Filename: Session/Session.php
Line Number: 625

**Comment by andersonunsonst** [comment]
https://bugs.php.net/bug.php?id=70871

**Comment by exbit** [comment]
Thank you

**Comment by narfbg** [comment]
Are you manually calling `session_regenerate_id()`?

**Comment by exbit** [comment]
no

**Comment by narfbg** [comment]
I hope that it's not a simple connection issue (i.e. something prevents CI from connecting to Redis), because I've left a comment on the PHP bug linked above.

**Comment by narfbg** [comment]
If you've followed the comments on bugs.php.net, you'd know that this error is triggered by one of the following:

> - new session ID creation is failed. (Very unlikely)
> - opening save handler is failed.
> - session ID collision is detected and failed. (Very unlikely)
> - session read with new session ID is failed.

Neither is a CI bug, so I'm closing this issue here.

https://github.com/php/php-src/commit/a03786f7730e99e86113b826087e2271a2b001fc makes the failure causes more obvious, so that should help ... I don't see it mentioned in the PHP7RC5 changelog, but it is commited 2 days earlier, so it should be in there.
