### ISSUE TITLE
Enhance language files

### ISSUE THREAD

**Issue by dreamerworks** [bcit-ci/CodeIgniter#4232]
I propose a change to languages files format.
From:
```php
$lang['some_key1'] = 'Some description 1';
$lang['some_key2'] = 'Another text description';
```
To:
```php
$lang = [

  'some_key1' => 'Some description 1',
  'some_key2' => 'Another text description',

];
```
Benefits:
 - To facilitate importing translations, copy/pasting or direct translation by non-programmers
 - Makes it more clear to read
 - Slightly smaller file size

**Comment by narfbg** [comment]
The only language files shipped with CI are located under the system/ directory, which you're not supposed to ever modify. Thus, none of the benefits that you've listed apply.

**Comment by dreamerworks** [comment]
You stand correct, as usual. This would then be an advice for people providing libraries... maybe on a CI documentation page of good practices on developing libraries for CI. 
Another place where this could be, and I am sorry for posting on the wrong repository, would be on CI translations repository:
If we read , https://github.com/bcit-ci/codeigniter3-translations, it states the said files should be placed inside application/languages. Although they should also be just for reading from, we might want to hand them over to a translation team for them to approve the chosen translations and to propose better alternatives for a given app. In such case, this would be beneficial.

Thank you, I just wanted to share this possible improvement, and get some feedback on reasoning for doing it one way or the other. I think we can keep this topic closed.

**Comment by jim-parry** [comment]
@dreamerworks Each translation has a moderator, responsible for the initial translation and for reviewing proposed changes to their translation. I chose this approach, as a team would not work for all languages at once, and it feels like overkill for each language on its own. So far, the mechanism has worked well. 
Interested moderators still need to "apply", and convince me that their language experience or knowledge are up to the moderation task.

JSON notation for the settings has some advantages, but so does the array notation ... specifically being to load the settings files in the right order and trust that over-ridden settings are properly merged.

**Comment by mwhitneysdsu** [comment]
@jim-parry his recommendation doesn't appear to be using JSON notation, but rather a single array definition (rather than re-specifying the array on each line) and using short array syntax. The short array syntax requires PHP 5.4, though.

Even omitting the short array syntax due to supporting PHP 5.2.4+, a single array definition has its advantages in terms of the number of characters required in the files. Using his example:

```
$lang = array(
    'some_key1' => 'Some description 1',
    'some_key2' => 'Another text description',
);
```

I think clarity in reading any of the given formats is primarily in the eye of the beholder, and the level of explanation required by non-programmers for any of the formats is often best prevented by simply exporting the array to a spreadsheet or some other form for translation.

For better or worse, most of the config files which don't require a great deal of explanation for the entries (or don't contain a lot of entries) use the format I've included above.

**Comment by jim-parry** [comment]
You are correct - I mis-identified the format.
My intent was to show that $x['a'] = 'asdasd' was *adding* to or replacing entries in $x, whereas the proposed $x = [...] was replacing $x, which is not always desirable.

Many of the config files do use short array notation, agreed. Some (database) even have a combination of styles. My concerns would probably be best addressed by a clearer explanation in the user guide, possibly the Config class page, but probably a separate page in the general topics section, which addresses application configuration in the broader sense.

**Comment by mwhitneysdsu** [comment]
Understood regarding adding/replacing entries vs. redefining $x (or $lang, in this case). Given the way the files are loaded, that distinction is probably more important in the /application/lang/ files than in the /system/lang/ files.

By short array syntax, I meant `$x = [ ... ];` as opposed to `$x = array( ... );`. As far as I know, none of the code in CI uses short array syntax, because it was added in PHP 5.4 and CI still supports earlier versions.

Despite the difference in terms, I understand what you're saying. It would appear that `$this->config->load()` already compensates for this by merging the `$config` arrays into `$this->config` as each file is loaded, so this may only be an issue (if at all) with `$this->lang->load()`.

**Comment by dreamerworks** [comment]
Yes, the issue was, short syntax vs long syntax.

5.4 compatibility should not be an issue:
- As of PHP 5.4 you can also use the short array syntax, which replaces array() with [].
http://php.net/manual/en/language.types.array.php
- PHP version 5.4 or newer is recommended.
http://www.codeigniter.com/user_guide/general/requirements.html

A simple find/replace just on system/language/english showed a small improvement of 2Kb in file size. Changing in all system languages it would improve the size, but not significantly.

The downside would be that it breaks compatibility with php < 5.4. 
I cannot find documentation for the following scenario, but it seems to be working correctly, as it is assuming the last definition:
```php
$lang = [

  'some_key1' => 'this value is 1', 
  'some_key2' => 'that value is 2',
  'some_key3' => 'bla value is 3', 
  'some_key1' => 'this line has a new translation', 

];
```

**Comment by jim-parry** [comment]
@dreamerworks PHP 5.4 or 5.5 may be recommended, per the user guide or the repo readme, but the minimum version is still 5.2.4, so this suggestion will have to wait for a future version :-/

**Comment by dreamerworks** [comment]
Very good. 
I have no problem as this suggestion would be just a minor improvement, it has no urgency at all. 

On the projects I develop, that I know will run on PHP with a [currently supported version |http://php.net/supported-versions.php], I will use the short syntax for client string translation and, as @narfbg mentioned, I have no need to touch the system folder of CI.

**Comment by ivantcholakov** [comment]
For generated language files from an administration panel the current syntax is easier. I would prefer the current syntax not to be changed.
