### ISSUE TITLE
Use new ANSI row limiting syntax in Oracle driver

### ISSUE THREAD

**Issue by cjbj** [bcit-ci/CodeIgniter#4279]
From Oracle DB 12, the ANSI row limiting syntax is supported: http://docs.oracle.com/database/121/SQLRF/statements_10002.htm#BABEAACC

The clause in https://github.com/bcit-ci/CodeIgniter/blob/master/system/database/drivers/oci8/oci8_driver.php#L651 could conditionally use this syntax when connected to Oracle 12. It makes the results cleaner since no dummy column would be returned.

More importantly, the offset and limit in either variant of the query should be bound to avoid poor performance from parsing otherwise unique SQL statements.

**Comment by narfbg** [comment]
With this being the first version-dependent thing in the oci8 driver, I stumbled upon an issue that needs to be fixed first - the `version()` method.

It proxies the call to `oci_server_version()` and according to the [php.net docs](https://secure.php.net/oci_server_version), that returns a string containing a lot more than a version number, so it may need additional parsing.

**Comment by narfbg** [comment]
As a side note, the pdo/oci driver will need to have the same thing.

**Comment by cjbj** [comment]
Regardless of old or new syntax, the important thing is to use bind variables.  Otherwise the DB will have to reparse the statement for each 'page'

**Comment by narfbg** [comment]
I don't understand what you mean by that.

**Comment by cjbj** [comment]
@narfbg For a bind example, see https://github.com/zendframework/zend-db/blob/b2c236920b1bb53d86a975fb4fa8c0b77d47d185/src/Sql/Platform/Oracle/SelectDecorator.php#L111  The rownum & offset are bind variables and are not PHP variables concatenated into the string.
For binding see http://php.net/manual/en/function.oci-bind-by-name.php or ping me.

**Comment by narfbg** [comment]
I know what binding variables to SQL means; what I don't understand is how is that relevant to this issue?

**Comment by v55555** [comment]
you is 牛B。

**Comment by cjbj** [comment]
@narfbg it's relevant that if the new syntax is added, it should be implemented to use bind variables.

**Comment by narfbg** [comment]
I'm not sure if that's even possible with the current architecture of the DB class. And correct me if I'm wrong, but when the statements for 2 "pages" are executed in 2 different HTTP requests, the database would still have to re-parse the SQL, so ...

**Comment by narfbg** [comment]
Does that work? Am I correct in assuming that `ORDER BY` is mandatory?

**Comment by cjbj** [comment]
@narfbg Looks OK from code inspection - though I don't know what `limit_used` is for, so I can't comment whether you want to set it or not in the 12.1 branch.

If you used binds, the repeated 'hard' parsing on successive HTTP requests would be reduced, and various data structures and data buffers could be reused. Keep it in mind when you re-architecture since NOT binding is really detrimental to performance and scalability.

There are also ways so that paging would be relative to the data set available at time of first page, so that  data inserted by other users wouldn't affect ordering.  I wouldn't go there for such a general purpose framework.

**Comment by narfbg** [comment]
`$limit_used` is irrelevant to the 12.1 case.

I'm aware of the performance benefits of using binds for repetitive queries, although I still don't understand how that could work between separate HTTP requests - that's execution on separate processes, meaning that the second (and third, Nth) process doesn't have the statement ID and needs to call `oci_parse()` anew in order to bind.
Even if that is somehow possible and `oci_parse()` detects that it is re-parsing the same query (I highly doubt that), it should depend on this happening on the same connection, so you'd have to use a persistent connection, which is often problematic and not the default on CI.

Either way, I do plan on transforming all queries to prepared statements and really bind variables in the future.

Thanks for your cooperation so far. :)
