### ISSUE TITLE
Form validation skipped for empty checkboxes using callable

### ISSUE THREAD

**Issue by WouterFlorijn** [bcit-ci/CodeIgniter#4284]
I explained the complete problem and solution here: http://stackoverflow.com/a/34068582/2622860

You can simply copy-paste my code into the Form_validation library to fix the issue.

Thanks

**Comment by narfbg** [comment]
... or you can update your CI installation. Issue #3904 was fixed in version 3.0.1.

Also, please submit a proper bug report next time, linking to a StackOverflow question isn't that.

**Comment by WouterFlorijn** [comment]
Fair enough. However I explained everything in the answer I linked so I didn't see the point in copying and formatting everything again.

**Comment by narfbg** [comment]
I understand your point, but whether you've explained it in there doesn't matter because if the SO thread gets deleted or changes its URL, all the content is gone.

And to be honest, the way you explained it took me 10 minutes to understand what you're talking about. There's just a big difference in how one posts a question or answer on StackOverflow and how a bug is reported.
