### ISSUE TITLE
DB_driver write type query detection

### ISSUE THREAD

**Issue by bdamian** [bcit-ci/CodeIgniter#4337]
Some SQL dialects allows returning objects. [Postgresql insert](http://www.postgresql.org/docs/9.1/static/sql-insert.html) gives _RETURNING_ keyword. There is check in `query` (`DB_driver.php`) function if query is "write type" by `is_write_type` call. If query is write type, response data are ignored. Function `is_write_type` is taken from specified database driver.

**Comment by narfbg** [comment]
Are you reporting this based on just browsing through the *system/database/DB_driver.php* code? Our PostgreSQL drivers in particular override that method.

**Comment by bdamian** [comment]
I know that driver overloads this method. It checks if the query is "write type" (btw. the regex in postgresql  driver is too complicated, check for `returning` word here is unnecessary).
The `query` code assumes that it may be only write or read type. And this causes problem. Such sql is both read and write and the code:
```
elseif ( ! is_bool($return_object))
{
	$return_object = ! $this->is_write_type($sql);
}
```
doesn't work properly. There is assumption __query is write type ⇔ query is not read type__.
I think there should be similar call – `is_read_type`. We have 3 cases and we can't use bool to handle it.

**Comment by narfbg** [comment]
You say it causes a problem and that it doesn't work properly, but you're not saying what that problem is ...

With that condition, `query()` only cares whether to return a result object or not and since there's a huge amount of "read type" queries, it takes a black-list approach instead. The method name may be a misnomer to an extent, but it works.

**Comment by bdamian** [comment]
Please read the sentence

> The `query` code assumes that it may be only write or read type.

carefully. The problem is in the code I pasted. It should be like this:
```
elseif ( ! is_bool($return_object))
{
-    $return_object = ! $this->is_write_type($sql);
+    $return_object = $this->is_read_type($sql);
}
```
There should be check if `$sql` contains read query, not if is not write query.

If you want to check if the problem occurs test code:
```
$q = 'insert into table1 values (1, 2, 3, 4) returning *;'
$res = $this->db->query($q);
$data = $res->result();
```
using postgres.
Query written above returns data `1 | 2 | 3 | 4`, but in second line you get an error, because `$res` is boolean, not an object. It is caused wrong read type query detection, I mentioned above.
__query is write type ⇔ query is not read type__ sums up problem briefly.

**Comment by narfbg** [comment]
I find it a bit insulting that you're trying to convince me with bold text that "write type" doesn't mean "not read type" ... I do understand what you're staying.

If the test code you're giving doesn't work, that means the regular expression you said is too complicated doesn't work. The "returning" part in it in there isn't unnecessary - it exists *precisely* to work around this issue.
Perhaps it's not ideal, and that is why I said the method name may be a misnomer in that context, but an `is_read_type()` method wouldn't be any better simply because we can't possibly catch all SQL commands that returns data - too many dialects with too many custom additions; bug reports about "FOO BAR" not returning a result set would be countless.
