### ISSUE TITLE
Pagination error when using config file and attributes

### ISSUE THREAD

**Issue by juniorweb** [bcit-ci/CodeIgniter#4454]
Hello guys,

Firstly, I'll describe the scenario.

I created a config file named pagination.php inside the config folder. 

Then I wrote on it:
`$config['attributes'] = array('class' => 'item');
`

On my controller I put the specific code for the page:
`$config['per_page'] = 10;
`

What follows is that Codeigniter doesn't place the class=item. I looked for the cause of the problem on the file system/libraries/pagination.php and I think I found it.

I saw that there are two calls to the method initialize that calls  _parse_attributes. Every time  _parse_attributes is called the value of the variable _attributes is set to empty. 

So, on the first call of the method the variable $this->_attributes will have the value class=item.
But on the second call, $this->_attributes will be set to empty.

The method create_links make use of  $this->_attributes to set the attributes, but it will be empty.

The expected result is
`<a href="" class="item">1</a>`

But I got
`<a href="">1</a>`

Apparent solution:
I removed the line 670 of the file system/libraries/pagination.php and it worked perfectly. The line I referer is this one (in the method _parse_attributes):
`$this->_attributes = '';`

The following line is not affected because PHP will know it's a string. 
`$this->_attributes .= ' '.$key.'="'.$value.'"';
`

Thanks guys.

**Comment by narfbg** [comment]
> I saw that there are two calls to the method initialize that calls _parse_attributes. Every time _parse_attributes is called the value of the variable _attributes is set to empty.

No, there is only one call to `initialize()` [here](https://github.com/bcit-ci/CodeIgniter/blob/3.0.4/system/libraries/Pagination.php#L342) and again only one to `_parse_attributes()`, [here](https://github.com/bcit-ci/CodeIgniter/blob/3.0.4/system/libraries/Pagination.php#L359).

**Comment by juniorweb** [comment]
@narfbg  Yes, there is one call on the code. But the constructor is called twice. One for the config file and other for the config on the controller. You can simulate with my code and you will see it.

**Comment by narfbg** [comment]
I don't have your code.

**Comment by juniorweb** [comment]
@narfbg Sorry, it's not the constructor that it's called twice. It's really the initialize() method. 
var_dump($params); on dump on the beginning shows:

```
array (size=16)
  'full_tag_open' => string '<nav class="ui pagination menu">' (length=32)
  'full_tag_close' => string '</nav>' (length=6)
  'first_link' => boolean false
  'last_link' => boolean false
  'next_link' => string '<i class="right arrow icon"></i>' (length=32)
  'next_tag_open' => string '<span class="icon item">' (length=24)
  'next_tag_close' => string '</span>' (length=7)
  'prev_link' => string '<i class="left arrow icon"></i>' (length=31)
  'prev_tag_open' => string '<span class="icon item">' (length=24)
  'prev_tag_close' => string '</span>' (length=7)
  'cur_tag_open' => string '<span class="active item">' (length=26)
  'cur_tag_close' => string '</span>' (length=7)
  'attributes' => 
    array (size=1)
      'class' => string 'item' (length=4)
  'use_page_numbers' => boolean true
  'page_query_string' => boolean true
  'first_url' => string '?per_page=1' (length=11)
array (size=3)
  'base_url' => string 'http://localhost/amp/pesquisa/professor/ana' (length=43)
  'total_rows' => int 67
  'per_page' => int 10
```

So, I really think it's called twice.

**Comment by juniorweb** [comment]
@narfbg I found it. I'm the one making the second call to the initialize so that I set the rest of the configuration on the controller. You may try it:

config/pagination.php
```
            $config['next_link'] = '<i class="right arrow icon"></i>';
            $config['next_tag_open'] = '<span class="icon item">';
            $config['next_tag_close'] = '</span>';
```

controllers/test.php
```
            $config['base_url'] = base_url("/pesquisa/professor/{$q}");
            $config['total_rows'] = $data['total'];
            $config['per_page'] = 10;
            $this->pagination->initialize($config);
            $data['paginas'] = $this->pagination->create_links();
```

I tried to not use the initialize on the controller, but it doesn't add the rest of the configuration specific to the controller. Maybe the attribution $this->_attributes = '' would be better placed in the constructor or initialize method.

**Comment by narfbg** [comment]
`initialize()` is supposed to reset the configuration to default values, that's the expected behavior.

**Comment by juniorweb** [comment]
@narfbg so, you are basically saying that I can either have one config file in the config folder or the config in the controller but not both at the same time. I think that's not good because I only put in the config folder what is common to every controller and I put the specific config in the controller. But following your idea, now I would have to delete my pagination.php config file and repeat all the common code in every controller.

**Comment by sparky672** [comment]
> @narfbg so, you are basically saying that I can either have one config file in the config folder or the config in the controller but not both at the same time. I think that's not good because I only put in the config folder what is common to every controller and I put the specific config in the controller. But following your idea, now I would have to delete my pagination.php config file and repeat all the common code in every controller.

This used to work in 3.0.0.  I'm seeing the same behavior after upgrading to 3.1.0

Very disappointing as it seems to totally ignore the DRY method.

ALL pagination within the project needs to share certain config options, but every Controller function will also need a few unique settings... how to do this now?

**Comment by narfbg** [comment]
@sparky672 Your rant doesn't make any sense ...

- This is an issue from 2012, *way* before the 3.0.0 release.
- The `initialize()` method has *never* loaded the config on its own. The config has always been passed by `CI_Loader` when you load the library.
- This behavior hasn't changed since the 3.0.0 release.

**Comment by sparky672** [comment]
I can only explain my observations.  Yesterday I took a working project running 3.0.0 and upgraded it to 3.1.0 by replacing only the `system` files.  I changed NOTHING within my Controllers or `application` files.

Here are my simple observations:

3.0.0 - all pagination instances are using my `application/config/pagination.php` configuration file.

3.1.0 - all pagination instances are IGNORING my `application/config/pagination.php` configuration file.

-----

As far as my rant:   You're going to have both common configuration settings for all pagination instances in your project _along with_ settings that are unique to each instance.  If having unique settings for multiple instances precludes being able to use `pagination.php`, then its own purpose is already defeated.  In order to use `pagination.php`, every instance of pagination would need identical URL structure, which makes it impossible to use on more than one Controller function.

I'm simply wondering how somebody would ever be able to use this `pagination.php` configuration file to their advantage.

**Comment by narfbg** [comment]
> Yesterday I took a working project running 3.0.0 and upgraded it to 3.1.0 by replacing only the system files.

My guess is that you *think* you took a 3.0.0 project, but it is not in fact 3.0.0. It may be an old 3.0.0-dev version, or some monkey-patched 2.x version ... who knows.

> Here are my simple observations:
>
> v3.0.0 - all pagination instances are using my application/config/pagination.php configuration file.
>
> v3.1.0 - all pagination instances are IGNORING my application/config/pagination.php configuration file.

No `CI_Pagination` instances are even aware of your config file. As I said - it's the Loader that reads and then passes the configuration to it. In other words, you're looking in the wrong place.

> As far as my rant: You're going to have both common configuration settings for all pagination instances in your project along with settings that are unique to each instance. If having unique settings for multiple instances precludes being able to use pagination.php, then its own purpose is already defeated. In order to use pagination.php, every instance of pagination would need identical URL structure, which makes it impossible to use on more than one Controller function.
>
> I'm simply wondering how somebody would ever be able to use this pagination.php configuration file to their advantage.

If you looked at the code and/or the description of this issue, you'd know that only the 'attributes' configuration is reset. Everything else is kept until overriden with a different value.
This is why I said you're not making any sense.

**Comment by sparky672** [comment]
> My guess is that you think you took a 3.0.0 project, but it is not in fact 3.0.0. It may be an old 3.0.0-dev version, or some monkey-patched 2.x version ... who knows.

Your guess is wrong.  [It was version 3.0.0](http://forum.codeigniter.com/thread-1657-post-7480.html#pid7480) (files dated March 30, 2015, 9:57 AM) that I downloaded and installed myself on April 5, 2015.

    	define('CI_VERSION', '3.0.0');  // line 58 from system/core/CodeIgniter.php 

> In other words, you're looking in the wrong place.

Well, that may be true, since I'm only looking for an explanation here.

>  This is why I said you're not making any sense.

[The docs](http://www.codeigniter.com/user_guide/libraries/pagination.html#setting-preferences-in-a-config-file) say: _"If you prefer not to set preferences using the above method, you can instead put them into a config file.  ... You will NOT need to use `$this->pagination->initialize()` if you save your preferences in a config file"_.  

So can you simply explain how this `pagination.php` config file can be used for pagination in all controller functions when each controller/function will have at least one pagination setting (such as `base_url`) that's unique to only that one controller/function?

Can't use `pagination.php` configuration here:

```
$config['base_url'] = '/class/function/';   // <- UNIQUE to each Controller function
$config['uri_segment'] = 3;   // <- depends on above setting

$this->load->library('pagination');
$this->pagination->initialize($config);
$data['pagination'] = $this->pagination->create_links();
```

Can use `pagination.php` configuration here, but now there's no way to set `base_url` for just this one time:

```
$this->load->library('pagination');
$data['pagination'] = $this->pagination->create_links();
```

**Comment by narfbg** [comment]
> Your guess is wrong. It was version 3.0.0 (files dated March 30, 2015, 9:57 AM) that I downloaded and installed myself on April 5, 2015.

Ok.

Still, everything else I've said stands. The diff speaks for itself:

<pre>
$ git diff 3.0.0 3.1.0 system/libraries/Pagination.php
diff --git a/system/libraries/Pagination.php b/system/libraries/Pagination.php
index d63f61d..44f848f 100644
--- a/system/libraries/Pagination.php
+++ b/system/libraries/Pagination.php
@@ -6,7 +6,7 @@
  *
  * This content is released under the MIT License (MIT)
  *
- * Copyright (c) 2014 - 2015, British Columbia Institute of Technology
+ * Copyright (c) 2014 - 2016, British Columbia Institute of Technology
  *
  * Permission is hereby granted, free of charge, to any person obtaining a copy
  * of this software and associated documentation files (the "Software"), to deal
@@ -28,10 +28,10 @@
  *
  * @package	CodeIgniter
  * @author	EllisLab Dev Team
- * @copyright	Copyright (c) 2008 - 2014, EllisLab, Inc. (http://ellislab.com/)
- * @copyright	Copyright (c) 2014 - 2015, British Columbia Institute of Technology (http://bcit.ca/)
+ * @copyright	Copyright (c) 2008 - 2014, EllisLab, Inc. (https://ellislab.com/)
+ * @copyright	Copyright (c) 2014 - 2016, British Columbia Institute of Technology (http://bcit.ca/)
  * @license	http://opensource.org/licenses/MIT	MIT License
- * @link	http://codeigniter.com
+ * @link	https://codeigniter.com
  * @since	Version 1.0.0
  * @filesource
  */
@@ -44,7 +44,7 @@ defined('BASEPATH') OR exit('No direct script access allowed');
  * @subpackage	Libraries
  * @category	Pagination
  * @author		EllisLab Dev Team
- * @link		http://codeigniter.com/user_guide/libraries/pagination.html
+ * @link		https://codeigniter.com/user_guide/libraries/pagination.html
  */
 class CI_Pagination {
 
@@ -353,7 +353,8 @@ class CI_Pagination {
 	 */
 	public function initialize(array $params = array())
 	{
-		if (isset($params['attributes']) && is_array($params['attributes']))
+		isset($params['attributes']) OR $params['attributes'] = array();
+		if (is_array($params['attributes']))
 		{
 			$this->_parse_attributes($params['attributes']);
 			unset($params['attributes']);
@@ -496,7 +497,7 @@ class CI_Pagination {
 		{
 			$this->cur_page = $this->CI->input->get($this->query_string_segment);
 		}
-		else
+		elseif (empty($this->cur_page))
 		{
 			// Default to the last segment number if one hasn't been defined.
 			if ($this->uri_segment === 0)
@@ -512,6 +513,10 @@ class CI_Pagination {
 				$this->cur_page = str_replace(array($this->prefix, $this->suffix), '', $this->cur_page);
 			}
 		}
+		else
+		{
+			$this->cur_page = (string) $this->cur_page;
+		}
 
 		// If something isn't quite right, back to the default base page.
 		if ( ! ctype_digit($this->cur_page) OR ($this->use_page_numbers && (int) $this->cur_page === 0))
@@ -570,7 +575,7 @@ class CI_Pagination {
 		{
 			$i = ($this->use_page_numbers) ? $uri_page_number - 1 : $uri_page_number - $this->per_page;
 
-			$attributes = sprintf('%s %s="%d"', $this->_attributes, $this->data_page_attr, (int) $i);
+			$attributes = sprintf('%s %s="%d"', $this->_attributes, $this->data_page_attr, ($this->cur_page - 1));
 
 			if ($i === $base_page)
 			{
@@ -591,11 +596,11 @@ class CI_Pagination {
 		if ($this->display_pages !== FALSE)
 		{
 			// Write the digit links
-			for ($loop = $start -1; $loop <= $end; $loop++)
+			for ($loop = $start - 1; $loop <= $end; $loop++)
 			{
 				$i = ($this->use_page_numbers) ? $loop : ($loop * $this->per_page) - $this->per_page;
 
-				$attributes = sprintf('%s %s="%d"', $this->_attributes, $this->data_page_attr, (int) $i);
+				$attributes = sprintf('%s %s="%d"', $this->_attributes, $this->data_page_attr, $loop);
 
 				if ($i >= $base_page)
 				{
@@ -613,7 +618,7 @@ class CI_Pagination {
 					else
 					{
 						$append = $this->prefix.$i.$this->suffix;
-						$output .= $this->num_tag_open.'<a href="'.$base_url.$append.'"'.$attributes.$this->_attr_rel('start').'>'
+						$output .= $this->num_tag_open.'<a href="'.$base_url.$append.'"'.$attributes.'>'
 							.$loop.'</a>'.$this->num_tag_close;
 					}
 				}
@@ -625,7 +630,7 @@ class CI_Pagination {
 		{
 			$i = ($this->use_page_numbers) ? $this->cur_page + 1 : $this->cur_page * $this->per_page;
 
-			$attributes = sprintf('%s %s="%d"', $this->_attributes, $this->data_page_attr, (int) $i);
+			$attributes = sprintf('%s %s="%d"', $this->_attributes, $this->data_page_attr, $this->cur_page + 1);
 
 			$output .= $this->next_tag_open.'<a href="'.$base_url.$this->prefix.$i.$this->suffix.'"'.$attributes
 				.$this->_attr_rel('next').'>'.$this->next_link.'</a>'.$this->next_tag_close;
@@ -636,7 +641,7 @@ class CI_Pagination {
 		{
 			$i = ($this->use_page_numbers) ? $num_pages : ($num_pages * $this->per_page) - $this->per_page;
 
-			$attributes = sprintf('%s %s="%d"', $this->_attributes, $this->data_page_attr, (int) $i);
+			$attributes = sprintf('%s %s="%d"', $this->_attributes, $this->data_page_attr, $num_pages);
 
 			$output .= $this->last_tag_open.'<a href="'.$base_url.$this->prefix.$i.$this->suffix.'"'.$attributes.'>'
 				.$this->last_link.'</a>'.$this->last_tag_close;
@@ -644,7 +649,7 @@ class CI_Pagination {
 
 		// Kill double slashes. Note: Sometimes we can end up with a double slash
 		// in the penultimate link so we'll kill all double slashes.
-		$output = preg_replace('#([^:])//+#', '\\1/', $output);
+		$output = preg_replace('#([^:"])//+#', '\\1/', $output);
 
 		// Add the wrapper HTML if exists
 		return $this->full_tag_open.$output.$this->full_tag_close;
</pre>

(GitHub doesn't allow comparisons *of a single file* between versions)

>> In other words, you're looking in the wrong place.
>
> Well, that may be true, since I'm only looking for an explanation here.

Sorry, this is a bug tracker - we don't provide such support here, that's what the [forums](http://forum.codeigniter.com/) are for, and we're way off topic at this point.

> So can you simply explain how this pagination.php config file can be used for pagination in all controller functions

I can, but I won't. Sorry.
See above.

> when each controller/function will have at least one pagination setting (such as base_url) that's unique to only that one controller/function?

That's a precondition that *you are asserting*, not one that must always be used and/or true.

> (your code examples here)

You claim that this doesn't work, or can't work, or used to work but now doesn't ... Yet, I've already explained that this can't possibly be caused by `CI_Pagination`.

**Comment by sparky672** [comment]
>  If you looked at the code and/or the description of this issue, you'd know that only the 'attributes' configuration is reset. Everything else is kept until overriden with a different value.

Okay, I took a step back and was able to reproduce this... only the `attributes` config item is reset.  It would be great if this was mentioned someplace in the documentation.  Since my `attributes` setting is common to all instances, putting it within my `pagination.php` configuration file seemed like a logical choice.

So as long as you keep `$config['attributes']` out of the `pagination.php` config file, you can have global settings within `pagination.php` AND individual settings via `initialize()`.

Thanks for your time.
