### ISSUE TITLE
Session_files_driver.php unlink permission denied 

### ISSUE THREAD

**Issue by ckcks12** [bcit-ci/CodeIgniter#4481]
the gc function is trying to unlink session file that has been expired.

However I dunno why the unlink got error although the expired session file had been deleted well.
I should let it log itself which file it is trying to unlink.

Anyway for temporary the workaround it needs to check the file exists. 

I saw you did it on dec 2015 but why not on version 3 ? 
If I missed something please tell me 

----- the code before fix -----
```
unlink($this->_config['save_path'].DIRECTORY_SEPARATOR.$file);
```

----- the code I fixed -----
```
if( is_file($this->_config['save_path'].DIRECTORY_SEPARATOR.$file) )
{
	unlink($this->_config['save_path'].DIRECTORY_SEPARATOR.$file);
}
````

the error code is at line 371 in Session_files_driver.php

**Comment by narfbg** [comment]
Sorry, but you make no sense at all ...

- If `gc()` tries to delete a file, it's because it just saw it existing, the worst case scenario being an external process deleting the same file in between the `readdir()` and `unlink()` calls, which should be less than a millisecond.
- There already is an `is_file()` check on [line 364](https://github.com/bcit-ci/CodeIgniter/blob/3.0.4/system/libraries/Session/drivers/Session_files_driver.php#L364).
- There are no commits related to this from December 2015.
- This logic didn't exist at all before version 3, so I don't get what you mean by that either.

**Comment by ckcks12** [comment]
you did fix it at 21 feb 2015. actually it's not 3. 
issue #3610 
As you know, it's not the logic same to the version 3 but it's same problem so that I misunderstood. 
I will tell you my situation later. I guess that external process deletes that....... maybe. 
 I issued because this error never occurred when I check that the file exists

**Comment by narfbg** [comment]
February is 9 months prior to December ... that commit exists in all 3.x versions.
