### ISSUE TITLE
Unable to locate the specified class: Session.php despite logs claiming session is running and cannot run again

### ISSUE THREAD

**Issue by Tech-Imp** [bcit-ci/CodeIgniter#4483]
So, upon following the upgrade instructions posted on the main site, and spending a week hammering at my site that was operational in 2.x I have reached an odd impasse.

I get a **Unable to locate the specified class: Session.php error** onscreen when a page should be shown (granted that page relies on the session to determine who has just logged in, so it can pull up the proper options) despite the fact that logging states

 DEBUG - 2016-02-24 08:15:17 --> Session class already loaded. Second attempt ignored.

and the browser shows that the session cookie exists

![session exists](https://cloud.githubusercontent.com/assets/11774935/13292381/226e830c-dae1-11e5-8aa0-17c31d6894bb.png)

and the database has the session properly synced up

![session in database](https://cloud.githubusercontent.com/assets/11774935/13293557/b5e2548e-dae5-11e5-82a9-6183a89f472d.png)

which seems overly odd to me. There are **no other warnings or errors generated** . The project has had its system folder deleted and replaced by the new version, as expected. Configurations from the new version have been used and the values for the appropriate things have been transferred. The database works as it is able to do its proper check and redirect based on things set in it (locking certain pages if the user is not logged in, and redirecting to the front).  I have gone out of my way to get everything in a row, checked the internet, seen similar incidents and no resolution as I have done **every item on the upgrade list twice** . There are no foreign libraries in play. This is for all intents and purposes, a base codeigniter upgrade. The only other things used are CSS and javascript based (bootstrap) which I am not even reaching yet on the session locked pages.

So to be clearer, the pages that need to reference the session variable and determine if that role is allowed to view the page is working, the mechanism for actually showing the contents is erroring out with cannot find session.php (despite the fact it just referenced it to remain on this page and passed the check for if this role is valid).

There was one hacky sort of thing that was suggested, putting session as a driver (rather than the library it is) and placing session.php outside of its specific session folder (system\libraries\Session) into the root folder for libraries in the system core (system\libraries). which yielded even weirder results, but as that is not a documented procedure, I decided to reach out to see where the error actually resided.

This issue currently prevents a launch that was on track for the end of the month that has been designed over the course of the past year.

Here is a copy of relevant areas, sensitive information has been stripped out.

from autoload.php
```

$autoload['libraries'] = array('session', 'encryption', 'database');
$autoload['helper'] = array('url','cookie');

```

from config.php

```
$config['base_url'] = 'https://meta-game.net';

$config['index_page'] = '';

$config['uri_protocol']	= 'REQUEST_URI';

$config['url_suffix'] = '';

$config['language']	= 'english';

$config['charset'] = 'UTF-8';

$config['enable_hooks'] = FALSE;

$config['subclass_prefix'] = 'MY_';

$config['composer_autoload'] = FALSE;

$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

$config['allow_get_array'] = TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

$config['log_threshold'] = 2;

$config['log_path'] = '';

$config['log_file_extension'] = '';

$config['log_file_permissions'] = 0644;

$config['log_date_format'] = 'Y-m-d H:i:s';

$config['error_views_path'] = '';

$config['cache_path'] = '';

$config['cache_query_string'] = FALSE;

$config['encryption_key'] = 'REMOVED FOR SECURITY REASONS';

$config['sess_driver'] = 'database';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = 'ci_sessions';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;


$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$config['cookie_secure']	= TRUE;
$config['cookie_httponly'] 	= TRUE;

$config['standardize_newlines'] = FALSE;

$config['global_xss_filtering'] = FALSE;

$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
$config['csrf_exclude_uris'] = array();


$config['compress_output'] = FALSE;

$config['time_reference'] = 'local';

$config['rewrite_short_tags'] = FALSE;

$config['proxy_ips'] = '';
```

From Log file (tried to keep it as short as possible with only navigation to bases site, login page and admin console)
[log-2016-02-24.txt](https://github.com/bcit-ci/CodeIgniter/files/145034/log-2016-02-24.txt)

Session.php is located under \meta-game\system\libraries\Session as expected along with all the other items concerning it

**Comment by Tech-Imp** [comment]
If additional information is required please let me know what. I tried to include all the items, short of my entire project, that I thought might be useful.

**Comment by narfbg** [comment]
For this to happen, something in your code is doing a `load_class('Session')` call, which you're not supposed to do.

One thing you didn't mention to have checked is having extensions/overrides under *application/core/* and/or *application/libraries/*, so I'm guessing one such extension designed for CI2 is now (naturally) misbehaving.  
That's just a guess though ... I can't tell anything for sure without seeing the relevant code, which is the only thing you haven't provided.

Also, if you're looking for help, please post on our [forums](http://forum.codeigniter.com/) instead. This is surely not a CI bug and we do only deal with bug reports here on GitHub.

P.S.: Screenshots are very rarely useful and more often than not - an annoyance. Please don't do that in the future unless explicitly asked for them.

**Comment by Tech-Imp** [comment]
There are no instances of load_class('Session') in the project. Searching for all instances of session also yielded no oddies. If you wish, I can find a way to include that search.

There was one instance of  $this->load->library('session'); in the login causing the second time for the thing to be loaded. Removing that line caused that error to disappear.


**However the underlying issue remains. **


Attached please find the simple code that exists within libraries and core. None of this should be triggering this issue. 

https://meta-game.net/files/core%20and%20libraries.zip

If it **wasnt** saying a file could not be located when ** it is clearly using said file** Id be inclined to agree with the assessment that this isnt a bug in CI.

My only reason for including the screenshots was to limit the potential for something obvious I was missing and to prove the steps followed.

**Comment by narfbg** [comment]
I'm not saying it's a direct, as is `load_class('session')` call ... some function of yours is most likely calling `load_class()` on whatever library name you're passing it.

And no offense, but please don't tell me when to close an issue or not - I have **verified** that `load_class()` is the only CI function that could trigger this error and I have **verified** that CI does no such calls for the session library, so I highly doubt that this is the 1 in a 500 case where I make the wrong judgement.  
I understand you're frustrated, but that doesn't mean the issue stays upen until your problem is solved.

**Comment by narfbg** [comment]
Also:

> There was one hacky sort of thing that was suggested, putting session as a driver (rather than the library it is) and placing session.php outside of its specific session folder (system\libraries\Session) into the root folder for libraries in the system core (system\libraries). which yielded even weirder results, but as that is not a documented procedure, I decided to reach out to see where the error actually resided.

This can only trigger the error in question ... system/libraries/Session.php isn't supposed to exist, that's exactly why the upgrade instructions explicitly say that you must delete the old system/ dir and replace it with the new one.

**Comment by Tech-Imp** [comment]
Did you look at the items you requested? 

There are NO instances of load_class anywhere in my application folder. None. The only time load_class is used is in the system folder....with items that are not touched by me at all. As in it is pristine from the download.

 I tried to abide by the standards of a language. As for the "workaround" thats why I mention it. I wasn't gonna use something hacky like that, and have reverted my system folder back to normal before I even filed the ticket.

**Comment by narfbg** [comment]
I did look at what you provided, although that was not what I requested - I did guess that extensions could be causing the issue, but what I said you haven't provided is the actual code that triggers the error.

Another thing that I saw now - an `is_loaded('session')` call could cause CI to do a `load_class('session')` call, but `is_loaded()` is again a function that you're not supposed to use.

**Comment by Tech-Imp** [comment]
Aka the system folder is exactly as it is downloaded from the Codeigniter site. 

Neither is_loaded nor load_class are used anywhere in the entire applications folder (the only place I have that contains php files aside from system, and I have not touched system after the clean upgrade)

If I thought it was a simple thing that google could have solved I wouldn't be here. I have cleaned everything, found every "troubleshooting" for the issue, come accross numerous tickets mentioning this that you've closed without more than telling them to redo the steps. I have found no solutions.

As you are the only one with extensive knowledge, I am at at an impasse.

I have exhausted every avenue short of spending months digging into code you are saying works perfectly. I dont have that time. It may be simpler to switch to another framework at that point. Id really prefer to not do that as I will have lost a years worth of development and testing.


As it stands you are saying only one thing can trigger this error. I have searched the entire structure. Those lines does not appear in any code I have in my project. It only appears in the system folders that come from.


Extensions get included by this function, they are currently functioning properly redirecting traffic as expected based on the information in the session:

```

function __autoload($classname)
 {
     if (strpos($classname, 'CI_') !== 0){
		$file= APPPATH . '/core/extensions/' . $classname . '.php';
		if (file_exists($file) && is_file($file)) {
			@include_once($file);
		} 
     }
 }
```

You said you didnt get what you requested. Please restate what you are looking for.

**Comment by Tech-Imp** [comment]
Hmm something you said sparked an idea. 
I am able to access some of the locked down pages while logged in but not ones with dynamic content. that immediately require access to the session to verify things to display. 
Investigating...

**Comment by narfbg** [comment]
> Aka the system folder is exactly as it is downloaded from the Codeigniter site.

You already said that, you don't need to repeat it.

> Neither is_loaded nor load_class are used anywhere in the entire applications folder (the only place I have that contains php files aside from system, and I have not touched system after the clean upgrade)

Yet, the `__autoload()` function that you've now shown doesn't have a specific place to be put in under application/, so you're obviously doing *something* not quite as it was intended.

> If I thought it was a simple thing that google could have solved I wouldn't be here. I have cleaned everything, found every "troubleshooting" for the issue, come accross numerous tickets mentioning this that you've closed without more than telling them to redo the steps. I have found no solutions.

I didn't say it was a simple thing, nor that it is solvable by a google search.

> As you are the only one with extensive knowledge, I am at at an impasse.

I am surely not the only one such person, even if the only one publicly known. If you're suggesting that I'm the only one you know could help you and therefore I should ... Well, I don't really mind, but this is a *bug tracker* and I will always refuse to accept it as a route to request help from me.

> I have exhausted every avenue short of spending months digging into code you are saying works perfectly. I dont have that time. It may be simpler to switch to another framework at that point. Id really prefer to not do that as I will have lost a years worth of development and testing.

No offense, but I get the impression that you've spent way too much time in looking for other people getting the same error message as opposed to hands-on debugging on your own. That often saves a lot of time.

> As it stands you are saying only one thing can trigger this error. I have searched the entire structure. Those lines does not appear in any code I have in my project. It only appears in the system folders that come from.

Well, *something* is calling `load_class()` with the first parameter to it being 'session', and it is not CI:

<pre>
narf@vaio ~/github/CodeIgniter $ grep -r 'load_class(' system/
system/core/Loader.php:		//       load_class('Model', 'core');
system/core/Loader.php:		//       However, load_class() instantiates classes
system/core/Common.php:	function &load_class($class, $directory = 'libraries', $param = NULL)
system/core/Common.php:	 * called by the load_class() function above
system/core/Common.php:		$_error =& load_class('Exceptions', 'core');
system/core/Common.php:		$_error =& load_class('Exceptions', 'core');
system/core/Common.php:			$_log[0] =& load_class('Log', 'core');
system/core/Common.php:		$_error =& load_class('Exceptions', 'core');
system/core/Common.php:		$_error =& load_class('Exceptions', 'core');
system/core/URI.php:		$this->config =& load_class('Config', 'core');
system/core/URI.php:		return ltrim(load_class('Router', 'core')->directory, '/').implode('/', $this->rsegments);
system/core/Input.php:		$this->security =& load_class('Security', 'core');
system/core/Input.php:			$this->uni =& load_class('Utf8', 'core');
system/core/Hooks.php:		$CFG =& load_class('Config', 'core');
system/core/Output.php:		// Note:  We use load_class() because we can't use $CI =& get_instance()
system/core/Output.php:		$BM =& load_class('Benchmark', 'core');
system/core/Output.php:		$CFG =& load_class('Config', 'core');
system/core/CodeIgniter.php:	$BM =& load_class('Benchmark', 'core');
system/core/CodeIgniter.php:	$EXT =& load_class('Hooks', 'core');
system/core/CodeIgniter.php:	$CFG =& load_class('Config', 'core');
system/core/CodeIgniter.php:	$UNI =& load_class('Utf8', 'core');
system/core/CodeIgniter.php:	$URI =& load_class('URI', 'core');
system/core/CodeIgniter.php:	$RTR =& load_class('Router', 'core', isset($routing) ? $routing : NULL);
system/core/CodeIgniter.php:	$OUT =& load_class('Output', 'core');
system/core/CodeIgniter.php:	$SEC =& load_class('Security', 'core');
system/core/CodeIgniter.php:	$IN	=& load_class('Input', 'core');
system/core/CodeIgniter.php:	$LANG =& load_class('Lang', 'core');
system/core/Security.php:			$uri = load_class('URI', 'core');
system/core/Router.php:		$this->config =& load_class('Config', 'core');
system/core/Router.php:		$this->uri =& load_class('URI', 'core');
system/core/Controller.php:			$this->$var =& load_class($class);
system/core/Controller.php:		$this->load =& load_class('Loader', 'core');
system/database/DB_driver.php:		$LANG =& load_class('Lang', 'core');
system/database/DB_driver.php:		$error =& load_class('Exceptions', 'core');
</pre>

Obviously, the only `load_class()` call between these that could trigger an error for Sessions is the one in *system/core/Controller.php*, [here](https://github.com/bcit-ci/CodeIgniter/blob/3.0.4/system/core/Controller.php#L75).
And if you look at that file, you'll see that the input comes from `is_loaded()`, which itself is only called by `load_class()`, so ... yea, a `load_class()` call is causing it.

> Extensions get included by this function, they are currently functioning properly redirecting traffic as expected based on the information in the session:

When I say "extensions" I mean what the term means in CodeIgniter, which is all files under application/core/ or application/libraries/ that modify CI's stock classes' behavior.
I am *not* referring to your application/core/extensions/ directory, although it shouldn't exist in the first place - you're not supposed to put anything under application/core/ that doesn't already exist in system/core/.

> You said you didnt get what you requested. Please restate what you are looking for.

The "userspace" code (the pieces that don't already exist in stock CI) that triggers the error - it could be a model, a controller, a third-party library, a custom script that you may've included in a nobody-knows-how way ... 
*But*, again, this is not something that belongs on the framework's bug tracker and you should post about it on our [forums](http://forum.codeigniter.com/) instead. We have *a lot* of people coming here to look for geniune bug reports, track development progress, etc. and I just can't allow it to become a generic debugging service for the public - we don't have the resources to cope with that.

**Comment by Tech-Imp** [comment]
I know you mentioned that you dont like screenshots but:

![querry results](https://cloud.githubusercontent.com/assets/11774935/13300024/c38074a4-db03-11e5-9e8d-5b3d91b030dc.png)

Quite literally there is no instance in my userspace code. Same for is_loaded.

Also, what would be the proper procedure for the extensions I have? They are intended as an additional layer like MY_Controller but there need to be 3 distinct flavors based on the section of the site. I wanted forced separation at the time but I should reevaluate them soon. 

The models on most of the pages need to reference the session further to see what data they are allowed to show. A few do not, those pages are reachable. Ill try and narrow it down further. I do know the potentially affected models do reference items the session like this:

 $this->session->userdata('id');

Wait....can the changes to the structure of how the ci_session is setup now to refer to the first column as id rather than session_id be causing an issue? In which case Id need to make a change on created tables in my database?

I do appreciate that you are helping, and if its not a bug hopefully this helps for documentation of oddities that can occur during the transition.

**Comment by narfbg** [comment]
Sorry, but I asked you twice directly and more times indirectly to move this to the forums and instead you're now asking me questions that aren't even related ... Can't help you more with that here.

**Comment by Tech-Imp** [comment]
Found it. Sorry...wanted to complete the train of thought here.

Apparently the models have become a lot more intolerant of having controllers in them. AKA something was including CI_Controller when it should have used CI_Model. That causes this whole issue >_<;

Thank you for your patience. Hopefully this chain helps someone else next time.
