### ISSUE TITLE
is_cli() doesn't return true when called from cli

### ISSUE THREAD

**Issue by bright-light-in-the-night** [bcit-ci/CodeIgniter#4565]
Because **is_cli()** doesn't return true, the caller **csrf_verify()** throws an error at **$_SERVER['REQUEST_METHOD']** about undefined index and you cannot count of is_cli() function.
The **php_sapi_name()** will return lightspeed in my case, **PHP_SAPI === 'cli'** returns false and **defined('STDIN')** returns false as well.
I have hacked the **Common.php** file manually, and did overwrite the **is_cli() **function with return **!isset($_SERVER['SERVER_ADDR']);**
Personally, I have never encountered a case where calling a Codeigniter script from cli to set the **SERVER_ADDR** key in **$_SERVER**. Wouldn't be better for is_cli() to be:

```
function is_cli()
{
	return (!isset($_SERVER['SERVER_ADDR']) OR PHP_SAPI === 'cli' OR defined('STDIN'));
}
```

**Comment by narfbg** [comment]
That's not CodeIgniter's problem ... Checking for existence of `STDIN` is already a work-around for similar situations. If that doesn't exist - you should report it to the Litespeed vendor.

`$_SERVER['SERVER_ADDR']` may not exist by default in CLI, but it is also something that just happens to work for you and not a reliable way to detect the environment.

**Comment by bright-light-in-the-night** [comment]
You are probably not gonna like this, but Codeigniter should work on most platforms, not the other way around. **$_SERVER['SERVER_ADDR']** is not set in cli, of course, that's why it could be included at the end of that return check. It's not that much to make another check.

**Comment by bright-light-in-the-night** [comment]
You are probably not gonna like this, but Codeigniter should work on most platforms, not the other way around. **$_SERVER['SERVER_ADDR']** is not set in cli, of course, that's why it could be included at the end of that return check. It's not that much to make another check.

**Comment by narfbg** [comment]
Well, you're probably not gonna like this either, but Litespeed on CLI isn't "most environments". :)  

We can't add checks for every single edge case, and while `$_SERVER['SERVER_ADDR']` may not exist by default on CLI, it can be set at runtime and/or as part of a lazy sysadmin's environment configuration.
Doing this check for *you* is bound to break somebody else's application - that just what happens when you do work-arounds for obviously broken conditions.

As I said, you should report this to Litespeed. We may be more easily reachable, but that doesn't mean it's our responsibility to fix issues caused by other projects.
