### ISSUE TITLE
The query builder: No way to remove the limit clause

### ISSUE THREAD

**Issue by ivantcholakov** [bcit-ci/CodeIgniter#4597]
On a cloned query builder object I am trying to remove the offset and limit clauses. Offset can be set to zero, but I don't see a way using the API to remove the limit clause.

https://github.com/bcit-ci/CodeIgniter/blob/3.0.6/system/database/DB_query_builder.php#L1242

I think, the method limit($value, $offset = 0) can be made to accept boolean FALSE in its first parameter for serving this case.

Edit: OFFSET can not be cleared too.

**Comment by narfbg** [comment]
I don't think any clause can be cleared (it alone), because QB is simply not built with that in mind.

It's not worth the effort to change this and there's not really a sane use case for it. As in, I can't imagine why you'd want to `clone`, but if you do - you should be cloning objects in "vanilla" condition, not ones that you need to artificially reset to a clean state.
