### ISSUE TITLE
$this->db->trans_status() always TRUE

### ISSUE THREAD

**Issue by tebbic** [bcit-ci/CodeIgniter#4604]
$this->db->db_debug=FALSE;
$this->db->trans_begin();
$this->db->insert("table0",$data0)
$this->db->insert("table1",$data1);//this step will fail;
$this->db->update("table2",$data2);
if($this->db->trans_status() ===FALSE){
$this->db->trans_rollback();
return false;
}
$this->db->trans_commit();

///table0,table1,table2 always be changed!!!

**Comment by narfbg** [comment]
How are table0, *table1*, table2 always changed and at the same time you're saying the `insert()` on *table1* is failing?

Also, which database driver and CI version are you using?

**Comment by tebbic** [comment]
database mariadb 5.5
engine innodb
dbdriver= mysqli
CI version=3.0

**Comment by narfbg** [comment]
"3.0" says pretty much nothing ... there are **7** 3.0.x versions.

Also, you didn't answer my first question.

**Comment by tebbic** [comment]
like title,when `insert` table1 fail, `$this->db->trans_status()` always be `TRUE`

**Comment by tebbic** [comment]
CI version 3.0.2

**Comment by narfbg** [comment]
Well, then upgrade to the latest version - 3.0.6.

**Comment by tebbic** [comment]
why,this is a bug of 3.0.2?

**Comment by tebbic** [comment]
can you tell me season? or tell me a link?

**Comment by narfbg** [comment]
A season? I suppose you mean reason?
Or a link to what?

Look, this is a bug tracker, not a Q&A site (the above questions are rhetorical).

Even ignoring the fact that, yes - a number of DB transactions-related bugs have already been fixed in newer versions - you're not supposed to report bugs for old versions in the first place.

Before opening an issue here, you need to do all of the following:

- Verify that your problem is 100% caused by a bug.
- Search the repository for other similar issues that may have already been reported (they have).
- Make sure that you're using the latest version (you're not).
- Make sure that the bug is not already fixed (it has been).

If you can't confirm all of these, and you're just seeking help with something, ask your question on our [forums](http://forum.codeigniter.com/) instead.
