### ISSUE TITLE
site_url trims trailing slash

### ISSUE THREAD

**Issue by SoundlessCoder** [bcit-ci/CodeIgniter#4605]
`site_url` trims slashes on the left and right side of the URI passed.  There are cases where I need my relative URLs to keep their slashes on the right, e.g.

    /segment/case/read/

If you pass the above string into `site_url`, it will remove the `/` on the right side, like so:

    site_url('/segment/case/read/'); // http://www.url.com/segment/case/read

The desired output should be:

    http://www.url.com/segment/case/read/

I utilize the `redirect` function for redirects, but if you pass a relative URL it will use `site_url` to prepend your configured URL which affects the relative URL passed.  I have apache configured to force trailing slashes in every request.  If I'm using `redirect` to redirect to a relative URL, apache will force a rewrite and produce a 2nd redirect (303/307 from CI then 301 from apache) which is not the desired output.

`site_url` should only trim the left trailing slash.

**Comment by narfbg** [comment]
Perhaps somebody else has configured nginx to do the opposite - strip a possible trailing slash and redirect to that.

So why is yours the desired behavior?

**Comment by SoundlessCoder** [comment]
If someone prefers to not have trailing slash could just omit the forward slash in `site_url`, while others can do the opposite.

**Comment by mwhitneysdsu** [comment]
It looks like this might require some additional modifications, and maybe a big bold notice in the release notes when it goes through. For instance, in `site_url()` itself, if `$this->config['url_suffix']` is set, it checks for a question mark to place the suffix before the query string, but it doesn't check for a trailing slash (and, if there is one, what would be the expected behavior?).

Some users' existing code will have to be modified simply because it was written with the assumption that `site_url()` would trim the trailing slash. I'm currently checking my own codebase(s) because I'm sure I got lazy once in a while and did something that will require modification when this change goes through.

**Comment by narfbg** [comment]
@mwhitneysdsu Good point on the BC break, although we generally ignore these minor ones when the cause is deemed to be a bug.

We could move this to 3.1.0 though ... @jim-parry What do you think?

**Comment by jim-parry** [comment]
I have no problem with this being in 3.0.7.
We could do the community a service by beefing up the unit tests for Config, explicitly indicating the expected behavior with & without url_suffix set and with & without a query string. Did you want me to do a PR for that?

**Comment by narfbg** [comment]
It is already pretty well-tested.

**Comment by koichirose** [comment]
This broke everything for me, I have nginx set to strip trailing slashes and redirect to the stripped URL.
I noticed soon enough (after about 1h in production) and fixed it by extending Codeigniter's Config class and using the old _uri_string function.

I should have looked at the changes more carefully, a heads up about a possible BC break would have been nice in the upgrading guide here http://www.codeigniter.com/user_guide/installation/upgrading.html
