### ISSUE TITLE
Failed Migrations Error Handling

### ISSUE THREAD

**Issue by EpicKris** [bcit-ci/CodeIgniter#4631]
It would be useful to be able to fail a migration by returning `FALSE` within the `up()` or `down()` functions, and the migrations library then showing a migration error using the error view templates.

**Comment by narfbg** [comment]
If we were writing it now - maybe, but we're not and that's a huge BC break.

Throw an exception.

**Comment by EpicKris** [comment]
Why is that a BC break since the `up()` and `down()` functions currently don't return any value?

What about a different method by setting a property (`fail`) to either TRUE or a string (error message) of the migrations library, and then the library showing a migration error.

I'm trying to handle such errors more gracefully in the event a user may come across such an error.

**Comment by narfbg** [comment]
If no return value has been checked so far, you haven't had a reason to return anything so far, meaning that by default all of your migrations fail now - I shouldn't be explaining this, it's really obvious.

Why are you avoiding exceptions? *This* is what they're made for.

**Comment by EpicKris** [comment]
Why would all my migration fail now because they're not returning anything? They would only fail if `FALSE` was returned, anything else would be considered successful.

I tend to avoid exceptions so the user doesn't see them? I have a feeling I'm missing something about exceptions, maybe I should read into them more. Thanks @narfbg .

**Comment by narfbg** [comment]
Checking *only* for FALSE may indeed work - I didn't think of that.
But that's hacky at best, as it goes against a very common (and not accidental) practice of considering everythig *except TRUE* to be a failure. And there's a problem with that - anybody not knowing that `=== FALSE` is intentional, may and most likely will invert the condition while refactoring for whatever reason - I know I would.

If you don't want your users to get an error message, Exceptions can be caught on demand, but I don't see the point - you SHOULD display an error message in case of a migration failure, and we already have a friendly enough looking view for them.

Even if that wasn't the case, looking for an exception instead of a FALSE return value would still be the better option.

**Comment by EpicKris** [comment]
Totally understand, I did a bit more reading around exceptions so I understand them a bit better now!

Perhaps this could be implemented so that at least if an exception is thrown then the migration table doesn't update, which I believe it currently does?

**Comment by narfbg** [comment]
It doesn't, that's why I told you to throw an exception in the first place.
