### ISSUE TITLE
Incorrect data type LONGTEXT with Cubrid and Forge

### ISSUE THREAD

**Issue by triquetrum** [bcit-ci/CodeIgniter#4640]
/system/database/drivers/cubrid/cubrid_forge.php

protected function _attr_type(&$attributes)

case 'LONGTEXT': $attributes['TYPE'] = 'STRING';

**Comment by narfbg** [comment]
Elaborate please ... this tells us nothing.

**Comment by rvankin** [comment]
I build small project. It must use MySQL and Cubrid. Need to save big text to db. When I create table Cubrid shows error about data type 'LONGTEXT' because don't have it. Cubrid have STRING data type, but MySQL don't have it.

Then, I see cubrid_forge.php file. I just found this solution, added rewrite for LONGTEXT data type in the Cubrid forge. Or maybe have another solution?

**Comment by rvankin** [comment]
Maybe need add anything to compare data types for supported databases?
