### ISSUE TITLE
table_exists() function should be case insensitive

### ISSUE THREAD

**Issue by Seb33300** [bcit-ci/CodeIgniter#4641]
`$this->db->table_exists($table)` should make a case insensitive test to check if the table exists.

In MySQL `CREATE TABLE Test` will result in a `test` table.

Then, `$this->db->table_exists('Test')` will return `false` since it should return `true`.

**Comment by mwhitneysdsu** [comment]
http://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html

There are similar issues with databases other than MySQL. Case sensitivity of table names tends to be controlled by configuration of the database. The behavior you describe is the default behavior of MySQL only on Windows.

It might be a good idea to do case-insensitive tests because some databases are terrible about being consistent in this sense. However, if your case changes in your code, there are configurations which would cause a case-insensitive test here to pass but cause any other code which uses the wrong case for the table name to fail.

The best solution when you need your code to be portable between Windows, Linux, and/or OS X is to only use lowercase table names.

**Comment by narfbg** [comment]
Indeed, this is OS-dependant and we tend to respect case-sensitivity in these cases.
