### ISSUE TITLE
DB_Result->custom_result_object() throw IndexError when the result is empty

### ISSUE THREAD

**Issue by azhai** [bcit-ci/CodeIgniter#4658]
In File database/DB_Result.php line 180:
When the result is empty, $this->custom_result_object does not have a key $class_name
```php
		if (isset($this->custom_result_object[$class_name]))
		{
			return $this->custom_result_object[$class_name];
		}
		elseif ( ! $this->result_id OR $this->num_rows === 0)
		{
			return array();
		}
```
Fix it:
```php
		if (isset($this->custom_result_object[$class_name]))
		{
			return $this->custom_result_object[$class_name];
		}
		else {
			$this->custom_result_object[$class_name] = array();
		}
		if ( ! $this->result_id OR $this->num_rows === 0)
		{
			return array();
		}
```

**Comment by narfbg** [comment]
The problem that you're describing doesn't exist. `isset()`, specifically, doesn't trigger errors for non-existent keys.

**Comment by mwhitneysdsu** [comment]
I think there may be an issue here, but not necessarily as described. On line 206, `$this->custom_result_object[$class_name]` is used without having been initialized: 

```php
		if ($_data !== NULL)
		{
			for ($i = 0; $i < $c; $i++)
			{
				$this->custom_result_object[$class_name][$i] = new $class_name();

```

As far as I can tell, though, this code should not run if the result is empty. This would instead be the code which runs when the result has already been retrieved.

The array is initialized on line 218 before being used in a similar manner on line 222: 

```php
		$this->custom_result_object[$class_name] = array();

		while ($row = $this->_fetch_object($class_name))
		{
			$this->custom_result_object[$class_name][] = $row;
		}
```

Without a better description to help in replicating the issue, I can't be 100% sure that initialization is necessary before line 206, rather than just good practice. However, it probably wouldn't hurt to move line 218 up (though I wouldn't do it as suggested above, since that would potentially cause problems on subsequent calls to `custom_result_object()`.

**Comment by narfbg** [comment]
That is not a problem either: https://3v4l.org/8KfBa

These errors are only triggered on read.
