### ISSUE TITLE
Could Session library become available in CLI?

### ISSUE THREAD

**Issue by luka-zitnik** [bcit-ci/CodeIgniter#4702]
Hi,

Disabling Session library in CLI really only makes it harder for me to test my CI application. I have to trick it it's been run by a web server.

I've tried to track down the reason why Session library is disabled in CLI.
https://github.com/bcit-ci/CodeIgniter/commit/2e3e23053d9748c68fa2c0e11f43af67da8743e8#diff-3ac2a07491f0f80bca8ca1b9ff04b392
It wasn't obvious to me.

**Comment by narfbg** [comment]
There are no sessions under CLI.

**Comment by luka-zitnik** [comment]
They don't make much sense, do they? But they seem functional. And then what if they can be used like in [here](https://github.com/luka-zitnik/CodeIgniterModule) Andrey?

**Comment by narfbg** [comment]
They don't make *any* sense, and while I understand your POV, this is all that matters.

Years ago, there used to be no restriction, until we changed the library to access `$_SESSION['REMOTE_ADDR']` instead of `CI_Input::ip_address()` and people started complaining about errors under CLI. They (expectedly) weren't really using the library, it was just auto-loaded or something like that.

Bottom line is, I prefer a handful of people doing trickery rather than a large crowd complaining.

**Comment by luka-zitnik** [comment]
OK. I trust you any change regarding this issue would ultimately boil down to deliberately causing a regression. And that's no fun.
