### ISSUE TITLE
get_cookie() doesn't prepend prefix

### ISSUE THREAD

**Issue by skunkius** [bcit-ci/CodeIgniter#4818]
In CI, I'm using cookie named, e.g. currency. I have shop, that uses cookie named currency too.

I have set prefix to use with my CI cookies, e.g. ci_. So, now cookie should be ci_currency. Using get_cookie('currency') - I get my shop currency value. If I manualy enter get_cookie('ci_currency') - I get my CI currency value.

In documentation stated: "... except it will also prepend the $config['cookie_prefix'] ...". No auto prepend for get_cookie()?

**Comment by mwhitneysdsu** [comment]
Here's the code which is causing your confusion:
https://github.com/bcit-ci/CodeIgniter/blob/develop/system/helpers/cookie_helper.php#L91

```php
$prefix = isset($_COOKIE[$index]) ? '' : config_item('cookie_prefix');
```

Whether it uses the prefix is dependent on whether it is set when it checks for the value without the prefix. So, if you're using the prefix because the cookie may already exist without the prefix, you may run into problems if you don't supply the prefix yourself when calling `get_cookie()`. The documentation could probably be clearer on this point.

I don't think this is likely to be changed, so you may be better off creating a `MY_cookie_helper` to define the `get_cookie()` function with the middle line modified to always use the cookie prefix if it is set:

```php
$prefix = is_null(config_item('cookie_prefix')) ? '' : config_item('cookie_prefix');
```

alternatively, if you're using PHP 7:

```php
$prefix = config_item('cookie_prefix') ?? '';
```

Or, if you prefer to avoid the need to make sure you stay on top of any changes to this function in the long term (though, other than documentation, this helper's code hasn't changed in years), you can define your own function to prepend the prefix and call `get_cookie()`.

**Comment by skunkius** [comment]
Agree, documentation should be clearer. Thanks for suggestions!
