### ISSUE TITLE
[BUG] Sessions and PHP7/7.1

### ISSUE THREAD

**Issue by dyanakiev** [bcit-ci/CodeIgniter#4830]
Hello when i switch from php 5.6 to 7 or 7.1 my sessions stop working correctly.
What is happening? On every reload ci_session cookie is changing and php session too.
I tried files session storage,database, memcached no difference.
I also tried fresh codeigniter without modifications and problem still persists.

My webserver setup is managed with serverpilot.io and php-fpm services with provides me fast php swithing.

I use latest 3.1.0 ci.

**Comment by gxgpet** [comment]
Related to #4179? 

Even so, I recommend post your question on [CodeIgniter forums](http://forum.codeigniter.com/), it's more likely you are having an issue with your own project, rather than a CodeIgniter issue.

**Comment by narfbg** [comment]
There's a thousand things that can break sessions.
PHP 7.1 has a release candidate, but is not officially out yet.
PHP 7.0 runs just fine for other people using CodeIgniter's sessions.

How did you determine that this is a bug?

And also, you don't need to prefix your title with `[bug]` - we don't welcome non-bug threads here.

**Comment by vahidov** [comment]
https://github.com/bcit-ci/CodeIgniter/issues/3649

In php 7.1 are new session configuration values:
session.sid_length
session.sid_bits_per_character
http://php.net/manual/en/session.configuration.php#ini.session.sid-length

and by default values regex: /^[0-9a-f]{40}$/ is not working.

**Comment by narfbg** [comment]
... and that has nothing to do with 7.0.

**Comment by jchbh-duplicate** [comment]
I meet the same problem. 
I spent whole day on this, currently I find the cookie value 'ci_session' not visible. ( through cookie helper ).
I see the session_start() call database helper's read() function with new session_id every time.  I think it may because PHP not found session id information in cookie.

is there any changes to PHP 7.1 on cookie part?

**Comment by dyanakiev** [comment]
Just to confirm: Everything works perfect with 3.1.1, no more problems with sessions. 

👍 Good job! 💃

**Comment by narfbg** [comment]
Well, it wasn't so perfect.

2f760877c313871e5066b93b0b1aa76428c09fb6

**Comment by joedes** [comment]
ola a todos, tive o mesmo problema, com a versão php 7.1, estranho, que em algumas paginas, minhas sessões funcionavam corretamente, mas na maioria as sessões não estavam sendo guardadas, mas mas nas versões anteriores sim. até mesmo na versão 7.0, meu projeto funcionava bem, apenas quando mudava para 7.1, as sessões não eram mostradas. ATUALMENTE ESTOU USANDO A VERSÃO 7.0 ESTA OK PRA MIM ATÉ O MOMENTO.

**Comment by jim-parry** [comment]
@joedes English only, thanks. Don't know what you are saying.

**Comment by joedes** [comment]
Hi all, the problem is the same, with a php 7.1 version, strange, that on some pages, my functions work correctly, but mostly as sessions are not being used, but in previous versions of php 5.2, 5.6 and 7.0 my project worked well, only when it changed to 7.1, as sessions not presented in SOME PAGES OF THE PROJECT. CURRENTLY I'M USING VERSION 7.0 IS OK TO ME UNTIL THE TIME.

**Comment by mckaygerhard** [comment]
@joedes this still happened to me with lasted 3.x ci, seems only with redirects! do you use redirects? or cookies kind of configurations?

**Comment by narfbg** [comment]
This is almost a 4 year old issue and it was fixed, 10 releases ago. Whatever problem you're having now, it's not the same thing and randomly commenting on old bug reports isn't going to help you.
