### ISSUE TITLE
$this->_reserved_identifiers is unreachable for a honest developer.

### ISSUE THREAD

**Issue by jthanto** [bcit-ci/CodeIgniter#4869]
When using the Active Record for updating and inserting data, we used to be able to set $this->_reserved_identifiers outside of DB_driver.php. Now it looks like it is protected, and I can't see any clear way to change this.
This removes the possibility of using statements like
    UPDATE LOW_PRIORITY table set ...
When using the querybuilder for $this->db->update('LOW_PRIORITY table', ...), it will escape the LOW_PRIORITY part. leaving me with update 'LOW_PRIORITY' 'table' OR update mydatabasename.'LOW_PRIORITY'. 
Is this intended? I really don't want to extend the class just for adding an override for this, or change it directly in the framework.
Im using CI 3.1

**Comment by narfbg** [comment]
If it is there, it is intended.

**Comment by jthanto** [comment]
Well, the issue is more that functionality for setting reserved_identifiers is MISSING, as in not even there.

**Comment by narfbg** [comment]
I see where this is going, so I'll cut to the chase ...

There are 2 issues here - that you assumed you should be able to set those reserved identifiers, and that you're doing this to somehow use `LOW_PRIOIRITY` via with the Query Builder.
You should do neither.

`_reserved_identifiers` is and has always been an internal property, an implementation detail. You should've never even tried to access it. The fact that you were able to is because PHP 4 didn't have visibility declarations and thus older CI versions that had to support PHP 4 couldn't restrict it.
Every major naming convention from the PHP 4 era suggests prefixing internal method and property names with an underscore, so that you know they should NOT be used as a part of a public API. I'd be surprised if you don't know this.

Despite this, there is a way to override these values, if you're smart enough to figure it out ... But I'm not giving such tips, especially here - we only accept bug reports here. You may have better luck on our [forums](http://forum.codeigniter.com/), and it would also help if you're more patient than with your [StackOverflow questions](https://stackoverflow.com/questions/40212863/set-speeds-of-mysql-updates-and-inserts-with-codeigniter3) (2 hours since you've posted that).

`LOW_PRIORITY` on the other hand is a MySQL-specific feature and using such features beats the entire point of using a query builder, that is - writing platform-agnostic queries. Your application can only run on MySQL, so QB only adds overhead in your case, you gain less than nothing - only performance penalties and functional limitations.
You're better off without it, and this isn't the first "new" restriction you'll encounter. Just switch to writing raw SQL.

Sorry.

**Comment by jthanto** [comment]
Thanks for cutting the the chase, as I actually got an explaination. And somewhat good tips.
What i don't like is the way you talk to me in parts of your explaination, and attacking me personally.
Thanks for the information though, no need to be hostile.

**Comment by narfbg** [comment]
I get that a lot ... apparently, unless I go out of my way to sugar-coat everything, I'm just an asshole by default.

I can assure you this is not me being hostile and I don't see how could that possibly have been a personal attack, nor why would I want to attack you in the first place.

**Comment by jthanto** [comment]
I don't even know what to reply to this.

**Comment by narfbg** [comment]
No need to really.

Text communication can't transfer emotions in the same way that voice or video would, and I'm just saying you got my intentions wrong. No hard feelings.

**Comment by trymkb** [comment]
Just adding a little to this discussion.

There are numerous identifiers that are not mysql specific that also gets escaped now, this makes the query builder useless for about any query using anything more specific than SELECT/UPDATE/INSERT/WHERE/HAVING

I often use CASE or IF in queries some of these are placed in places like the order by, and would still like to use the query builder for 90% of the other part..
Currently i either need to extend the whole class to set the identifiers, or hack the library to allow me setting this.

To my knowledge the whole point of codeigniter was to make the life of the developer easier, and to provide a toolbox with features, and not force you to use only one specific method.

I understand the reasoning for the escaping, and that you want it to not contain anything DB specific, But i don't understand the reasoning for not allowing us to set the reserved_identifiers or even turn off the escaping for a query on other parts than select, set, where or having.

If we decide to use features that breaks portability for the project we are working on, it does absolutly nothing to break codeigniters support for multiple databases etc. it only allows handling of more specific cases which you might not have orginally planned for.

These queries I am talking about are few and rare in most of our projects, but I still don't understand the reasoning for the answer:

>>You're better off without it, and this isn't the first "new" restriction you'll encounter. Just switch to writing raw SQL.

I understand that LOW_PRIORTY under update/insert is a mysql specific scenario, but CASE and IF in a order by is not.
Both are solved by allowing us to set the reserved_identifiers in some way...

**Comment by narfbg** [comment]
@trymkb 

There's performance implications to doing ORDER BY with dynamic expressions.
And *still*, you can turn off escaping for it. Pretty much everything QB method but `from()` has an `$escape` parameter.

As I already said, the `_reserved_identifiers` property is an **implementation detail**. I might rename or delete it tomorrow, and you shouldn't depend on it; you shouldn't even know that it exists.

**Comment by trymkb** [comment]
Yes know that there is an performance impact by using those in order by, but it is not something you can always avoid (why i state it is rare).

Sorry I went from memory instead of checking the current state of the query builder, and missed that order_by now has the escape option.

**But i also see that update() is still missing this option.**
Adding it there will solve jthanto's issue.

Even though there is a huge difference between allowing one specific command i deem to be safe in a query and allowing everything to pass ..

I would still prefer to have access to the reserved_identifiers or something similar to it.

Thanks for the response :-)

**Comment by Llbe** [comment]
LOW_PRIORITY is not only MySQL specific, it's specific for table-level locking engines. Practically that means MyISAM. You should not be using MyISAM (eg it's not crash safe). Simply use Innodb and forget about LOW_PRIORITY. :-)

This option would only be good for people using the MEMORY engine with a _high_ load and a lot of concurrency.

**Comment by trymkb** [comment]
There are numerous reasons for using MyISAM and as you state the option for using it while running the Memory engine also applies.

MyISAM can handle about 10x the amount of reads using less CPU and Memory than InnoDB can if properly setup.
And writes can be a helluva lot faster also.. depending on the data.

Partitioning works faster with MyISAM and you also lose most of the benefits with InnoDB when using it.
You also have the Merge engine.

There are also custom engines that allows for other commands.

A framework should not take those decisions on behalf of developers.

**Comment by narfbg** [comment]
> A framework should not take those decisions on behalf of developers.

And it doesn't. It's not forcing you to use InnoDB.
What the framework does is to abstract common functionalities.

**Comment by trymkb** [comment]
But you are making a decision by not considering fixing the update function with the escape option, or add some functionality to add your own identifiers to the list.

I can provide the necessary code to fix the identifiers and the update() function, but if this is not going to be accepted just because it conflicts with an opinion then i will not bother doing that.

**Comment by narfbg** [comment]
It's an abstraction for the most common case, that works on all platforms.

You want to shove arbitrary SQL into it and it's not made for that. If you want to write arbitrary SQL, you write raw SQL. How many times do I have to say this before you understand that this is simply how it is supposed to work?

It's not broken, it doesn't need fixing. Period.

**Comment by trymkb** [comment]
This is a narrow-minded way of thinking..

It is broken for me and jthanto, and probably many more people.
And your argument is to not improve anything .. just because you have not experienced this issue or don't care.

I have alot of very complex queries, which i prefer a simpler approach of writing than just raw SQL.. 
In most cases the query builder works out of the box.. and in other i have just hacked the library to fix the missing functionality.

But this is not a good solution, I would prefer that CI itself takes the responsibility of actually having a good query builder with a safe and expandable method of escaping out of the box.

Can you explain why does the insert command have an escape toggle, but not the update?

**Comment by narfbg** [comment]
> This is a narrow-minded way of thinking..

My arguments are consistent and logical.
You're ignoring instead of refuting them, and yet you have the nerve to call *me* narrow-minded.

Is that your strategy to get me to agree with you?

> It is broken for me and jthanto, and probably many more people.

I'll repeat myself yet again: it's not broken. It works exactly as intended.

>And your argument is to not improve anything .. just because you have not experienced this issue or don't care.

No, my argument is to stick to what an abstraction means.
You either don't understand that or just don't like it because it doesn't fit into your coding habits.

> I have alot of very complex queries, which i prefer a simpler approach of writing than just raw SQL..

The goal of using a Query Builder is to know that when you migrate e.g. from MySQL to PostgreSQL tomorrow, you don't have to rewrite your queries.

It's made for portability, not for your very complex queries that will never run on anything but MySQL. No amount of PHP code on top of what always amounts to `query()` call will make your queries simpler.

> In most cases the query builder works out of the box.. and in other i have just hacked the library to fix the missing functionality.

Most cases are the generic SQL that would work on any platform.
You've hacked the library to *break portability constraints*, not to fix it.

Also, if you don't care enough to restrain yourself from monkey-patching upstream code, why are you even here? If you'd hack any upstream library to fit your personal preferences anyway, why do you care at all?

> But this is not a good solution, I would prefer that CI itself takes the responsibility of actually having a good query builder with a safe and expandable method of escaping out of the box.

What you want is called magic. I don't do magic.

> Can you explain why does the insert command have an escape toggle, but not the update?

I don't really remember why it was given to `insert()`, but I sure can tell you why it wasn't such a big deal as it is for `update()`. Consider these 2 signatures from CI2:

```php
    function insert($table = '', $set = NULL)
    function update($table = '', $set = NULL, $where = NULL, $limit = NULL)
```

Obviously, there's room for another parameter in `insert()`.
What I assume is not so obvious is where the would you put an extra parameter in a function that already has 4.

Do we put it at the end and force you to use the others?
Do we put it in the middle and break backwards-compatibility?
At what do we realize that we have parameter creep? (hint: we already have that and you're advocating for making it worse)

I'm not saying it's perfect, but it sure in hell not broken in the sense that you mean it.

And now that I've explained that, do you at least understand that there's other reasons for rejecting your requests other than "we don't want to improve anything"?

**Comment by trymkb** [comment]
First of all, i said it was a narrow-minded way of thinking not calling you narrow-minded.

Second you are assuming that we as developers do not understand that we are choosing to use database specific command and that we are breaking portability (which for many is a non-issue).
There are still alot of database specific commands you can write using the query builder.

But by adding this simple functionality you are in no way harming portability for others or even affecting them at all, you are only adding functionality that allows you to safely escape what you want, where as the current method in the functions that allows escaping is everything or nothing.

I understand adding a parameter to a function already defined is a hassle, but it has been done before. And i don't see the argument that it has 4 or 5 parameters as a valid one.

Adding a function to set/add/remove reserved identifiers is all that is needed, i don't care about update not having an escape option .. i would prefer to be able to safely set what i deem is safe.

I understand your arguments and i don't agree with them.

Though i am glad you responded as this has made my decision to stop using codeigniter after almost 10 years using it and move to another framework alot easier.

**Comment by narfbg** [comment]
> First of all, i said it was a narrow-minded way of thinking not calling you narrow-minded.

This is useless nit-picking, you know that.

> Second you are assuming that we as developers do not understand that we are choosing to use database specific command and that we are breaking portability

I don't assume it, though I do think many don't understand it.

> (which for many is a non-issue)

It's your choice, I don't care about that.
But enabling more choices does impact the framework for others and I do care about that.

> But by adding this simple functionality you are in no way harming portability for others or even affecting them at all, you are only adding functionality that allows you to safely escape what you want, where as the current method in the functions that allows escaping is everything or nothing.

This is simply not true.
Every single feature that we introduce, no matter how small, does affect other users. And that's an argument that comes after we ignore maintenance efforts and a ton of other technical considerations.

> I understand adding a parameter to a function already defined is a hassle, but it has been done before.
> And i don't see the argument that it has 4 or 5 parameters as a valid one.

A lot of things have been done before, that doesn't mean it was a good idea to do them.

This is not just my opinion. People have worked on ways to measure code quality, complexity, maintainability and the more parameters you add, the worse the scores you get.

> Adding a function to set/add/remove reserved identifiers is all that is needed, i don't care about update not having an escape option .. i would prefer to be able to safely set what i deem is safe.

You say "all that is needed", but you really mean is "all that I demand".
Also, I said this in my second comment here:

>> Despite this, there is a way to override these values, if you're smart enough to figure it out ...

> I understand your arguments and i don't agree with them.

Good, so we can agree to disagree then.

> Though i am glad you responded as this has made my decision to stop using codeigniter after almost 10 years using it and move to another framework alot easier.

Or not, because of course - there's no way that you'd accept somebody won't submit to your demands, and if that means you'll have to rewrite your entire application just to move away, so be it.

Honestly, if you think another framework is what you need, by all means go for it. But after you calm down a bit and look at this thread after a week or so, you should be able to see how silly this looks.

**Comment by trymkb** [comment]
>First of all, i said it was a narrow-minded way of thinking not calling you narrow-minded.
>>This is useless nit-picking, you know that.

I am sorry if you feel offended, i did not intend that, for me there is a clear distinction between stating something is a narrow-minded way of thinking and being narrow-minded.

>Or not, because of course - there's no way that you'd accept somebody won't submit to your demands, and if that means you'll have to rewrite your entire application just to move away, so be it.

The reasons i have for changing framework has been numerous over the years.
When i started using CI it was a framework with the goal of keeping things fast and simplifying tasks, Never take huge decision on the behalf of the developer and being a hindrance.
Like not provide an auth lib because there are too many variables to provide a good common solution, this is something I fully support and have no issues with, but is a dealbreaker for alot of developers.

Previously my primary reason for changing framework is because CI has been in maintenance mode the last 3-4 years.

It is not that this single issue is the reason, but the lack of innovation, and the willingness to consider another viewpoint.

I can provide a better version (because apparently i can do magic) which does not break compatibility or portability unless the developer actively chooses to do so, while making the code faster and more secure, but you have flat out denied even considering it.

And what you are calling monkey-patching i call fixing your shit. (this you can be offended by)
I would have liked to take the time to actually contribute, but looking at the history of people trying to provide contributions made me rethink this.

Yes my db driver and query builder would have a few functions which needs to be added to the documentation.
It will also fix a MAX MIN 'hack' and make adaptable to handle scenarios you cant predict, like using custom storage engines in mysql, also fix memory consumption and general speed.

But I have lost all faith in CI now and I rather use my resources on Phalcon.

I will leave with this little note taken from the bullet points on the homepage:
>No restrictive coding rules

>Use your own coding and naming conventions, with only a few caveats that deal with classname conflicts. **CodeIgniter looks to empower you, not shackle you**

**Comment by narfbg** [comment]
> I am sorry if you feel offended, i did not intend that, for me there is a clear distinction between stating something is a narrow-minded way of thinking and being narrow-minded.

Fair enough. Rest assured though, you haven't managed to offend me so far.
Angered because you've continuously *ignored* my argurments as I'm at least trying to give you feedback - sure, but not offended.

> Previously my primary reason for changing framework is because CI has been in maintenance mode the last 3-4 years.
>
> It is not that this single issue is the reason, but the lack of innovation, and the willingness to consider another viewpoint.

That "maintenance mode" and "lack of innovation" resulted in 700+ line changelog for version 3.0.0, and an additional 8 3.x releases after that.

Yes, we're not doing a rewrite every year, but I'm sure you know that's one of the framework's strengths.

> I can provide a better version (because apparently i can do magic) which does not break compatibility or portability unless the developer actively chooses to do so, while making the code faster and more secure, but you have flat out denied even considering it.

We're already the fastest full-stack PHP framework, and one of the few that actually care about performance. No, Phalcon and other *extensions* don't count, because they're not the same thing.
But you'd be able to make it faster, magically and with no trade-offs.

You (and I do mean you personally) have not find a single security flaw within it, but you'll also make it more secure, just as a side effect of adding more functionality.

I'm having a hard time believing this, and I'm pretty sure you wouldn't wonder why. Talk is cheap.

> And what you are calling monkey-patching i call fixing your shit. (this you can be offended by)

"Monkey patching" is a popular term, though I am kind of misusing it.
What you call "fixing" is "adding stuff that you want".

And no, I'm not offended by the word "shit" either, I like to use "foul" language myself.

> I would have liked to take the time to actually contribute, but looking at the history of people trying to provide contributions made me rethink this.

We welcome contributors.
What we don't welcome is self-entitled people who believe that every contribution *must* be accepted.

> Yes my db driver and query builder would have a few functions which needs to be added to the documentation.

Seriously? Are you implying that I reject features because I don't want to *document* them?
FFS, if that was my problem, I'd just make documentation additions a mandatory part of every pull request (as it should be anyway).

> It will also fix a MAX MIN 'hack' and make adaptable to handle scenarios you cant predict, like using custom storage engines in mysql, also fix memory consumption and general speed.

Again, talk is cheap.

> But I have lost all faith in CI now and I rather use my resources on Phalcon.

By all means, go for it.

> I will leave with this little note taken from the bullet points on the homepage:
>
> No restrictive coding rules
>
> Use your own coding and naming conventions, with only a few caveats that deal with classname conflicts. **CodeIgniter looks to empower you, not shackle you**

And this stands at the root of our conflict here. You're equating "shackles" with an optional feature, designed to help with a problem that you don't have, not *catering* to you.
