### ISSUE TITLE
URI Routing two bugs

### ISSUE THREAD

**Issue by Epexa** [bcit-ci/CodeIgniter#4875]
I found two bugs in URI Routing in version 3.1.1, in version 3.1.0 was no such!

**First. If named function same name controller.**
Example:
```php
class Bug extends CI_Controller
{
	
	function bug()
	{
		exit(1);
	}

}
```
Link http://site/bug/bug does not work!

**Second. If add to existing function any URI segment in URL without routes.php not shown error 404.**
Example:
```
http://site/bug/bug/dawdad
http://site/bug/bug/3123
http://site/bug/bug/dawdad/3123/dad/3123/...
```

**Comment by mytharcher** [comment]
Same for my `Index/index`:

```php
class Index extends CI_Controller {
    public function index () {
    }
}
```

When I debug into the source I found in [line 419 of `CodeIgniter.php`](https://github.com/bcit-ci/CodeIgniter/blob/develop/system/core/CodeIgniter.php#L419) there is a `is_callable` check for controller class method:

```php
elseif ( ! is_callable(array($class, $method)))
{
    $e404 = TRUE;
}
```

I am not sure why my index controller class method is not callable?

**Comment by narfbg** [comment]
You did miss something, at least 2 things actually ...

- A `class::method` pair with matching names is a PHP 4 style constructor and there is a [note about it in the documentation](https://codeigniter.com/userguide3/general/controllers.html#reserved-method-names). I don't agree with `is_callable()` returning false for such methods, but that's the reason it does it.
- The `Index` controller name specifically is and has always been a [reserved name](https://codeigniter.com/userguide3/general/reserved_names.html), for that reason and because we use `index()` as the default method to call in a controller.

And I know what you'd say to that: "But it worked in previous versions!"

Well, it may have worked without side effects *if you also had a `__construct()` method*, which overrides the PHP 4 constructor, but the point is - this is a PHP thing that we can't control.

Also, a note to @Epexa: We don't appreciate [double posting](http://forum.codeigniter.com/thread-66492.html).

**Comment by Epexa** [comment]
@narfbg What can you say about second issue "URI segment in URL without routes.php not shown error 404"

**Comment by narfbg** [comment]
Your "second issue" I can't even understand. You're kind of treating this as if it was a forum thread ... which is one of the reasons why we often tell people to write on the actual [forums](http://forum.codeigniter.com/) instead.

For a bug report to be useful, it has to be more detailed, easily understandable and you should take the time to debug it yourself, so that you are 100% sure it is a bug.

Also, please note that not every problem that you experience is a bug, but if you do have multiple ones - you should report them separately.

**Comment by Epexa** [comment]
@narfbg Ok, see https://github.com/bcit-ci/CodeIgniter/issues/4882 !
