### ISSUE TITLE
ip_address() on AWS and Load Balancer

### ISSUE THREAD

**Issue by gorankrgovic** [bcit-ci/CodeIgniter#4944]
I don't know why and this is really a weird behavior, but when you want to fetch the user IP address with $this->input->ip_address() it gives you the VPC ip address instead of the user! Tried on multiple instances and it's always the same behavior. Tried with custom function like:

```
public function get_client_ip() {
        $ipaddress = '';
        if (getenv('HTTP_CLIENT_IP'))
            $ipaddress = getenv('HTTP_CLIENT_IP');
        else if(getenv('HTTP_X_FORWARDED_FOR'))
            $ipaddress = getenv('HTTP_X_FORWARDED_FOR');
        else if(getenv('HTTP_X_FORWARDED'))
            $ipaddress = getenv('HTTP_X_FORWARDED');
        else if(getenv('HTTP_FORWARDED_FOR'))
            $ipaddress = getenv('HTTP_FORWARDED_FOR');
        else if(getenv('HTTP_FORWARDED'))
            $ipaddress = getenv('HTTP_FORWARDED');
        else if(getenv('REMOTE_ADDR'))
            $ipaddress = getenv('REMOTE_ADDR');
        else
            $ipaddress = 'UNKNOWN';
        return $ipaddress;
    }
```

Which gives me the correct ip address of the USER. 

On ubuntu 16.04. PHP 7.0, latest codeigniter framework

**Comment by emilebourquin** [comment]
This really isn't CodeIgniter's fault, it's more due to how EC2/VPC is set up.

I got around this issue by using mod_remotip .

In /etc/httpd/conf.d , I created a file named mod_remoteip.conf .

In that file, I placed:

RemoteIPHeader X-Forwarded-For

#ELB us-west-1a Subnet
RemoteIPTrustedProxy XXX.XX.XX.X/20

#ELB us-west-1c Subnet
RemoteIPTrustedProxy YYY.YY.YY.Y/20


where XXX.XX.XX.X/20 is the CIDR block of my ELB VPC Subnet in us-west-1a and YYY.YY.YY.Y/20 is the CIDR block of my ELB VPC Subnet in us-west-1c .

Or, more basically, put the address you are getting from your call to $this->input->ip_address() into the RemoteTrustedProxy line. Do an apachectl restart, and now calls to $this->input->ip_address() return the user's IP address.

This accomplishes the same thing your function does (The ELB passes the user's IP address in X-Forwarded-For), but does it at the Apache HTTPD level, rather than making CodeIgniter changes. It has the added bonus effect of making any PHP call to get an IP address of the user work properly.

**Comment by narfbg** [comment]
@emilebourquin We have that feature built-in ...

@gorankrgovic 

The code you've shown allows *any* user to spoof their address. As I already said - we have a feature for your use case, you should use that to be safe.

However, this is a bug tracker and we don't provide general support here.
If you need help with something, please post on our [forums](https://forum.codeigniter.com/) instead.
