### ISSUE TITLE
image_lib -> resize not working for some image

### ISSUE THREAD

**Issue by hendrawd** [bcit-ci/CodeIgniter#4967]
Selfie images from Samsung phones is not working.
`$this->image_lib->resize();` will always return false and the image will not saved to directory

Here is the config
```
$config['source_image'] = FCPATH . 'images/pics/' . $file_name;
$config['new_image'] = FCPATH . 'images/pics/prev/';
$config['maintain_ratio'] = TRUE;
$config['width'] = 480;
$config['height'] = 480;
```

Here how i use image_lib
```
$this->image_lib->initialize($config);
$this->image_lib->resize();
$this->image_lib->clear();
```
I am using autoload to load the library.

This problem might be related with https://bugs.php.net/bug.php?id=72404
and https://github.com/libgd/libgd/issues/206
You can get the sample image [here](http://beta.opajaap.nl/wp-content/uploads/wppa-source/14659120613561390699243.jpg)

**Comment by narfbg** [comment]
Well, both links suggest that this only happens with incorrectly-formatted (i.e. broken) JPEGs, so ...

What are you suggesting? And if you've followed the discussions you've linked, did you try any of the work-arounds mentioned? If so, what results did you get?

**Comment by hendrawd** [comment]
@narfbg I already tried the suggestion from the discussion, but it's only for disable the warning, image resize still failed.

**Comment by narfbg** [comment]
Yes, I'd guess the resize would still fail with our current code regardless of the warning being disabled.

What I meant by asking if you've tried the work-around**s** (plural) isn't just if you've tried switching a single INI option, but if you've further debugged this.

This comment from https://bugs.php.net/bug.php?id=72404 gives a lot of hints:

> Setting gd.jpeg_ignore_warning=1 in php.ini solved the problem
that the JPEG couldn't be read. Please verify this[1].
>
> If that works, you'll find that the image is bottom up when read
by GD. That is because the image data are stored that way, and the
Exif Orientation flag is supposed to signal a reader that the
image has to rotated by 180° (its value is 3[2][3]). However, GD
is not supposed to regard Exif data, so you'd have to rotate the
image yourself if necessary.
>
> [1] <http://php.net/manual/en/image.configuration.php#ini.image.jpeg-ignore-warning>
> [2] <http://php.net/manual/en/function.exif-read-data.php>
> [3] <http://sylvana.net/jpegcrop/exif_orientation.html>

It says that enabling `gd.jpeg_ignore_warning` not only hides the warning, but *allows the image to be read*, meaning that after enabling it - our process probably fails somewhere else now.
And that may be fixed if we read the EXIF data and rotate the image prior to resizing it.

Have you tried any of that? Even if just with your own raw PHP code, have you tried to make it work somehow?

**Comment by vlakoff** [comment]
I've got my new wallpaper for 2017.

**Comment by hendrawd** [comment]
@narfbg i do rotate the image after upload success

This is the library that i use for rotating image
```
function __construct($params = NULL)
{
    if (!is_array($params) || empty($params)) return FALSE;

    $file_path = $params['filepath'];
    $exif = @exif_read_data($file_path);

    if (empty($exif['Orientation'])) return FALSE;

    $CI =& get_instance();
    $CI->load->library('image_lib');

    $config['image_library'] = 'gd2';
    $config['source_image'] = $file_path;

    $orientations = array();

    switch ($exif['Orientation']) {
        case 1: // no need to perform any changes
            break;

        case 2: // horizontal flip
            $orientations[] = 'hor';
            break;

        case 3: // 180 rotate left
            $orientations[] = '180';
            break;

        case 4: // vertical flip
            $orientations[] = 'ver';
            break;

        case 5: // vertical flip + 90 rotate right
            $orientations[] = 'ver';
            $orientations[] = '270';
            break;

        case 6: // 90 rotate right
            $orientations[] = '270';
            break;

        case 7: // horizontal flip + 90 rotate right
            $orientations[] = 'hor';
            $orientations[] = '270';
            break;

        case 8: // 90 rotate left
            $orientations[] = '90';
            break;

        default:
            break;
    }

    foreach ($orientations as $orientation) {
        $config['rotation_angle'] = $orientation;
        $CI->image_lib->initialize($config);
        $CI->image_lib->rotate();
    }
}
```

**Comment by narfbg** [comment]
FYI, simply disabling the warning makes it work for me.

**Comment by hendrawd** [comment]
@narfbg ok i will re-check again next few days. Have a nice weekend :)

**Comment by hendrawd** [comment]
@narfbg Ok, i checked again and it works. Thank you for your help.
If anyone has the same problem, you can open your php.ini file, and search for 
`gd.jpeg_ignore_warning`, set the value to 1. Don't forget to remove the comment syntax at the first of the row. In my case, the default was
```ini
; gd.jpeg_ignore_warning = 0
```
And i changed it to
```ini
gd.jpeg_ignore_warning = 1
```
After that restart your server
```bash
sudo apachectl restart
```

**Comment by narfbg** [comment]
Please note that this is a bug tracker. It's not a place to share "solutions" and we don't close issues as soon as you have a work-around for yourself ... we have a [forum board](https://forum.codeigniter.com] for that.

Technically this isn't a bug, as we've determined that it's caused by improperly formatted JPEGs, but we'll still apply the solution as a patch against our code, for the benefit of all.
