### ISSUE TITLE
oci_bind_by_name() call has no error handling

### ISSUE THREAD

**Issue by zploskey** [bcit-ci/CodeIgniter#5030]
In the Oracle driver, the call to `oci_bind_by_name()` in `_bind_params()` does not handle the return value: https://github.com/bcit-ci/CodeIgniter/blob/master/system/database/drivers/oci8/oci8_driver.php#L376.

This function return false on failure and true otherwise. See https://github.com/bcit-ci/CodeIgniter/pull/5029#issuecomment-281405781.

**Comment by narfbg** [comment]
Why is that a problem, and how do you expect it to be handled?

**Comment by zploskey** [comment]
Currently it appears that these calls may fail silently. It might be preferable to indicate which parameter failed to bind, maybe in a warning/log message that only appears in development. Presumably a bind failure would typically cause an error when the query executes. Handling failure of `oci_bind_by_name` would help the developer catch errors even if the stored procedure is not called.

**Comment by narfbg** [comment]
If the query fails when the build fails, there will be a query failure, so how would that be silent? :)

Joking aside, I reckon there's a *lot* of other function calls that we don't do error handling for, but that's not because we forgot to do that ... it's because we can't have half of our code being error handling alone.
And so, if the only reason you've opened this issue is that you saw a function call without its return value checked for, you could probably open another 100 similar issues, while nobody would actually experience those 100 problems.

I guess what I'm saying is - if you *know* that this is a problem, please suggest a more specific solution to it. Otherwise this issue will just sit here forever. :/

**Comment by zploskey** [comment]
Point well taken. Some Oracle drivers do handle this potential error, but given that this function is only called in `stored_procedure()`, which then calls `query()`, I don't think there is ever a context where parameters are bound but the query is not immediately executed. So it appears is not necessary to handle the return value in this case. If the DB driver is ever modified to provide a way for create a stored procedure but not immediately run it then it might be worth further consideration.
