### ISSUE TITLE
Some minor bugs in Postgres Driver (invalid reference to 'key' attribute)

### ISSUE THREAD

**Issue by tsergeant** [bcit-ci/CodeIgniter#5057]
I was actually going to issue a pull request but am not quite sure how to make that happen. So far I've cloned the repository, made suggested bug fixes in a new branch and committed the branch (locally). I'm not sure what to do after that.

Anyway, the issue is with the postgres driver (system/database/drivers/postgre/postgre_driver.php) which errors if using a connection string (with extra options) to connect to the database. When cycling over the options there are several references to $this->key that should read $this->$key.

Also, a fairly common option (sslrootcert) is missing from the list.

**Comment by zploskey** [comment]
To submit a pull request, press the "Fork" button in the upper right corner. You'll need to add your copy as a remote in your existing clone by doing something like `git remote add github https://github.com/tsergeant/CodeIgniter.git`. While on your branch with your patch, run `git push github`. This will push the branch to your fork on Github. There should then be a link to compare and submit a pull request on your fork's page.

I see what you're saying about the use of `$this->key` instead of `$this->$key` here:
https://github.com/bcit-ci/CodeIgniter/blob/develop/system/database/drivers/postgre/postgre_driver.php#L133

The comment on that block suggests that this code not very often used.

**Comment by narfbg** [comment]
Pushed bugfix patch, linked above.

As for options such as 'sslrootcert' ... At least that one isn't described on the php.net manual, as far as I can see, so that's why it's missing - we just don't know about it.  
Specifically for SSL settings, we already have made some available for MySQL and I'd rather reuse the same keys, as they're described in the config file. Please open a new issue/PR about that and I'd be happy to work with you on that.

Also, we do have a contribution guide: https://github.com/bcit-ci/CodeIgniter/blob/develop/contributing.md
