### ISSUE TITLE
Package bcit-ci/codeigniter is abandoned, you should avoid using it. Use codeigniter/framework instead.

### ISSUE THREAD

**Issue by salmanaligeek** [bcit-ci/CodeIgniter#5068]
I tried to install CodeIgniter through composer using this:
`composer require bcit-ci/CodeIgniter`
And it installed successfully I got a warning, see screenshot http://imgur.com/HiOiff0

And then I tried to install with this:
`composer require codeigniter/framework` 
and I got a fatal error, see screenshot here http://imgur.com/HZjlBGM

I don't know what I am doing wrong.

See all screenshots here http://imgur.com/a/zsnER

**Comment by narfbg** [comment]
`bcit-ci/codeigniter` was NEVER an official CI package on Packagist - some random user had created it, and the maintainers gave it to us after we noticed it.  
That being said, if `bcit-ci/codeigniter` works - then `codeigniter/framework` almost by definition cannot be broken, as the former is an alias for the latter. If you have problems with either, it's almost certainly something you did.

That's about all I can say about this. Whatever the issue is that you're having, it is certainly not a CodeIgniter bug and we only deal with bug reports here.  
For anything else, please post your questions on our [forums](https://forum.codeigniter.com/) instead.
