### ISSUE TITLE
CI dose not seemingly support Mariadb.

### ISSUE THREAD

**Issue by skiingwang** [bcit-ci/CodeIgniter#5096]
Dose the CI 3 framework not connect the mariadb and have no it's driver?

**Comment by narfbg** [comment]
No offense, but if you knew what MariaDB is, you'd already know the answer.

Please do at least basic research, and ask your questions on our [forums](https://forum.codeigniter.com/) instead; this is a bug tracker.

**Comment by skiingwang** [comment]
I certainly know it's one branch of mysql. I try to list the records but show the error info: Message: 

Call to undefined function mysql_connect()
Filename: C:\xampp\htdocs\ci\system\database\drivers\mysql\mysql_driver.php

**Comment by inieves** [comment]
I think what @narfbg  is referring to is that MariaDB is supposed to be a drop-in replacement for MySQL.  I interpret that to mean (and maybe others also) that it should be possible to use MariaDB in any/all situations where MySQL can be used, without having to change configuration/settings/drivers/etc.  I do not know if that is true in practice.

**Comment by narfbg** [comment]
That's exactly what I meant and it is 100% true.

A MariaDB driver doesn't exist anywhere, not in a framework, not as a PHP extension. The error message itself says that a **mysql_** function doesn't exist, so it is completely illogical to think that this has anything to do with MariaDB in particular.

OP tried to use ext/mysql, which would work, but didn't have it installed - a very basic issue. Now, I know a newbie who encounters a particular issue for the first time probably won't recognize it, but all one has to do is to literally copy-paste the error message into the search box and read through the first result or two.  
It takes way more effort to find this repository and open an issue, and it's only a waste of everybody's time, so it's quite annoying when that happens.

**Comment by inieves** [comment]
Im sorry, but you did 1) not say what you mean and 2) actually did not say anything similar.  You phrased your response as the insult: "No offense, but if you knew what MariaDB is, you'd already know the answer."

Further, just because MariaDB is _trying_ to be a drop-in replacement for MySQL _does_not_guarantee_ that they have achieved that outcome.

Ahem... who are you calling a newbie?

**Comment by narfbg** [comment]
> Im sorry, but you did 1) not say what you mean and 2) actually did not say anything similar.

You said you think you know what I was referring to and I confirmed that in 1 sentence. The rest was clarification.
Are you complaining that I confirmed your thoughts or that 17 months ago I didn't give an extensive answer to a completely irrational question asked in the wrong place? I don't get it.

>  You phrased your response as the insult: "No offense, but if you knew what MariaDB is, you'd already know the answer."

No, you perceive it as an insult because you take pride in your knowledge and unlike the OP at the time, you actually know that it takes nothing special to use MariaDB in place of MySQL.
Perhaps it was passive-aggresive, I'll give you that, but it was my way of saying you need to help yourself first before wasting somebody else's time. I stand by it and you know I'm right.

> Further, just because MariaDB is *trying* to be a drop-in replacement for MySQL *does_not_guarantee* that they have achieved that outcome. If you think really hard about precisely what it means to be a drop-in replacement for a piece of software, which is itself constantly changing, then you realize that there is always the possibility for *not* feature parity.

Yea, if you think really hard about how to start an argument over nothing, you come up with that.

Of course there are subtle differences between MySQL and MariaDB. Of course I know this and it would be stupid to think otherwise, as there wouldn't be a reason for the two to exist. If you thought my first comment was an insult, this is way more insulting by the same token.
But the context here (the single most important thing in every debate, I would say) is how to use both databases through PHP. And in that context they are 100% the same.

> Ahem... who are you calling a newbie?

That wasn't directed at anybody in particular, though I hope the OP was a newbie at the time, as the alternative explanation for his actions would be quite bad. And I see you think that's an insult too ... it's not; everyone's a newbie at some point and there's no shame in that.

It also looks like you thought I was talking about you and I see zero reason for that ... Are you one of those people who look for a reason to be offended at everything? If so, here's some friendly advice - stop thinking that everyone's out to get you and you'll be much happier.

**Comment by ssergio100** [comment]
> > Desculpe, mas você 1) não disse o que quis dizer e 2) realmente não disse nada parecido.
> 
> Você disse que sabe o que eu estava me referindo e eu confirmei isso em 1 frase. O resto foi esclarecimento.
> Você está reclamando que eu confirmei seus pensamentos ou que há 17 meses não dei uma resposta extensa a uma pergunta completamente irracional feita no lugar errado? Eu não entendo.
> 
> > Você formulou sua resposta como um insulto: "Sem ofensa, mas se você soubesse o que é MariaDB, você já saberia a resposta".
> 
> Não, você o considera um insulto porque se orgulha de seu conhecimento e, diferentemente do OP da época, você realmente sabe que não é preciso nada de especial para usar o MariaDB no lugar do MySQL.
> Talvez tenha sido passivo-agressivo, vou lhe dar isso, mas era a minha maneira de dizer que você precisa se ajudar primeiro antes de desperdiçar o tempo de outra pessoa. Eu apoio e você sabe que estou certo.
> 
> > Além disso, apenas porque o MariaDB está _tentando_ ser um substituto para o MySQL não _garante_ que eles alcançaram esse resultado. Se você pensar muito sobre exatamente o que significa ser um substituto para um pedaço de software, que está constantemente mudando, perceberá que sempre há a possibilidade de _não_ haver paridade de recursos.
> 
> Sim, se você pensa muito sobre como iniciar uma discussão sobre nada, você propõe isso.
> 
> Claro que existem diferenças sutis entre o MySQL e o MariaDB. É claro que eu sei disso e seria estúpido pensar o contrário, pois não haveria uma razão para os dois existirem. Se você pensou que meu primeiro comentário foi um insulto, isso é muito mais ofensivo pelo mesmo motivo.
> Mas o contexto aqui (a coisa mais importante em todos os debates, eu diria) é como usar os dois bancos de dados através do PHP. E nesse contexto, eles são 100% iguais.
> 
> > Ahem ... quem você está chamando de novato?
> 
> Isso não foi direcionado a ninguém em particular, embora eu espere que o OP seja um novato na época, pois a explicação alternativa para suas ações seria muito ruim. E vejo que você acha que isso é um insulto também ... não é; todo mundo é novato em algum momento e não há vergonha nisso.
> 
> Também parece que você pensou que eu estava falando sobre você e não vejo razão para isso ... Você é uma daquelas pessoas que procuram um motivo para se ofender com tudo? Nesse caso, eis alguns conselhos amigáveis ​​- pare de pensar que todo mundo quer te pegar e você ficará muito mais feliz.

Quem não faz sexo não deveria tentar ajudar outras pessoas.
