### ISSUE TITLE
Only variables should be passed by reference /system/codeigniter/Common.php

### ISSUE THREAD

**Issue by alexmason528** [bcit-ci/CodeIgniter#5224]
I have upgrade php version to 7.0.22 and this error happens.

**Comment by gxgpet** [comment]
Tell us which at which line of Common.php is this happening and what CI version are you using.

**Comment by devravi** [comment]
I was upgrading codeigniter application from 2.1.x to 3.1.6,
I'm receiving same error on line number: 257.
My Php version is 5.6

**Comment by zploskey** [comment]
You need to replace your system folder. This file has been moved to system/core/Common.php, so you must be using an old version. Follow the upgrading section in the user guide.

**Comment by u01jmg3** [comment]
`$objects[$class] =& instantiate_class(new $name());`

Is the same as writing:

`$objects[$class] =& new $name();`

Which is the way that it needed to be written to glue PHP 4 with PHP 5.3 code because it prevented strict standard warnings in PHP 5.3.

Now this can be written as:

`$objects[$class] = new $name();`

---

https://stackoverflow.com/questions/7653709/codeigniter-instantiate-class-function#answer-7653853

**Comment by narfbg** [comment]
`instantiate_class()` hasn't existed in CI since version 2.0.0 ... We're at 3.1.10 now.

In case it wasn't clear when I closed the issue, @zploskey answered it appropriately - if you get this error, it means you've screwed up an update.
