### ISSUE TITLE
Upload class file_size error

### ISSUE THREAD

**Issue by fattalgazi** [bcit-ci/CodeIgniter#5247]
Hello,

In that line : https://github.com/bcit-ci/CodeIgniter/blob/fced25f5728ce81fe810216fcaa4ccec7523f6c9/system/libraries/Upload.php#L496

You just convert bytes to kilobytes.  But if the uploaded file's size is lower than 6 byte, round(5/1024, 2); will equal to 0.

**Comment by narfbg** [comment]
How is that an issue?

**Comment by fattalgazi** [comment]
Because, after user uploading a file, I check file_size attribute, if it equals to "0", we return an error that says "You uploaded an empty file, please fix it."

**Comment by narfbg** [comment]
Does CI check it? If not, then it's a logical flaw in your code - you know the output is in kylobytes, and 5 bytes are nowhere near a kilobyte.

And in fact, a 5-byte file could be an empty file depending on your definition ... A lot of text editors will append, without rendering, an empty line to the end of all files (typically on UNIX-based systems). If you have BOM enabled and configured your line endings to be `\r\n`, that makes 3 (BOM) + 2 (LE) = 5 bytes total, for an otherwise empty-content file.
Of course, `CI_Upload` wasn't designed with this in mind. It's just such a hilarious coincidence that I just had to mention it. :D

On a more serious note: Why would you ever want to upload and/or accept a 1-5 byte file upload. That's what regular, text input fields are for.

**Comment by fattalgazi** [comment]
There is a textarea in our iOS application for creating NOTES.  User can type anything he/she wants. We just send the text with "multipart/form-data" method. I noticed this situation when someone just tried to send "Hi" text to our backend. Because it is only 2 bytes, but "0" for CI :( 

I fixed the situation by file_get_contents of the file if CI says it is 0 file_size.

**Comment by narfbg** [comment]
That's probably the weirdest thing to use `CI_Upload` for, ever. :)

Sorry, but we can't do anything about it.

**Comment by fattalgazi** [comment]
Sorry, but why is it weirdest? I send another things while uploading , not just text but also picked image. "Image" and "Your note" fields together. You need to be calm down! Thx.

**Comment by narfbg** [comment]
Calm down? I wasn't anxious, angry, or in any other way non-calm. I wasn't even criticizing you by saying it's weird; in fact, I was rather amused (see that smiley face there? that's what it represents).

It is weird for 2 reasons:

1. I would guess an iOS app would interact with a rigid HTTP API, which CI is not suited for.
2. You don't need all of your multipart/form-data to be represented as file attachments.

*Now*, that you are telling me what I supposedly need to do, I'm quite annoyed with you.

**Comment by fattalgazi** [comment]
Ok, I already fixed the situation , all I wanted is notifying you this CI behaviour. Thank you.
