### ISSUE TITLE
CI and Suhosin incompatibility

### ISSUE THREAD

**Issue by objecttothis** [bcit-ci/CodeIgniter#5248]
If php.ini contains `suhosin.cookie.encrypt = On` then CSRF will fail.  There are two ways to resolve this.  Either comment that line out (unsafe) or add the line `suhosin.cookie.plainlist = [insert config.php cookie name here]` (safe)

This should be added to a FAQ, wiki or troubleshooting guide as anyone with suhosin running is liable to run into this and `suhosin.simulation = On` does not make the problem go away and suhosin doesn't log it because it's not technically suhosin blocking anything which makes the problem difficult to track down.

**Comment by narfbg** [comment]
Given Suhosin's [status](https://en.wikipedia.org/wiki/Suhosin#Development_History), this is not an issue for us.

Also, this is false speculation:

> Either comment that line out (unsafe) or add the line `suhosin.cookie.plainlist = [insert config.php cookie name here]` (safe)

While encrypting a cookie can improve security, that is what is called "hardening", which is mostly what Suhosin is about - making a strong system even stronger, generally speaking. Lack of hardening does not mean a system is unsafe.

And more importantly, if you actually need your cookies to be encrypted, that alone would be the real problem. Data needs to be encrypted if it is a secret, and it is a major flaw to store secret data in cookies.

**Comment by objecttothis** [comment]
@narfbg You misunderstand what I mean by safe or unsafe.  Safe meaning that other cookies still get encrypted and you just whitelist the one(s) you don't want encrypted.  Unsafe is meant to indicate that it will resolve the problem but if you were relying on encrypted cookies, you won't get them.  I did not intend to imply that the system is no longer secure.  

I think you are also making an assumption about encrypting cookies that is a non-sequitur. Yes, I agree that it is bad practice to store secret data in cookies, however encrypting cookies isn't therefore a moot point.  Encrypting them reduces the footprint of just one more attack vector.

I'm not suggesting changing the implementation of CI to accomodate this, but merely suggesting that you post the incompatibility somewhere so that anyone else with this suhosin directive will know to disable it.  Whether the project is dead or not, is not relevant as people still use it in CI supported PHP versions (i.e., PHP 5.6 for CI 3.1.5), so others are potentially going to run into it.

**Comment by narfbg** [comment]
> Unsafe is meant to indicate that it will resolve the problem but if you were relying on encrypted cookies, you won't get them. I did not intend to imply that the system is no longer secure.

Every library, framework, etc. comes with a set of assumptions and trade-offs. This is one of the cases where you will find unanimous agreement that you shouldn't ever rely on such a thing.

> I think you are also making an assumption about encrypting cookies that is a non-sequitur. Yes, I agree that it is bad practice to store secret data in cookies, however encrypting cookies isn't therefore a moot point. Encrypting them reduces the footprint of just one more attack vector.

A non-sequitur is an erroneous argument. If you agree with my argument, then it is by definition not a non-sequitur.
But even further on that - I'm not saying storing secret data in cookies is merely a bad practice. There are a lot of "bad" practices, that when applied to valid use cases, are quite good. We call them "bad practices" because they are commonly used for the wrong purpose and/or lead to bigger problems.

What I'm saying here is that storing secret data in cookies is *inherently* bad, no matter what. It is insecure when not encrypted, but also otherwise problematic even when encrypted (e.g. concurrency issues with server-less sessions we had in CI2). I will tell you what is wrong with literally every use case you can come up with.

> I'm not suggesting changing the implementation of CI to accomodate this, but merely suggesting that you post the incompatibility somewhere so that anyone else with this suhosin directive will know to disable it.

Fair enough.

However, we don't have a specific place for this. And to be honest, an esoteric issue with a dead third-party project is the last thing I'd care to put on a FAQ. :)

There is a Wiki we have here on GitHub, but while I do delete junk from it when I see it, it is otherwise exclusively user-maintained and you are more than welcome to edit it.
Otherwise, annoying that I have to deal with this on a bug tracker, and I ask you not to do that in the future, but you have achieved what you wanted - anybody googling for the problem will find this very discussion. We do also have a [forum board](https://forum.codeigniter.com/), which has historically always been where CI users go in search of solutions.

> Whether  the project is dead or not, is not relevant as people still use it in  CI supported PHP versions (i.e., PHP 5.6 for CI 3.1.5), so others are  potentially going to run into it.

Disagree. Conscious efforts to maintain compatibility with defunct projects only slow down progress, and is one of the major reasons why CI lost enormous amounts of popularity.
At least when we did that, we did it because older PHP versions still had the majority market share. That is not the case with Suhosin. :)

**Comment by objecttothis** [comment]
@narfbg non-sequitur is Latin and it means does not follow. it's used to indicate when your answer does not follow from your argument. I was never trying to argue that one should store secret data in cookies and you seemed to have missed that point. There is nothing wrong with encrypting non-secret data in cookies... especially if an attacker wastes a bunch of time trying to crack it. nonetheless, it sounds like this conversation has run its course so I will leave it at that.
