### ISSUE TITLE
File does not upload if it finds some specific words in the file

### ISSUE THREAD

**Issue by imranabdurrahim** [bcit-ci/CodeIgniter#5256]
```
$config['upload_path'] = './uploads/';
$config['allowed_types'] = 'txt';
$config['max_size'] = '10000';
$this->load->library('upload', $config);
if(!$this->upload->do_upload('datafile')){
    print_r($this->upload->display_errors());  
}else{
      // rest of work
 }
```

Everything is ok but when it try to upload a text file containing char starting new line ( example: charlie@mail.com ), it shows this error: The filetype you are attempting to upload is not allowed.

Same thing happen with image file too by adding 'char' word inside of image file.
Note: I have found only 'char' word, but i strongly believe there are some more words which also conflict. 

But with 

> var_dump($_FILES);

 it shows that it is correct mime type file.

when it gets global file type setting:

> $config['allowed_types'] = '*'; 

It works.

> Codeigniter version 3.1.5

Note2:  The problem dose not occur in older version like 2+, but only with version of 3+

**Comment by Tpojka** [comment]
I can confirm the same. I am using virtual vagrant Ubuntu 16.04 environment. If I put content of `char` in example file and try to upload it, I will be refused by app. I also tried with content of file like `#!/bin/bash` - it was refused from uploading also. Could it be Linux thing?

**Comment by imranabdurrahim** [comment]
Good finding. It's not only with text but also with image file too. I mean editing inside of img file with "char" word. But strange matter is excel file is ok with it. So if it would be a linux problem i think all types of uploading would be blocked. Moreover, There is no problem with older version. So i think it is problem within CI

**Comment by narfbg** [comment]
$ echo 'char' > test.txt 
    $ file --brief --mime test.txt 
    text/x-c; charset=us-ascii

`text/x-c` corresponds to C source code files, and since `char` is a C data type, I guess that makes some sense.

But unfortunately, this is outside of CodeIgniter's control - it simply uses whatever mime-detection is available on the OS. If you find false-positives like this, you can just add them to your *application/config/mimes.php* to work around that.

**Comment by Tpojka** [comment]
Thank you for response. Just was unsure since plain PHP upload code inside controller worked fine. 
Plain PHP upload code inside CodeIgniter controller works as expected while CI upload library doesn't. And that in case mime type is not changed. 
Secondly, I am not sure why content would be checked at all.

**Comment by narfbg** [comment]
I don't know what you mean by "plain PHP upload code", but if it doesn't check the file contents - it cannot actually verify the filetype, and thus any type-related restrictions are meaningless.

**Comment by Tpojka** [comment]
If I don't use CodeIgniter `Upload` library and make upload with basic PHP functions/code for file upload, everything went well - same file is being uploaded.

**Comment by narfbg** [comment]
That literally doesn't say anything but "something else works".

**Comment by Tpojka** [comment]
I am not sure. I would just like to know why CI upload library can't be used fairly when uploaded file contains `char` text. You were right for that above:

    tpojka@mbp:~ >_ file --brief --mime ~/Desktop/testFile.txt 
    text/x-c; charset=us-ascii
    tpojka@mbp:~ >_

Again, same file can be uploaded when [example code](http://php.net/manual/en/features.file-upload.post-method.php#example-384) is used. 
I am trying to understand that though.

**Comment by narfbg** [comment]
Well, the example code you listed doesn't do any kind of checks. And I already answered the rest:

> if it doesn't check the file contents - it cannot actually verify the filetype, and thus any type-related restrictions are meaningless

**Comment by Tpojka** [comment]
Which brings us back to initial question: why this is happening in CI and in what line of code of CI C jumps in. Beside that 
>If you find false-positives like this, you can just add them to your application/config/mimes.php to work around that.

this solves requirement although doesn't seem to be most secure way.
I followed issue and found [these](https://bugs.php.net/bug.php?id=53035) [two](https://github.com/Microsoft/moodle-local_o365/issues/3) pages where issue is mentioned but I couldn't see explanation per se.
@imranabdurrahim You have two ways: to update mime types array with `text/x-c` or to use native PHP upload code.

**Comment by narfbg** [comment]
What do you mean why? A type check was declared a type check is being done - that's why.

**Comment by Tpojka** [comment]
@narfbg Clear now. Thanks.

**Comment by imranabdurrahim** [comment]
I have confirmed that with 'double' and 'float' it behaves the same. As those are also C variable. 

@narfbg 
You missed the note:

> Note2: The problem dose not occur in older version like 2+, but only with version of 3+

The problem is happening with newer version. Old version is fine. 
So i have looked to mime type of both versions and found in older version it includes text/x-c mime type 

> 'txt'	=>	array('text/plain', 'text/x-c'),

but in newer version it removed. 
`

> 'txt'	=>	'text/plain',

I think it is not a problem to include this again in newer version as it is not a security risk in case of .txt extension. 

`

**Comment by narfbg** [comment]
No, I did not miss anything. In fact, if anyone "missed" something, it is you by talking about "older version like 2+".

It is true that you wouldn't encounter this in *some* 2.x versions, but those are only 2.0.0-2.0.3, which didn't have server-side type detection at all. This feature was introduced in 2.1.0 and was one of my first contributions to the project ... there is literally nothing related to it that you could surprise me with.

I don't know which version you have looked at, but **no** CI version tracked here on GitHub (all since 2.0.3) includes 'text/x-c' as a valid type for 'txt'. And it makes zero sense that this would've ever been the case prior to that, so ... I believe you're mixing something up here.

Either way, regardless of the fact that it comes with contents in it, *application/config/mimes.php* is a **configuration** file and that is very much by design. We cannot possibly track all mime types, or all false-positives like this one here. If you need something in there - just add it.

**Comment by imranabdurrahim** [comment]
My mistake. 
Yes, it was always `'txt' => 'text/plain',`  since 2.0.3 

I am still confused about this behavior. Though it is not CL issue i got. 

And thanks for your server-side type detection contribution.
