### ISSUE TITLE
show_404 not working if URI has query string and enable_query_strings is FALSE

### ISSUE THREAD

**Issue by td234** [bcit-ci/CodeIgniter#5275]
Using CI 3.1.5
I am using the config->allow_get_array to pass page numbers to my controller. If a page is out of range, I want to return a 404 using show_404(). This is returning a blank page. I have discovered that it seems to fail on Exceptions.php around line 181 on ob_start(). It works fine for URIs without the query string, but add the query string and it returns a blank page.

**Comment by narfbg** [comment]
*allow_get_array* is a boolean that defaults to TRUE, and is deprecated because the only thing it does is to remove `$_GET` if you set it to FALSE ... useless.

Nothing to do with `show_404()`. Whatever issue it is that you're having, please post about it on our [forums](https://forum.codeigniter.com/).

**Comment by td234** [comment]
Hi. thanks for the replay. I have continued to investigate this and show_error is failing on ob_start() when there is a "?" in the URI. Works fine if not "?". 

I agree this has nothing to do with allow_get_array, but wanted to explain any settings that I had set. 

I have found that if I force ob_end_flush() before the ob_start() on line 182, then I get the error template, but get_instance() does not work on that temp-late. 

Should be a way to show an error on a URI with a "?".
