### ISSUE TITLE
Bug: custom config values with 'enable_hooks = true' not properly initialize hooks 

### ISSUE THREAD

**Issue by JaydenLiang** [bcit-ci/CodeIgniter#5323]
### This bug is about overriding the default value of ‘enable_hooks’ in the config using the $assign_to_config provided in public/index.php.

- In public/index.php, line 167, it says the $assign_to_config variable is used to override the default config values. 
_*Note: See the 'CUSTOM CONFIG VALUES' section in public/index.php_

- To reproduce the bug, assume that a user wants to override the ‘enable_hooks’ default config by adding this line of code in public/index.php:
`$assign_to_config['enable_hooks'] = true;`
The bug arises, because:

1. Look into system/core/CodeIgniter.php:
    1. Starting from line 219, the config class is loaded in system/core/CodeIgniter.php, and $assign_to_config is passed to override right after.
	`$CFG =& load_class('Config', 'core');
	// Do we have any manually set config items in the index.php file?
	if (isset($assign_to_config) && is_array($assign_to_config))
	{
		foreach ($assign_to_config as $key => $value)
		{
			$CFG->set_item($key, $value);
		}
	}`

    2. However, in line 200, the Hooks class was instantiated before config class is loaded.
    `$EXT =& load_class('Hooks', 'core');`
2. Look into system/core/Hooks.php, from line 90 to line 98. The hooks class constructor also loads the config items. Then it verifies the ‘enable_hooks’ item that actually comes from the default config to determine if hooks feature is enabled or not. Obviously, the customized 'enable_hooks' value is not yet effective because of the loading order mentioned in point #1 above)
		`$CFG =& load_class('Config', 'core');
		log_message('info', 'Hooks Class Initialized');
		// If hooks are not enabled in the config file
		// there is nothing else to do
		if ($CFG->item('enable_hooks') === FALSE)
		{
			return;
		}
`

To fix this bug, I suggest a two-step approach: 1) instantiate the Hooks class after loading the Config class. 2) Using config_item('enable_hooks') in Hooks ctor which takes the current effective config sets instead of loading the default config.
*note: using the config_item('enable_hooks') makes more sense than calling the load_class('Config', 'core') class registry here.

**Comment by bkader** [comment]
Sorry for commenting this close issue, but I wanted to say that there are other classes to which to can pass $CFG and use it so you don't **load_config** again. Some of them are:  
* __Controller.php__ at line **78**, you can use `$this->load =& load_class('Loader', 'core', $this->config);`;  
* the __Input.php__ uses `config_item()` often, so I added $CFG to class constructor on __CodeIgniter.php__ file.  
* __Exceptions.php__: it is loaded using `show_error()`and `show_404()`, it uses `config_item()` as well, so I added `global $CFG;` then I loaded the class passing $CFG to its constructor.  
* __Loader.php__:  Because I added `$this->config` to __Controller.php__ when loading the __Loader.php__ class, the `Loader::config()` method can use it like so: `$this->config->load(...)` instead of using `get_instance()->...`. And: both `add_package_path()` and `remove_package_path()` methods will no longer need to use `$this->_ci_get_component('config')` (this method becomes useless) but you will have to change it in other classes as well.  

All what I said, can be done in one single function, the `load_class()`, so instead of having at the end of it:  

    $_classes[$class] = isset($param)
        ? new $name($param)
        : new $name();
    return $_classes[$class];    

Use this:  

    if ( ! isset($param) && $class !== 'Config')
    {
        global $CFG;
        $param =& $CFG;
    }
    $_classes[$class] = new $name($param);
    return $_classes[$class];
