### ISSUE TITLE
Codeinigtor can't work on Openlitespeed or litespeed

### ISSUE THREAD

**Issue by iamzerovn** [bcit-ci/CodeIgniter#5390]
Dear Admin !
Can you explain for me why The Codeinigtor can't work on Openlitespeed or litespeed with any php version ?
I know about rewrite rules in openlite speed is different apache (http://open.litespeedtech.com/mediawiki/index.php/Help:Rewrite_Rule_Differences ),  but..nothing happend when run codeignitor.
Please help

**Comment by narfbg** [comment]
No, I can't explain. I've never used litespeed, so I couldn't even begin to guess. But you're not helping yourself either ... Seriously, if I were to troll an OSS maintainer, I couldn't do a better job than this. You've even managed to misspell CodeIgniter twice.

If you're really looking for help, post on our [forums](https://forum.codeigniter.com/) and *explain your problem*. Nobody can help you with "doesn't work" and "nothing happens" because that doesn't mean anything.
