### ISSUE TITLE
Field data returns one-less fields after query with limit

### ISSUE THREAD

**Issue by xeldarith** [bcit-ci/CodeIgniter#5435]
I'm extending the `query()` from core oci8 driver and I've found bug on `$result->field_data()` (`$result` is an `oci8_result` returned from `parent::query()` method).
The `field_data()` is returning one less fields on subsequent queries after doing select query with `limit()`.

Here's the scenario where it failed:
```
// query with limit
$db->limit(5)->get('TABLE'); // field_data() returns full fields here

// subsequent query
$db->get('TABLE'); // field_data() returns one-less fields
```

Here's how I extends the query() and found the bug:
```
public function query($sql, $binds = FALSE, $return_object = NULL)
{
	$result = parent::query($sql, $binds, $return_object);
        // ............
        $field_data = $result->field_data();
       // dump field_data to check the fields, second query will return one-less fields
       var_dump($field_data); 
}
```
After I trace oci8 driver files, I found that `$this->limit_used` is not reset to `FALSE` after select query is reset. Why it matters? When `$this->limit_used` is `TRUE`,  number of fields that being returned by `field_data()` will be subtracted by 1.

So my fix / workaround is by adding/overriding `_reset_select()` method on `oci8_driver`
```
protected function _reset_select ()
{
        parent::_reset_select();
        $this->limit_used = false;
}
```

Note that this problem occurs only with `oci8` driver.
I hope it's already fixed in future release. 
Thanks.

**Comment by narfbg** [comment]
You're onto something as `limit_used` is never reset, indeed.

But almost nothing else makes sense ...

1. While not technically impossible (with certain limitations), we don't support extension of any of the database classes, so ... How? And why should we consider this as valid anything at all?
2. Even if we did support DB extensions, why is that a precondition for your bug report? It doesn't seem to me like it should be related at all?
3. What does "one-less fields" mean exactly? There's no expected vs actual results presented.
4. `query()` is to be directly used for raw SQL queries, while `_reset_select()` is an internal method to provision a reset of Query Builder conditions (and `$limit_used` is only relevant with QB) - no link between the two.
5. "I hope it's already fixed in future release." - if you hope it's already fixed, you can easily check if it is with a simple search.

That last one is just a nitpicky remark, but please do clarify on the rest.

**Comment by xeldarith** [comment]
Sorry for wasting your time because I didn't make it clear.

1. I'm doing it by extending the `CI_Loader` class and overriding the `database()` method to load my extension or the original if not found.
2. a. `$limit_used` in `CI_DB_oci8_result` is initialized with the same value of `CI_DB_oci8_driver`'s `$limit_used`.
    b.  Because `field_data()` is a protected method from CI_DB_Driver, so to my knowledge, to call it we need to either modify the database class or extend it. I'm doing the latter because it's "cleaner" and I've already extended it for another purpose.
3. Ahh, my bad. One-less fields means exactly that. The fields returned by `field_data` is missing one i.e. the last field.
This is only an example (json-encoded). I don't have access to Oracle database right now.
Expected:
```
[
	{
		"name": "id",
		"type": "NUMBER",
		"max_length": 32
	},
	{
		"name": "name",
		"type": "VARCHAR2",
		"max_length": 100
	},
	{
		"name": "price",
		"type": "NUMBER",
		"max_length": 12
	}
]
```
Actual (missing `price` field):
```
[
	{
		"name": "id",
		"type": "NUMBER",
		"max_length": 32
	},
	{
		"name": "name",
		"type": "VARCHAR2",
		"max_length": 100
	}
]
```

4. Very true. That's why I override the `_reset_select()` in `CI_DB_oci8_driver`, because `$limit_used` is used only by oci8 driver and result. 
5. I was not really expecting it to be fixed to be honest. Because this's a special use case for me. 
What I hoped was only so this could help anyone who faces similar issue. 
I think it's just my habit to write it like that. Sorry if it was disturbing you.

I feel dumb, after writing the answer to no. 4.
I can just override the `_reset_select()` in my extension class so I don't need to modify the database class at all. 
I guess I'm too exhausted yesterday after spending hours to fix the problem. Sorry about that.

Thank you for your time.

**Comment by narfbg** [comment]
I had already said that you're onto something with this ... it's a legitimate bug; pushed the fix.

The points I listed were for clarification because you made the whole thing quite confusing. 3 is what I really needed info for, while the rest have literally no connection to the issue - they may be the circumstances under which you found the issue, but then become noise that needs to be separated out while figuring what's actually going on.
