### ISSUE TITLE
xss_clean issue

### ISSUE THREAD

**Issue by ccnie** [bcit-ci/CodeIgniter#5463]
In xss_clean URL Decode part, we use rawurldecode to decode string.
While the string is encoded in gb2312, such as  'https://www.sogou.com/web?query=%C1%EC%BF%CB01'.

The return string will be decoded as error string.

**Comment by cvhau** [comment]
This issue was not caused by xss_clean, using rawurldecode to decode a string that was encoded in GB2313 is incorrect way. If possible you should encode the url in normal url encode standard (see http://php.net/manual/en/function.urlencode.php) or RFC 3986 (see http://php.net/manual/en/function.rawurlencode.php).
I hope this will help you. Good day! :)
