### ISSUE TITLE
Incorrect uri in caching functions

### ISSUE THREAD

**Issue by hamzawain7** [bcit-ci/CodeIgniter#5479]
Output.php
_write_cache line 548. $uri is incorrect
_display_cache line 631. $uri is incorrect

The uri formed doesn't has a slash after index_page i.e uri has the value 'http://localhost/index.phpcontroller/function' instead of 'http://localhost/index.php/controller/function'.

**Comment by narfbg** [comment]
https://github.com/bcit-ci/CodeIgniter/blob/3.1.8/system/core/Output.php#L548 - docblock
https://github.com/bcit-ci/CodeIgniter/blob/3.1.8/system/core/Output.php#L631 - an opening brace with '$uri' nowhere in sight

...

**Comment by hamzawain7** [comment]
Sorry
https://github.com/bcit-ci/CodeIgniter/blob/3.1.8/system/core/Output.php#L565
https://github.com/bcit-ci/CodeIgniter/blob/3.1.8/system/core/Output.php#L675

**Comment by hamzawain7** [comment]
You can debug the value of $uri at lines mentioned, it is missing a slash. The code is working because the same hash with a missing slash is used everywhere, but it would be better if the slash wasn't missing because when writing custom functions for cache one supposes that the uri is not missing a slash after index

**Comment by 17100113** [comment]
Hi. 

In the _write_cache function, we have $uri as
`$uri = $CI->config->item('base_url')
			.$CI->config->item('index_page')
			.$CI->uri->uri_string();`

In the _display_cache function, again, we have the URI as 
`$uri = $CFG->item('base_url').$CFG->item('index_page').$URI->uri_string;`

The debugger shows the following results:
There's a slash missing between index.php and l/facebook-cover...
![screen shot 2018-04-24 at 4 41 57 pm](https://user-images.githubusercontent.com/3061219/39184944-d5680b7e-47de-11e8-8e35-ea1db2fa5026.png)

In some places, such as the site_url function in Config.php (core files for codeig), a function "slash_item" has been used to "Fetch a config file item with slash appended (if not empty)". Perhaps that is missing from here?

**Comment by narfbg** [comment]
@17100113 Thanks. I was about to go "PR or GTFO" on this, but the suggestion to use `slash_item()` does resolve the issue.

But please don't post screenshots of code ... it really doesn't help with anything.

@hamzawain7 This is a bug tracker. If you want to nitpick the code for obscure inconveniences to potential custom code that 1 in a 1000 users would experience, you need to be proactive ...

1. You opened a bug report with 2 lazy (no links), incorrect references to single lines of code and an unclear problem statement.
2. I point out the incorrect references.
3. You reply with "corrected" ones that don't really show anything.
4. I explain the unclarity, suggest that the unclear problem probably isn't a problem and ask you to elaborate *a lot*.
5. Your reply (as lazy as possible again) basically amounts to "You go debug it. But yeah, there's no bug, just maybe custom coders would like it better otherwise".

^ That's an example of how to annoy any OSS maintainer. You would've never convinced me to do anything but closing the issue, and this would've been just a huge waste of our time.

I'll make this change because it turns out to be as simple as `item()` -> `slash_item()` and it would be semantically correct (in that you're right), but that comes at a price ...

Now I have to write another note in the upgrade instructions (because people will be left with junk cache files), and that means a huge bunch of people will look at a lenghtier upgrade guide, not want to go through it and subsequently not upgrade. And I have to deal with all the fallout from that.

So please, anyone who reads this, if you want any kind of change, anywhere - be constructive and proactive, don't be lazy, put in some effort. It's the least you can do and it's all we expect.

**Comment by hamzawain7** [comment]
I am sorry with not make this mistake again.
