### ISSUE TITLE
Redis class (Cache library driver) throws exception when Redis server is down

### ISSUE THREAD

**Issue by thorium369** [bcit-ci/CodeIgniter#5562]
When the Redis server is down, and you try to use the redis driver like :
```
$this->load->driver('cache');
$this->cache->redis->save('foo', 'bar', 10);
```

It returns an exception:
```
Type: RedisException
Message: Redis server went away
Filename: E:\codeigniter-app\system\libraries\Cache\drivers\Cache_redis.php
Line Number: 140
```

The line throwing the error is from the constructor of CI_Cache_redis class:
`$serialized = $this->_redis->sMembers('_ci_redis_serialized');`

Is this expected behavior or should the Redis cache driver handle this exception in some way? (like currently it handles RedisException while doing connect/auth).

This was found while using the latest version of CI : 3.1.9

**Comment by anovsiradj** [comment]
workaroud

```php
$this->load->driver('cache');

$ok = true;
try {
	// @$this->cache->redis->save('foo', 'bar', 10);
	$this->cache->redis->save('foo', 'bar', 10);
} catch (\Exception $e) {
	$ok = false;
	log_message('error', 'redis server is down! ' . $e->getMessage());
}
```

**Comment by narfbg** [comment]
The on-connect checks exist so that the library can fallback to another driver if configured so.

After a connection is established, it is assumed that everything related to it is supposed to be fine, and your particular issue shouldn't even be possible - you have connected to the server literally a millisecond ago. Such crashes are not just rare and unexpected ... I didn't even know they were possible, since method calls (in this case to `sMembers()`) are supposed to just return FALSE in case of failure.

I suppose we could add checks for that, although they'd be some annoyance in our code, but whether that's expected behavior or really a moot point, as it was never envisioned. The question is whether CI handling this particular exception is beneficial or not. If it objectively helps users - then it's good, but if it just hides debugging information, then it wouldn't be such a good idea.

P.S. Please don't post screenshots of code. It's annoying, literally doesn't help with anything and in this particular case nobody needed to see that code anyway.

**Comment by thorium369** [comment]
Thanks @narfbg for your thoughts. 
Sorry I am replying so late.

Regarding the issue that happened with me, it was due to some outage at the cloud provider and the redis server went completely down (which is really rare). So due to this even the connection establish call had failed as I could see errors in the logs for that. Hence it wasn't the case that connection was established and the ```sMembers()``` call failed a millisecond later.

According to me, CI handling the exception would be beneficial, as I too was expecting redis calls to just return false in case if they fail. A simple log_message like the one's for connection establish seems good for debugging. However I can understand other developers might expect different behavior. So the decision is up to the community & contributors. Feel free to close if this issue if needed.

Out of curiosity, I tried modifying the redis cache driver myself so that the ```sMembers()``` call in question doesn't throw an exception.
But then any call to redis like ```$this->cache->redis->save('foo', 'bar', 10);``` throws an exception on line 193 ```$this->_redis->set($id, $data, $ttl);``` and line 325 ```$this->_redis->close();```.
So for CI to handle all exceptions, along with the sMembers call it would be required to put each function called using _redis in the cache driver to be in try-catch.
Or alternatively, users can just put their calls to the driver like ```$this->cache->redis->save()``` in the try-catch block.

About the screenshot of code, will keep in mind.

**Comment by narfbg** [comment]
I see ... Well, the most debug-friendly thing we could do is to actually remove the current `catch` block for the connection establishment. If the existing log message saying that the connection failed didn't help you, I don't see how countless others saying that e.g. `save()` fails would.

That way, one could at least do with just a `try ... catch` during initialization as opposed to every other call.
