### ISSUE TITLE
Form_Validation does not work in 3.1.9

### ISSUE THREAD

**Issue by lichtwellenreiter** [bcit-ci/CodeIgniter#5660]
I had downloaded a fresh copy from 3.1.9 from the website. When ist comes to validate inputs with form_validation, CI was not able and returned alway false. Then i grabbed the Form_validation.php from the 3.1.x stable branch and replace my file with it, it works now fine

**Comment by apartamenti** [comment]
In Form validation callbacks not working. I guess this is a bug. I tried to copy from 3.1.x stable branch but it's still not working.

**Comment by jim-parry** [comment]
Saying "it doesn't work" is not helpful. Your issues are more than likely configuration problems.
Please post your "question" on the [forum](https://forum.codeigniter.com/index.php), with enough explanation that someone can help you.

**Comment by jim-parry** [comment]
That error message happens if you have a callback rule without an error message.

**Comment by apartamenti** [comment]
I have an error message, callback function is returning TRUE.

`if ($res == 0)
		{
			$this->form_validation->set_message('currentpass_check', 'Current password Didn\'t match');
			return FALSE;
		}
		else
		{
			return TRUE;
			
		}`

**Comment by narfbg** [comment]
@lichtwellenreiter There are no changes to the FV library since the 3.1.9 release:

> $ git diff 3.1.9 3.1-stable system/libraries/Form_validation.php
> $

Whatever problem you were having, it was likely because of manual patches that you've applied yourself. And even otherwise, if replacing 3.1.9 with 3.1-stable fixes something, that would only mean that we've found the problem and fixed it already; posting issues about that is pointless.

@apartamenti You're doing a lot of things wrong ...

- Hijacking someone else's thread, without adding anything helpful to it.
- Not listening to our instructions.
- Posting a screenshot because ... why? That doesn't clarify anything.
- Posting a random code snippet, which not only doesn't help either (we don't know the rest of your code), but is also not real - it would produce a syntax error.

Please, just post on the [forums](https://forum.codeigniter.com/), listen to the feedback that you get and use more common sense.

**Comment by apartamenti** [comment]
> @lichtwellenreiter There are no changes to the FV library since the 3.1.9 release:
> 
> > $ git diff 3.1.9 3.1-stable system/libraries/Form_validation.php
> > $
> 
> Whatever problem you were having, it was likely because of manual patches that you've applied yourself. And even otherwise, if replacing 3.1.9 with 3.1-stable fixes something, that would only mean that we've found the problem and fixed it already; posting issues about that is pointless.
> 
> @apartamenti You're doing a lot of things wrong ...
> 
>     * Hijacking someone else's thread, without adding anything helpful to it.
> 
>     * Not listening to our instructions.
> 
>     * Posting a screenshot because ... why? That doesn't clarify anything.
> 
>     * Posting a random code snippet, which not only doesn't help either (we don't know the rest of your code), but is also not real - it would produce a syntax error.
> 
> 
> Please, just post on the [forums](https://forum.codeigniter.com/), listen to the feedback that you get and use more common sense.

Did you read https://github.com/bcit-ci/CodeIgniter/blob/develop/contributing.md , when you saying hijacking someone else's thread ? We've same problem with @lichtwellenreiter.  Be careful with the language!

**Comment by apartamenti** [comment]
OK I will.
