### ISSUE TITLE
Password config files?

### ISSUE THREAD

**Issue by wood-chris** [bcit-ci/CodeIgniter#5687]
Both the [gitignore.io](https://www.gitignore.io/api/codeigniter) and [github](https://github.com/github/gitignore/blob/master/CodeIgniter.gitignore) recommended `.gitignore` files for CodeIgniter include `*/config/development`, which is designed to put (dev) files which include passwords. However, the current [CodeIgniter](https://github.com/bcit-ci/CodeIgniter/blob/3.1-stable/.gitignore) `.gitignore` doesn't include this. 

Is this an oversight (hence this can be regarded as a bug report), or is there a different recommended way to manage passwords in repositories? The most ideal situation would be to _only) have the passwords (and usernames?) in a separate file that isn't in a repo, but all other config to be stored in the repo, so that an entire stack can be easily and quickly recreated.

**Comment by narfbg** [comment]
Our current .gitignore only deals with stuff that we actually track in our repository, which doesn't include *config/development/* or any other environment-specific location.
Even the 'development' name itself isn't a constant and unless you're a one-man project you likely have no reason to use it - a sensible setup would give each developer their own environment.

This doesn't mean that adding such a line to *.gitignore* couldn't at least serve as an example, but the lack of it isn't a bug, nor an oversight. At best it's a minor convenience for some to have and to put it bluntly, I don't care whether it exists or not.

You're free to submit a PR with it if you wish, but that opens up more questions for discussion - what happens to *config/config.php*? What about *config/production/config.php* (the 'production' name is actually hard-coded and comes with functional implications)? Production credentials should be more important to keep secret ...
Yet, if we put both in `.gitignore`, that means people no longer have example configs AND we'll be showered with bug reports about CI no longer working out of the box.

As for specific "password files", there's too many ways to implement that and that's just something we leave up to our users. Not least because every deployment strategy will handle it differently.

**Comment by wood-chris** [comment]
Thanks for the reply and explanation! Yes, I agree that it would open up a (potentially complicated) discussion. Given your justification, I'll leave it as the status quo.
