### ISSUE TITLE
Fatal error when calling constructor of CI_Model class in 3.1.10

### ISSUE THREAD

**Issue by zkelo** [bcit-ci/CodeIgniter#5689]
I have a model `Account` with following code;
```php
class Account extends CI_Model
{
	private $tableName = 'accounts';
	public function __construct()
	{
		parent::__construct();
		$this->load->library('database');
	}
        // Other methods...
}
```
I loaded this model in controller (`$this->load->model('account')`). With this code I'm getting fatal error "**Cannot call constructor**". What happens in new CI 3.1.10 and how I can fix this?

CI 3.1.9 haven't this error.

**Comment by narfbg** [comment]
I have to point out that calling `CI_Model::__construct()` does nothing; to be more precise - that constructor itself does nothing; it's empty: https://github.com/bcit-ci/CodeIgniter/blob/3.1.10/system/core/Model.php#L57
That's been the case since 3.1.7, and even before that it only logged a pretty much useless message. We've only kept it for backwards compatibility and you should just remove those `parent::__construct()` calls.

But that being said, there have been no changes to *system/core/* between 3.1.9 and 3.1.10. You've likely pulled the *develop* branch instead of 3.1.10 and those are not the same thing.
