### ISSUE TITLE
Query Builder dbprefix gets injected in the wrong place on Update.

### ISSUE THREAD

**Issue by objecttothis** [bcit-ci/CodeIgniter#5694]
#4086 and #4096 are similar.  Running CodeIgniter 3.1.9

`$this->db->set('attribute_values.attribute_datetime','attribute_values.attribute_value');`
`$this->db->where('attribute_links.definition_id',$definition_id);`
`$success = $this->db->update('attribute_values JOIN attribute_links ON attribute_values.attribute_id = attribute_links.attribute_id');`

Produces:

    UPDATE `attribute_values
    JOIN attribute_links ON attribute_values`.`ospos_attribute_id =` `attribute_links`.`attribute_id`
    SET `ospos_attribute_values`.`attribute_datetime` = 'attribute_values.attribute_value'
    WHERE `ospos_attribute_links`.`definition_id` = '8' 

You can see that the order of the join turns out properly but that it's inserting dbprefix on the attribute_id column and it's inserting a backtick in improper places.  In other areas the Query builder is not inserting the dbprefix where it should.

I would like to be able to use db->join() with db->update() but for some reason that isn't a thing even though my code above accomplishes the join if I'm not using dbprefix, but dbprefix breaks it.  This should either be fixed to work properly with dbprefix or something should be put into place to temporarily not append dbprefix so that it can be hardcoded and it won't put dbprefix in the wrong place like it's doing now.

Before you say it, not using dbprefix isn't an option.

**Comment by narfbg** [comment]
> You can see that the order of the join turns out properly but that it's inserting dbprefix on the attribute_id column and it's inserting a backtick in improper places. In other areas the Query builder is not inserting the dbprefix where it should.

Well, I had to edit your post and add proper code formating before I could see this ... :)

> I would like to be able to use db->join() with db->update() but for some reason that isn't a thing even though my code above accomplishes the join if I'm not using dbprefix, but dbprefix breaks it.

Yea, the problem here is that you're shoving arbitrary SQL into `update()` and it's not designed to work like that. You've linked other issues as similar because they mention "dbprefix", but if there's any issue related to this it's #2944 - it's kind of long, but if you read through it you'll find hints at why the combination of `update()` and `join()` isn't supported.
Either way, that's not a valid pretext for shoving a `JOIN` expression into `update()` and expecting it to work at all (I'm surprised it does), let alone in combination with another feature ...

> This should either be fixed to work properly with dbprefix or something should be put into place to temporarily not append dbprefix so that it can be hardcoded and it won't put dbprefix in the wrong place like it's doing now.

I don't fully understand what you're suggesting, but there's nothing to fix. You're doing something that's just not supported.
The only alternative I can suggest is using raw SQL and `query()`.

> Before you say it, not using dbprefix isn't an option.

Oh, it's an option ... you just don't like that option.
I'm seriously itching to drop that feature entirely and remarks like this are really testing my resolve to keep it for the few poor souls who think it's a good idea. What I'm trying to say is, just stick to reporting actual problems and if there's a bug we'll fix it. This isn't helping your case.

**Comment by objecttothis** [comment]
@narfbg dbprefix is useful when you have two or more installs of the same CI driven software in the same database space. The reason I said it's not an option is not because it's not possible, we agree on that, but that involves a bunch of code rewrites and refactoring for code that already uses it.

You're saying join and update isn't supported and I can respect that, but as long as the database (MYSQL in this case) is capable of doing it, then you are going to get people trying to use Query Builder to do things like this, so it really shouldn't be surprising that people are asking.  Doing a search on "CI Query Builder Update Join" gives quite a number of hits in google on people trying to do this an similar.  For now I'm using Query builder and dividing it into two separate queries and making PHP do the work of the join via associated array.

The dbprefix suggestion was simply to have a means of disabling the appending of the dbprefix value for a block of code, or a flag specifically for querybuilder to disable the appending for that query.
