### ISSUE TITLE
readme.rst Improvement

### ISSUE THREAD

**Issue by wangch7** [bcit-ci/CodeIgniter#5761]
Problem Description: No instruction of how to contribute in readme.rst. First time users will probably want to see information of how to contribute (which includes how to set up environment, communicate, and submit changes, etc.).

Solution Description: Add a contributing section in readme.rst with general contributing information, and include a link to file "contributing.md" (https://github.com/bcit-ci/CodeIgniter/blob/develop/contributing.md).

**Comment by narfbg** [comment]
The cynic in me says that if one can't find their way into contributing.md, then they likely don't have what it takes to contribute anything of value. Not least because contributing.md is automatically linked by GitHub in the "New issue" form.

On the other hand, it can't hurt, but there's also a tiny issue with linking to the file - we'd have to make a hard link (i.e. absolute URL, not relative) to it, which includes the branch in it and that's a bit wonky when the 3.1-stable branch links to develop for no apparent reason (and you can be sure nobody will bother correcting that after each merge).

@jim-parry What do you think?

**Comment by narfbg** [comment]
Resolved via #5980.
