### ISSUE TITLE
CI v3.1; mysql_driver; use backslash as like escape character rather than bang

### ISSUE THREAD

**Issue by hellopablo** [bcit-ci/CodeIgniter#5765]
I ran into an issue where queries weren't returning results when they were expected to. I eventually found it was due to the mysql driver using the `!` character as the `$_like_escape_chr` string rather than a backslash.

Is this a bug? Or am I missing some information ? I've Google and the suggestion is that backslash is indeed the correct escape character.

I wanted to check before I submitted a PR (I'm stuck on v3.* unfortunately).

**Comment by narfbg** [comment]
It's not a bug. The escape character is declared within the query, which allows more flexibility.

**Comment by hellopablo** [comment]
Thanks for the response @narfbg. Can I ask why CI uses the `!` character by default, when MySQL defaults to `\`? Do I need to set the `ESCAPE` query with _each_ `like` query? I cant see an easy way to globally change this on the fly within the app.

**Comment by narfbg** [comment]
For one, since the backslash is an escape character in PHP, it's simply easier to work with `!`, to avoid having to double escape everywhere. Then also, MySQL isn't all there is; we support lots of databases and we don't design our stuff around MySQL defaults.

I don't know what you're doing in order to answer your other question, but you should ask on the [forums](https://forum.codeigniter.com/) anyway, this is a bug tracker.
