### ISSUE TITLE
Oracle does not support "REPLACE" query

### ISSUE THREAD

**Issue by tomaluca95** [bcit-ci/CodeIgniter#5767]
I'm using CI 3.1.10 and when I run a `db->replace` I get a `ORA-00900: invalid SQL statement`.

I think that Oracle does not support "REPLACE" query

**Comment by narfbg** [comment]
... and? We can't make Oracle have a REPLACE statement.

**Comment by tomaluca95** [comment]
The driver doesn't raise an error like it does with `->last_id()`

**Comment by narfbg** [comment]
The driver doesn't do anything for `last_id()` either, the method simply doesn't exist.

You'll get a PHP error for `last_id()` because the method doesn't exist at all, while `replace()` exists in the Query Builder, which all drivers extend, so code executes and you get an SQL error instead. This is an implementation detail.

**Comment by tomaluca95** [comment]
The oci8_driver.php has on line 439:

```
public function insert_id()
	{
		// not supported in oracle
		return $this->display_error('db_unsupported_function');
	}
```
