### ISSUE TITLE
Exception: Too few arguments to function CI_Input::post_get()

### ISSUE THREAD

**Issue by OmarSRolo** [bcit-ci/CodeIgniter#5772]
I am getting this error:
Exception: Too few arguments to function CI_Input::post_get(), 0 passed in /var/www/api/application/core/MY_Controller.php on line 150 and at least 1 expected /var/www/api/system/core/Input.php 262

the code that rise this error is this one:

    public function get_post_all($id = true)
    {
        $data = $this->input->post_get();
        if (count($data) === 0) {
            $data = $this->input->get_post();
        }
        if (count($data) === 0) {
            $data = (array)json_decode(file_get_contents('php://input'), TRUE);
        }
        if ($id) {
            return $data;
        } else {
            unset($data['id']);
            return $data;
        }
    }

I have being using this code for long time.. I dont know why now this error.

**Comment by lcssanches** [comment]
`post_get` and `get_post` require a parameter. That's why you're getting this error.

Calling `post_get` and `get_post` makes no sense. [See the docs](https://www.codeigniter.com/user_guide/libraries/input.html?highlight=post_get#CI_Input::post_get).

I think you should be using only `post()` and `get()` instead.

**Comment by OmarSRolo** [comment]
I know what it means.. But the same web works in Windows with xampp.. But
not in Linux. Grettings

**Comment by lcssanches** [comment]
You probably have different versions of PHP on Windows and Linux.

Anyway, you should fix your code.

**Comment by narfbg** [comment]
> But the same web works in Windows with xampp

No, it doesn't. Maybe the error message doesn't show up, because you've disabled error reporting, but that doesn't mean it's working. And even if it did, that doesn't mean you should be using the thing in a clearly wrong way.

Either way, this is a bug tracker. Please post your questions on our [forums](https://forum.codeigniter.com/) instead.
