### ISSUE TITLE
Potential php5_validate_id()-related bug in Redis Session driver

### ISSUE THREAD

**Issue by gxgpet** [bcit-ci/CodeIgniter#5779]
Hello,

While working on a composer-installable version of CI's Session library, I noticed that for the Redis session driver the call of `php5_validate_id()` method happens on a fail scenario, on the `CI_Session_redis_driver::open()` method, instead of success case. So I think the correct version of it would be

```diff
 		else
 		{
+			$this->php5_validate_id();
 			$this->_redis = $redis;
 			return $this->_success;
 		}

-		$this->php5_validate_id();
-
 		return $this->_fail();
 	}
```

If what I'm saying is correct, I can open a PR with it.

**Comment by narfbg** [comment]
It appears that you're right, yes.

**Comment by gxgpet** [comment]
Okay, will open a PR about it.

Also, if we are on this, I have another quick question for `CI_Session_files_driver::open()`: why is it throwing the generic `Exception` on fail cases instead of a `log_message()` + `return $this->_failure;`? Is it intentional or should that be changed? I can open a PR about that, too. :)

**Comment by narfbg** [comment]
I'm not sure about that.

It was probably intended as a way to simulate the effect of `return $this->_failure;`, as the initial version of `CI_Session` didn't utilize that technique - the `_failure` property only exists because of a PHP5 bug where `return FALSE` (the actual intended way to trigger failures) wasn't working, so it was added later when I accidentally found out that `return -1` works.
Yes, a PR for that would be nice too.
