### ISSUE TITLE
Function delete_files has a bug

### ISSUE THREAD

**Issue by StudPro** [bcit-ci/CodeIgniter#5809]
Hi CI Team,
into file /system/helpers/file_helper (CI v3.1.10) on line 143 the code check if the "filename" start not with dot but if it is a "directory", and not a file, it's a problem on line 149.

I found this bug about when someone tried to open a url like http://url/.somethings/xxx and CI create a directory like application/cache_db/.somethings/xyz

The Ci report a log error how it's impossibile to delete the file... but it's a directory!

A suggestion to fix it?

**Comment by narfbg** [comment]
I'm not sure I get what you're saying ...

Is it a cache-clear bug or a `delete_files()` bug? If `delete_files()` is not doing what is necessary to clear up cache files, we could simply not use it there ...

**Comment by alixbergeret** [comment]
Hi,

I cannot replicate this issue, and as such I suggest that we close it, unless we get more information.

Here is what I did to try and replicate the issue:

- I activated the database caching on one of my live CI3 websites, to generate files and folders in the "cachedb" folder (since it is mentioned in the original message).

- I then tried to call the delete_files helper on various files/folders withing the "cachedb" folder, with the $del_dir parameter set to true and false... everything works as expected, no errors, normal behaviour. 

The only strange thing is that it won't deleted folders with a name starting with a dot, but that seems to be by choice, see line 123 in file_helper.php (second clause in IF statement):

`if (is_dir($filepath) && $filename[0] !== '.' && ! is_link($filepath))`

Cheers.
