### ISSUE TITLE
_alter_table for sqlite3

### ISSUE THREAD

**Issue by 0x6d61726b** [bcit-ci/CodeIgniter#5911]
Hey, I am wondering why there is no support for `DROP` and `CHANGE` in `_alter_table` for sqlite3. Is it just that nobody has implemented it yet or is it something more serious?

https://github.com/bcit-ci/CodeIgniter/blob/2ad24af488da7dc518684cc146914b2937749031/system/database/drivers/sqlite3/sqlite3_forge.php#L144-L157

I am asking because I would like to use that function both with mysqli (which is supported) and sqlite3 (which is currently not).

**Comment by narfbg** [comment]
SQLite being "lite" simply doesn't support a lot of functionality that you'd otherwise find in a traditional SQL database. Such is the case here, as it simply doesn't support DROP and CHANGE column statements.

Docs: https://www.sqlite.org/lang_altertable.html

The commented-out SQL code seen in `CI_DB_sqlite3_forge::_alter_table()` is a potential work-around for the DROP functionality. In a way, that is indeed the case of just noone having implemented it yet, but that's because the implementation is much more complex than what other database platforms offer.
