### ISSUE TITLE
bug: redirect clears or destroy the session object

### ISSUE THREAD

**Issue by mckaygerhard** [bcit-ci/CodeIgniter#5974]
i worked in a code of my page.. as many examples in web.. but those that implicas "redirect" directive of CI does not work..

how this happens? easy, make just a form with a value, and send to a controller that opens a session object.. after success created the session make a redirect.. and session retrieve of the data are empty:

1. Form submitted
2. Receive in controller
3. after session created Redirects
3. after try to get some data result in empty or null

after a search i found some bugs reported like: https://github.com/bcit-ci/CodeIgniter/issues/5934#issuecomment-605914977 and  https://github.com/bcit-ci/CodeIgniter/issues/5545 and https://github.com/bcit-ci/CodeIgniter/issues/5545

**The common denominator:  the redirection! and the session id validation**

in my code i removed the redirect and works! but if i try to put any redirect usage.. session are destroyed! after this i try to search in older versions and works with 2.X and 3.1+patch (--LINK REMOVED--) for php 5.6 and php 7.X, but seems in https://github.com/bcit-ci/CodeIgniter/issues/5545#issuecomment-405923226 resolved too but needs work, currently doe snot work with php 5.6 and php 7.0!

hope this clarify and make at least a proper bug request over the session problem for me and @luizzz @it-can @wrabit and others..

**Comment by toshadevam** [comment]
I think that bug, has reported before!

Please Help!

**Comment by narfbg** [comment]
No, this isnt clarifying anything.

You're saying meaningless things, in poor English (I can't blame you, but the fact is it makes understanding you harder), linking to an awful blog post that doesn't differentiate between CI2 and CI3, the phrase "bug request" is an oxymoron ... I don't think you even understand what the term bug means.

I'm going to assume that you're talking about the `redirect()` URL helper here, because nothing else makes sense.

`redirect()` does an `exit;` at its end and when you do use `redirect()`, it interrupts everything that's still going on and stops all remaining script execution. If you use it before a session is properly initialized, that will naturally not allow it to complete.
This applies to everything. Redirects don't have any relation or knowledge of sessions and vice-versa.

This is not a bug.
