### ISSUE TITLE
Sesssion with dot not working

### ISSUE THREAD

**Issue by rmdhfz** [bcit-ci/CodeIgniter#6019]
$config['sess_cookie_name'] = 'mydomainsession.id';

it's not work

**Comment by gxgpet** [comment]
If this is about using `'mydomainsession.id'` as a cookie name, then it cannot be regarded as a bug, since that is an accepted value for a cookie name. If you still think this is a CodeIgniter internal bug, please provide more detailed steps for reproducing the problem, but also what exactly isn't working.

However, if you need help with debugging an issue with your own application, you should head to the [forums](https://forum.codeigniter.com/).

**Comment by gxgpet** [comment]
Also, this seems addressed on #3108.

**Comment by rmdhfz** [comment]
Thank you @gxgpet
