### ISSUE TITLE
cli 返回 Controller or its method is not found: {0}::{1}

### ISSUE THREAD

**Issue by zl0314** [bcit-ci/CodeIgniter#6044]
windows平台下面 （代码是从https://codeigniter.org.cn/下载的4.0.3）， 在**testing**环境下，执行php spark serve的时候， 返回的信息是：
【
   ERROR: 404
  Controller or its method is not found: {0}::{1}
】

不能任何参数，执行php spark的时候，返回：
【
An uncaught Exception was encountered

Type:        Error
Message:     Call to undefined method CodeIgniter\HTTP\IncomingRequest::getSegments()
Filename:    D:\site\ci4\system\CodeIgniter.php
Line Number: 906

        Backtrace:
              -400 - D:\site\ci4\system\CodeIgniter.php::runController
                              -308 - D:\site\ci4\system\CodeIgniter.php::handleRequest
                              -86 - D:\site\ci4\system\CLI\Console.php::run
                              -57 - D:\site\ci4\spark::run

】

**Comment by datamweb** [comment]
Set `CI_ENVIRONMENT = development` . CLI do not run in testing mode.

**Comment by gxgpet** [comment]
Hello! Please keep your posts and comments in English, so that everyone can understand. 
This is the CI3 repository. If you are looking for CI4 repo, please head to https://github.com/codeigniter4/CodeIgniter4.

We also encourage people looking for help for their own projects to seek it on the [forums](https://forum.codeigniter.com/), as we use this area for bugs related to the framework itself.
