### ISSUE TITLE
unable to access get_instance() on pre_controller hooks.

### ISSUE THREAD

**Issue by gphg** [bcit-ci/CodeIgniter#6068]
As the docs said:
> **pre_controller** Called immediately prior to any of your controllers being called. All base classes, routing, and security checks have been done.

Does this mean it count the `get_instance()`? I tried to `var_dump` the `get_instance()`, it return `null`. But once I changed the hook point onto `post_controller_constructor` (and the rest points) it returns the instance.

As the docs said:
> **post_controller_constructor** Called immediately after your controller is instantiated, but prior to any method calls happening.

My questions are:

1) Is this the design? I mean, like it is not possible and such?

2) Is it possible to access the CodeIgniter's instance inside the `pre_controller`? If yes, how?

**Comment by gphg** [comment]
Uh, okay...?

I'm straight to the point. I need Uri and Cache libraries to be loaded on `pre_controller` for HTTP caching and rate limiting. It's something like this: https://www.digitalocean.com/community/tutorials/how-to-implement-php-rate-limiting-with-redis-on-ubuntu-20-04

It requires a client identifier. The article mentions IP address, but in my case, i might going to use token served as cookie.

**Comment by gxgpet** [comment]
There are [some](https://www.codeigniter.com/userguide3/general/controllers.html?highlight=remap#remapping-method-calls) [ways](https://www.codeigniter.com/userguide3/general/core_classes.html) of hooking into pre-controller's-method (because this seems to be what you are trying to do). Please read the user guide thoroughly, it has many examples and situations very well explained and what to do for those.

If you need further help specifically for your own project, remember that we recommend people to use the forums.

**Comment by narfbg** [comment]
> Uh, okay...?

I suppose you didn't catch what I was saying.

As I already said, `get_instance()` returns the controller instance. At the same time, 'pre_controller' literally means "before controller". That is, of course, you cannot have the controller before the controller exists - otherwise it would be quite the paradox, wouldn't it? :)

It is possible to get the URI and Cache libraries without going through the controller, but you should really, really know what you're doing. If you can't figure it out yourself, then as unhelpful as this might seem, it's just not a good idea.
