### ISSUE TITLE
user_guide: modernizr.min.js is taken from remote server

### ISSUE THREAD

**Issue by tenzap** [bcit-ci/CodeIgniter#6103]
Currently the user guide references this js file from a remote server:
- https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js

Is this intended? Could it be made local, or rather not?

On the debian lintian checks, this is reported as a security breach:

https://lintian.debian.org/tags/privacy-breach-uses-embedded-file

**Comment by tenzap** [comment]
BTW, is there a release plan/ETD for 3.1.12 ?

**Comment by narfbg** [comment]
No, this isn't really intentional. It seems to be a part of the theme chosen for our docs a long, long time ago. I've never even touched that. I don't think it can be made local, because the reference is included at many different path levels, but I can add an integrity check for sure.

As for 3.1.12 ... Historically, we've never committed to estimates; things change, and all of our development happens on someone's spare time, so I can't answer that in a more straightforward way than "soon".
