### ISSUE TITLE
Sample code for cache_override hook

### ISSUE THREAD

**Issue by yetimdasturchi** [bcit-ci/CodeIgniter#6131]
Hello, how is the cache override hook used? There are examples?
p.s: codeigniter 3.x

**Comment by gxgpet** [comment]
Hi!

The cache_override hook replaces `CI_Output`'s [`_display_cache`](https://github.com/bcit-ci/CodeIgniter/blob/develop/system/core/Output.php#L661). If you look at the logic of this method, it simply tries to find, based on values of the current HTTP request, a static file on the disk, from the `cache` directory, and if it finds and it's not _expired_, then it outputs it and returns `TRUE`. Otherwise, `FALSE` is returned.

The hook should follow the same principle (especially about returning value), only that you are not forced to use the built-in filesystem caching mechanism.
