### ISSUE TITLE
Release new version with fixes for php 8.2

### ISSUE THREAD

**Issue by tenzap** [bcit-ci/CodeIgniter#6188]
Would you please release a new version with fixes for php 8.2?

Just recreating this because #6170 is now closed although support for 8.2 is not in yet and PR #6173 isn't 'in' either.

In the meantime, php 8.2 has hit Debian unstable and is likely to be part of the next Debian stable which could be released in a few month. ("new package" freeze is starting on 2023-02-12)

**Comment by gxgpet** [comment]
Hello,

The reason this isn't released yet (from my point of view), is that we are collecting bug reports and fixes that must be applied to the framework's codebase. While I tested the framework with some usual, basic scenarios, I can't possibly cover all situations. 

That's why, as you can see, we have recently received some pull requests opened here, and also comments regarding things we can fix for PHP 8.2. Personally, I appreciate all this help that ensures the next release will provide good compatibility of the framework with PHP 8.2, and those will be addressed in the following days. I also hope we shall perform the release in the near future, which shouldn't be that long already.

Kindly ask you to be patient about this, and please don't open other duplicates of #6170. I know we need to perform a release for the PHP 8.2 compatibility, and it will be done.

**Comment by gidzr** [comment]
Hi @gxgpet 

You've responded to this issue as being closed.

I've got what I thought was the latest version of CI3 3.1.13.. and it isn't updated for php8.2

Am I misunderstanding that 3.1..13 was updated for php 8.2 but not iterated on the version number? or is the php update a manual fix per the instructions and discussions on this issue?

I'd imagine you'd have to iterate to .14 .. but seems strange this issue is considered closed and nothing has changed to the codebase.

Cheers
