### ISSUE TITLE
only laravel

### ISSUE THREAD

**Issue by vahidalvandi** [bcit-ci/CodeIgniter#6274]

**Comment by datamweb** [comment]
I'd rather use a powerful old man [(CodeIgniter4)](https://github.com/codeigniter4/CodeIgniter4) than a newly matured young man (Laravel).

1. Lightweight and simplicity: CodeIgniter4 is known for its lightweight and simplicity. It has comprehensive and easy-to-understand documentation, which helps developers to easily familiarize themselves with it and start using it.
2. Fast performance: CodeIgniter4 provides fast performance due to its lightweight and optimized code structure. This is especially important for projects that require quick data processing.
3. Flexibility: CodeIgniter4 provides developers with the flexibility to easily adapt to the needs of their projects. This flexibility allows developers to easily apply their required configurations and changes.
4. Easy installation and setup: CodeIgniter4 has a simple installation and setup process, which helps developers to quickly start their projects and require less time for initial configurations and settings.

5. User community: CodeIgniter4 also has an active and vibrant user community that can assist developers throughout the development process and support their projects.

CodeIgniter4 has made significant advancements in development, with responsive and friendly developers. Additionally, CodeIgniter offers official packages such as Shield, Settings, Tasks, Queue and more. These packages provide additional functionality and tools to developers, enhancing the overall development experience and productivity. The community around CodeIgniter is active and supportive, contributing to its growth and evolution over time.

Perhaps if CodeIgniter4 focused more on advertising and marketing, CodeIgniter4 wouldn't be as underrated. Additionally, many websites currently use CodeIgniter4 for development but may not express it openly.

CodeIgniter4 is currently being developed on a daily basis by contributors. Its documentation is becoming clearer, and new features are being added regularly. Moreover, it is compatible with various PHP versions ranging from 7.4 to 8.3, ensuring that developers are not limited by their PHP version choices. This active development cycle, along with its compatibility across PHP versions, makes CodeIgniter4 a versatile and evolving framework for web development.

However, it should be noted that the choice between CodeIgniter4 and Laravel depends on the specific requirements and constraints of each project, and each has its own advantages and disadvantages.
